import { regions } from "../regions"
import { criteria } from "../criteria"

/**
 * @type {Array.<import(".").Album>}
 */
const albums = [
    {
        id: "madura_madura",
        title: "Madura",
        artist: "Madura",
        year: 1971,
        country: regions.USA,
        criteria: [criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.ODD_RHYTHM, criteria.C_JAZZ, criteria.JAM, criteria.BLUESY, criteria.TRANSITION],
        selectedTrackTitle: "Drinking No Wine",
        selectedTrackYtId: "EeeFV_iMsTI",
        spotifyId: "4156YoZJTUAXJOXsoIXHkM",
        deezerId: "276308802",
        designers: [],
        similarAlbums: ["sky_king_secret_sauce", "frank_zappa_apostrophe"],
        isAGem: false,
    },
    {
        id: "madura_madura_ii",
        title: "Madura II",
        artist: "Madura",
        year: 1973,
        country: regions.USA,
        criteria: [criteria.FANFARE, criteria.C_JAZZ, criteria.C_ELECTRO, criteria.ODD_RHYTHM, criteria.ORCHESTRAL_PARTS, criteria.FEMALE, criteria.ART_POP],
        selectedTrackTitle: "Doctor Honoris Causa",
        selectedTrackYtId: "6Ga7Azzgn0s",
        spotifyId: null,
        deezerId: null,
        designers: ["John Berg"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "magic_spell_is_there_anywhere_a_gas_station",
        title: "Is There Anywhere A Gas Station?",
        artist: "Magic Spell",
        year: 1980,
        country: regions.SWITZERLAND,
        criteria: [criteria.JAM, criteria.C_PSYCHE, criteria.C_ELECTRO, criteria.SYMPHONIC],
        selectedTrackTitle: "Turkish Invasion",
        selectedTrackYtId: "3RHzfQQn1Zs",
        spotifyId: null,
        deezerId: null,
        designers: ["Roman Spiess"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "magma_magma",
        title: "Magma",
        artist: "Magma",
        year: 1970,
        country: regions.FRANCE,
        criteria: [criteria.STORYLINE, criteria.EXPERIMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.SPECTACULAR, criteria.ZEUHL, criteria.ROCK_OPERA, criteria.SCI_FI],
        selectedTrackTitle: "Kobaïa",
        selectedTrackYtId: "TAtaaxb2TVU",
        spotifyId: "2Dxds4KnG03MiNlxB9AMev",
        deezerId: "44079",
        designers: ["M.J. Petit"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "magma_1001_centigrades",
        title: "1001° Centigrades",
        artist: "Magma",
        year: 1971,
        country: regions.FRANCE,
        criteria: [criteria.STORYLINE, criteria.EXPERIMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.SPECTACULAR, criteria.ZEUHL, criteria.ROCK_OPERA, criteria.SCI_FI],
        selectedTrackTitle: "Ki Ïahl Ö Lïahk",
        selectedTrackYtId: "gbVas9ZMVgk",
        spotifyId: "0TDe5JNrVMvYJhA6Wk3kYe",
        deezerId: null,
        designers: ["Christian Vander", "Gérald Nimal"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "magma_mekanik_destruktiw_kommandoh",
        title: "Mëkanïk Dëstruktïẁ Kömmandöh",
        artist: "Magma",
        year: 1973,
        country: regions.FRANCE,
        criteria: [criteria.STORYLINE, criteria.EXPERIMENTAL, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.SPECTACULAR, criteria.ZEUHL, criteria.ROCK_OPERA, criteria.SCI_FI, criteria.FEMALE],
        selectedTrackTitle: "Da Zeuhl Ẁortz Mëkanïk",
        selectedTrackYtId: "B5UZVtUC3V0",
        spotifyId: "6MDeMi4c1Zo1KRKtCgZpsb",
        deezerId: "44083",
        designers: [],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "magma_wurdah_itah",
        title: "Ẁurdah Ïtah",
        artist: "Magma",
        year: 1974,
        country: regions.FRANCE,
        criteria: [criteria.EXPERIMENTAL, criteria.TRANSITION, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.SPECTACULAR, criteria.ZEUHL, criteria.ROCK_OPERA, criteria.SOUNDTRACK, criteria.FEMALE],
        selectedTrackTitle: "De Zeuhl Ündazïr",
        selectedTrackYtId: "8rRdPY9fTdU",
        spotifyId: "51oBKp7YV5ZEVc2PQpU7yx",
        deezerId: "44080",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "magma_kohntarkosz",
        title: "Köhntarkösz",
        artist: "Magma",
        year: 1974,
        country: regions.FRANCE,
        criteria: [criteria.EXPERIMENTAL, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.C_PSYCHE, criteria.SPECTACULAR, criteria.ZEUHL, criteria.ROCK_OPERA, criteria.LENGTHY_TRACKS, criteria.FEMALE, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Köhntarkösz (Part II)",
        selectedTrackYtId: "4h3yHBDRoek",
        spotifyId: "7k6xCjMzSg4WFFxRNDq7pm",
        deezerId: "44081",
        designers: ["Fabio Nicoli"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "magma_udu_wudu",
        title: "Üdü Ẁüdü",
        artist: "Magma",
        year: 1976,
        country: regions.FRANCE,
        criteria: [criteria.SYMPHONIC, criteria.C_JAZZ, criteria.C_ELECTRO, criteria.C_PSYCHE, criteria.SPECTACULAR, criteria.ZEUHL, criteria.ROCK_OPERA, criteria.FEMALE, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: "Üdü Ẁüdü",
        selectedTrackYtId: "cSqsfVhcJSo",
        spotifyId: "3TOrYzTzra3GW7iqQmKpLC",
        deezerId: "21891",
        designers: ["Klaus Blasquiz"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "magma_attahk",
        title: "Attahk",
        artist: "Magma",
        year: 1978,
        country: regions.FRANCE,
        criteria: [criteria.SYMPHONIC, criteria.JAZZ, criteria.JAZZY_GROOVY, criteria.ODD_RHYTHM, criteria.ZEUHL, criteria.ROCK_OPERA, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Rindë",
        selectedTrackYtId: "e26I9r4msLE",
        spotifyId: "7CEoMKWc490SjtEMJ5va6D",
        deezerId: "44078",
        designers: ["H.R. Giger"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mahavishnu_orchestra_the_inner_mounting_flame",
        title: "The Inner Mounting Flame",
        artist: "Mahavishnu Orchestra",
        year: 1971,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZ, criteria.JAZZY_GROOVY, criteria.FEMALE],
        selectedTrackTitle: "A Lotus On Irish Streams",
        selectedTrackYtId: "1m5V8zbyR2M",
        spotifyId: "0chWLemqlI6G1GOEr1q1bz",
        deezerId: "98995",
        designers: [],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "mahavishnu_orchestra_birds_of_fire",
        title: "Birds Of Fire",
        artist: "Mahavishnu Orchestra",
        year: 1973,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Sanctuary",
        selectedTrackYtId: "d08lMTHzYdY",
        spotifyId: "6SLknspfGod3v3TyWawl8J",
        deezerId: "97632",
        designers: ["Ashok"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mahavishnu_orchestra_between_nothingness_and_eternity",
        title: "Between Nothingness And Eternity",
        artist: "Mahavishnu Orchestra",
        year: 1973,
        country: regions.USA,
        criteria: [criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.LIVE, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "La Mère De La Mer",
        selectedTrackYtId: "8YrPXjladAw",
        spotifyId: "1SkdtzukyNIq2wTUiVeyuk",
        deezerId: "116761",
        designers: ["Ashok"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mahavishnu_orchestra_apocalypse",
        title: "Apocalypse",
        artist: "Mahavishnu Orchestra",
        year: 1974,
        country: regions.USA,
        criteria: [criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.BLENDS, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Hymn To Him",
        selectedTrackYtId: "M9eegi9dd6g",
        spotifyId: "2LYPJHnU2WC7RbHXvJxXZX",
        deezerId: "115857",
        designers: ["Ashok"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mahavishnu_orchestra_visions_of_emerald_beyond",
        title: "Visions Of Emerald Beyond",
        artist: "Mahavishnu Orchestra",
        year: 1975,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: `Lila's Dance`,
        selectedTrackYtId: "ZSh0nmretso",
        spotifyId: "7J0OL2Ai73lJZu06coM0Oo",
        deezerId: "115665",
        designers: ["Ashok"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mahogany_rush_maxoom",
        title: "Maxoom",
        artist: "Mahogany Rush",
        year: 1972,
        country: regions.QUEBEC,
        criteria: [criteria.JAM, criteria.C_PSYCHE, criteria.ROCK, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Buddy",
        selectedTrackYtId: "zvHYArrWQ",
        spotifyId: "2dfmgmxi7UYxCFxHVx3Ie6",
        deezerId: null,
        designers: ["Hans Memling"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mahogany_rush_child_of_the_novelty",
        title: "Child Of The Novelty",
        artist: "Mahogany Rush",
        year: 1974,
        country: regions.QUEBEC,
        criteria: [criteria.JAM, criteria.C_PSYCHE, criteria.ROCK, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Child Of The Novelty",
        selectedTrackYtId: "4fVfpcHMxWg",
        spotifyId: "2j2VetN4wKo311qTel05JU",
        deezerId: null,
        designers: ["Bob Lemm", "Ivan Schwartz"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mahogany_rush_strange_universe",
        title: "Strange Universe",
        artist: "Mahogany Rush",
        year: 1975,
        country: regions.QUEBEC,
        criteria: [criteria.JAM, criteria.C_PSYCHE, criteria.ROCK, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Strange Universe",
        selectedTrackYtId: "gbuNknh5lhI",
        spotifyId: "5PxuOEcNc9aQKjZZE5AMdx",
        deezerId: null,
        designers: ["Bob Lemm", "Ivan Schwartz"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "malicorne_pierre_de_grenoble",
        title: "Pierre De Grenoble",
        artist: "Malicorne",
        year: 1973,
        country: regions.FRANCE,
        criteria: [criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.MEDIEVAL],
        selectedTrackTitle: "Pierre De Grenoble",
        selectedTrackYtId: "MHipWZs224w",
        spotifyId: "0JHEmxZJhFsUSlUcGnbIRW",
        deezerId: "251373",
        designers: ["Christian Welter"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "malicorne_colin",
        title: "Colin",
        artist: "Malicorne",
        year: 1974,
        country: regions.FRANCE,
        criteria: [criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.MEDIEVAL],
        selectedTrackTitle: "La Pernette",
        selectedTrackYtId: "0aqCx7zmZus",
        spotifyId: "0uuKARJ0Cij4ZCLRIuEj4h",
        deezerId: "250060",
        designers: ["Albert Riou"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "malicorne_le_mariage_anglais",
        title: "Le Mariage Anglais",
        artist: "Malicorne",
        year: 1975,
        country: regions.FRANCE,
        criteria: [criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.MEDIEVAL],
        selectedTrackTitle: "Le Garçon Jardinier",
        selectedTrackYtId: "j15LFZ4xUCc",
        spotifyId: "5hyGrvhr4k06s2PLJUnBC0",
        deezerId: "250061",
        designers: ["Albert Riou"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "malicorne_almanach",
        title: "Almanach",
        artist: "Malicorne",
        year: 1976,
        country: regions.FRANCE,
        criteria: [criteria.CONCEPT, criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.MEDIEVAL],
        selectedTrackTitle: "Le Luneux",
        selectedTrackYtId: "zaZtP2q3PiU",
        spotifyId: "2JM0OGBN3jBQ8zCgSoUVH3",
        deezerId: "250059",
        designers: ["Albert Riou", "Laurent Leserre"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "malicorne_nous_sommes_chanteurs_de_sornettes",
        title: "Nous Sommes Chanteurs De Sornettes",
        artist: "Malicorne",
        year: 1977,
        country: regions.FRANCE,
        criteria: [criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.MEDIEVAL],
        selectedTrackTitle: "Le Jardiner Du Couvent",
        selectedTrackYtId: "vmR4u7OV3ME",
        spotifyId: "3MLyB7zQdrSIBqT0uQsxQh",
        deezerId: null,
        designers: ["Laurent Lesserre"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "malicorne_lextraordinaire_tour_de_france_dadelard_rousseau_dit_nivernais_la_clef_des_coeurs_compagnon_charpentier_du_devoir",
        title: "L'extraordinaire Tour De France D'Adélard Rousseau, Dit Nivernais La Clef Des Cœurs, Compagnon Charpentier Du Devoir",
        artist: "Malicorne",
        year: 1978,
        country: regions.FRANCE,
        criteria: [criteria.CONCEPT, criteria.FANFARE, criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.MEDIEVAL, criteria.ODD_RHYTHM],
        selectedTrackTitle: "À Paris La Grande Ville",
        selectedTrackYtId: "bBEF3DXPajc",
        spotifyId: "1zBQPjZRxDdgsjdTP0iA0K",
        deezerId: "251370",
        designers: ["Alain Poirier"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "malicorne_le_bestiaire",
        title: "Le Bestiaire",
        artist: "Malicorne",
        year: 1979,
        country: regions.FRANCE,
        criteria: [criteria.CONCEPT, criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.MEDIEVAL, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "Jean Des Loups",
        selectedTrackYtId: "E8YPDRxb2-A",
        spotifyId: "4C91mXMnUw22yIi5omosDZ",
        deezerId: "251371",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "malicorne_balancoire_en_feu",
        title: "Balençoire En Feu",
        artist: "Malicorne",
        year: 1981,
        country: regions.FRANCE,
        criteria: [criteria.ROCK, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "Balançoire En Feu",
        selectedTrackYtId: "Hq8_4smwns0",
        spotifyId: "1JR2aZwyKHD80sE7pwb6XK",
        deezerId: "251366",
        designers: ["Richard Schaeffer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "malicorne_les_cathedrales_de_lindustrie",
        title: "Les Cathédrales De L'industrie",
        artist: "Malicorne",
        year: 1986,
        country: regions.FRANCE,
        criteria: [criteria.ART_POP, criteria.C_FOLK, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE, criteria.FRENCH, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Big Science (1,2,3)",
        selectedTrackYtId: "LKnxB8YXtAk",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "man_man",
        title: "Man",
        artist: "Man",
        year: 1971,
        country: regions.WALES,
        criteria: [criteria.JAM, criteria.C_PSYCHE, criteria.ROCK, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Would The Christians Wait Five Minutes? The Lions Are Having A Draw",
        selectedTrackYtId: "9fCs_QsrcSU",
        spotifyId: "78JGXwpxY2ZqO4ouyrG75k",
        deezerId: "319364",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "man_do_you_like_it_here_now_are_you_settling_in",
        title: "Do You Like It Here Now, Are You Settling In?",
        artist: "Man",
        year: 1971,
        country: regions.WALES,
        criteria: [criteria.JAM, criteria.ROCK, criteria.JAZZY_GROOVY, criteria.BLUESY],
        selectedTrackTitle: "All Good Clean Fun",
        selectedTrackYtId: "PllGouNiXlo",
        spotifyId: "5yGuU3tLCnsnPtexUBKL02",
        deezerId: "319368",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "man_be_good_to_yourself_at_least_once_a_day",
        title: "Be Good To Yourself At Least Once A Day",
        artist: "Man",
        year: 1972,
        country: regions.WALES,
        criteria: [criteria.JAM, criteria.ROCK, criteria.JAZZY_GROOVY, criteria.BLUESY],
        selectedTrackTitle: `C'mon`,
        selectedTrackYtId: "pZIg-fJU7vI",
        spotifyId: "6H63XRFZChnj9UIlHUdKI9",
        deezerId: "319365",
        designers: ["David Anstee"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_mandrake_memorial_the_mandrake_memorial",
        title: "The Mandrake Memorial",
        artist: "The Mandrake Memorial",
        year: 1968,
        country: regions.ENGLAND,
        criteria: [criteria.BAROQUE, criteria.C_PSYCHE, criteria.ROCK, criteria.SOFT],
        selectedTrackTitle: `Sunday Noon`,
        selectedTrackYtId: "p35o50UK_Zc",
        spotifyId: null,
        deezerId: null,
        designers: ["Milton Glaser"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_mandrake_memorial_medium",
        title: "Medium",
        artist: "The Mandrake Memorial",
        year: 1969,
        country: regions.ENGLAND,
        criteria: [criteria.BAROQUE, criteria.C_PSYCHE, criteria.C_FOLK, criteria.SOFT],
        selectedTrackTitle: `After Pascal`,
        selectedTrackYtId: "p5VvC-AZ8bU",
        spotifyId: null,
        deezerId: null,
        designers: ["Milton Glaser"],
        similarAlbums: ["jefferson_airplane_crown_of_creation"],
        isAGem: false,
    },
    {
        id: "the_mandrake_memorial_puzzle",
        title: "Puzzle",
        artist: "The Mandrake Memorial",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.BAROQUE, criteria.ORCHESTRAL_PARTS, criteria.C_PSYCHE, criteria.FEMALE, criteria.LENGTHY_TRACKS, criteria.PATCHWORK, criteria.TRANSITION, criteria.CONCEPT],
        selectedTrackTitle: `Earthfriend Prelude`,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Milton Glaser", "Maurits Cornelis Escher"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "maneige_maneige",
        title: "Maneige",
        artist: "Maneige",
        year: 1974,
        country: regions.QUEBEC,
        criteria: [criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.EXPERIMENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.SYMPHONIC, criteria.INSTRUMENTAL, criteria.ODD_RHYTHM, criteria.C_JAZZ, criteria.FRENCH, criteria.PIANO],
        selectedTrackTitle: `Le Rafiot`,
        selectedTrackYtId: "U6e2MX9lUls",
        spotifyId: "3eaJIFOZ6tlVQ66OklSWoE",
        deezerId: "47211732",
        designers: ["Gilles Brault"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "maneige_les_porches",
        title: "Les Porches",
        artist: "Maneige",
        year: 1975,
        country: regions.QUEBEC,
        criteria: [criteria.LENGTHY_TRACKS, criteria.UNCOMMON_INSTRUMENTS, criteria.FRENCH, criteria.SYMPHONIC, criteria.PIANO, criteria.BAROQUE],
        selectedTrackTitle: `Les Porches De Notre-Dame`,
        selectedTrackYtId: "JuCq9n8jW8E",
        spotifyId: "2yl7108VONO5PBcosjj4dH",
        deezerId: "47209352",
        designers: [],
        similarAlbums: [],
        isAGem: false, // TODO almost
    },
    {
        id: "maneige_ni_vent_ni_nouvelle",
        title: "Ni Vent... Ni Nouvelle",
        artist: "Maneige",
        year: 1977,
        country: regions.QUEBEC,
        criteria: [criteria.ODD_RHYTHM, criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `Les Folleries`,
        selectedTrackYtId: "mNdc8GYYDZc",
        spotifyId: "3ZKTikxMbMgelmfLdghfEt",
        deezerId: "47211692",
        designers: ["Claude Lamarre", "Fernand Leclerc", "Richard Packwood"],
        similarAlbums: ["focus_focus_3"],
        isAGem: false,
    },
    {
        id: "maneige_libre_service",
        title: "Libre Service",
        artist: "Maneige",
        year: 1978,
        country: regions.QUEBEC,
        criteria: [criteria.ODD_RHYTHM, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT, criteria.SOFT_SEVENTIES, criteria.JAM, criteria.INSTRUMENTAL, criteria.C_ELECTRO, criteria.JAZZY_GROOVY, criteria.C_JAZZ],
        selectedTrackTitle: `Les Pétoncles`,
        selectedTrackYtId: "uo2dazo2sbs",
        spotifyId: "3WCM79MC3U27y5eeyD4vRi",
        deezerId: "47206822",
        designers: ["William Roberto Wilson", "Serge Clément"],
        similarAlbums: [],
        isAGem: false, // TODO almost a gem!!
    },
    {
        id: "maneige_composite",
        title: "Composite",
        artist: "Maneige",
        year: 1979,
        country: regions.QUEBEC,
        criteria: [criteria.LIVE, criteria.INSTRUMENTAL, criteria.C_ELECTRO, criteria.JAM, criteria.JAZZY_GROOVY, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT, criteria.C_JAZZ],
        selectedTrackTitle: `L'éveil Et L'approche`, // defaut OU toujours trop tard
        selectedTrackYtId: "todo",
        spotifyId: null,
        deezerId: null,
        designers: ["Christiane Valcourt", "André Panneton"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "maneige_montreal_6am",
        title: "Montréal, 6am",
        artist: "Maneige",
        year: 1980,
        country: regions.QUEBEC,
        criteria: [criteria.INSTRUMENTAL, criteria.SOFT_SEVENTIES, criteria.ODD_RHYTHM, criteria.C_JAZZ],
        selectedTrackTitle: `Popozof`,
        selectedTrackYtId: "uXgLdj5_GN4",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: ["camel_breathless"],
        isAGem: false,
    },
    {
        id: "maneige_images",
        title: "Images",
        artist: "Maneige",
        year: 1983,
        country: regions.QUEBEC,
        criteria: [criteria.INSTRUMENTAL, criteria.ODD_RHYTHM, criteria.C_JAZZ, criteria.SOFT_SEVENTIES, criteria.SOFT, criteria.C_ELECTRO],
        selectedTrackTitle: `Transport`,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["André Perry", "André Panneton"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "manfred_mann_chapter_three_manfred_mann_chapter_three",
        title: `Manfred Mann Chapter Three`,
        artist: "Manfred Mann Chapter Three",
        year: 1969,
        country: regions.ENGLAND,
        criteria: [criteria.C_JAZZ, criteria.C_PSYCHE, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Travelling Lady",
        selectedTrackYtId: "dQWchOJpsiA",
        spotifyId: "1qdXxoCkBgArwWQcf7RM1v",
        deezerId: "13185672",
        designers: ["Luke Weall", "Jack Levy"],
        similarAlbums: ["frank_zappa_the_grand_wazoo"],
        isAGem: false,
    },
    {
        id: "manfred_mann_chapter_three_volume_two",
        title: `Volume Two`,
        artist: "Manfred Mann Chapter Three",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.C_JAZZ, criteria.C_PSYCHE, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.LENGTHY_TRACKS, criteria.JAM],
        selectedTrackTitle: "Lady Ace",
        selectedTrackYtId: "yaJdw5UX_fw",
        spotifyId: "2CyA4yTzaT15y0RoKaCYbN",
        deezerId: "13185788",
        designers: ["Marcus Keef"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "manilla_road_invasion",
        title: `Invasion`,
        artist: "Manilla Road",
        year: 1980,
        country: regions.USA,
        criteria: [criteria.HEAVY, criteria.C_PSYCHE, criteria.SPACY, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: "Cat And Mouse",
        selectedTrackYtId: "8Z0JUBEmjEQ",
        spotifyId: null,
        deezerId: null,
        designers: ["Sharon Jesik", "Manilla Road"],
        similarAlbums: ["judas_priest_sin_after_sin"],
        isAGem: false,
    },
    {
        id: "manilla_road_metal",
        title: `Metal`,
        artist: "Manilla Road",
        year: 1982,
        country: regions.USA,
        criteria: [criteria.HEAVY, criteria.ROCK],
        selectedTrackTitle: "Cage Of Mirrors",
        selectedTrackYtId: "rKog5u9dX-8",
        spotifyId: null,
        deezerId: null,
        designers: ["Music Forward Group"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "maquina_why",
        title: `Why?`,
        artist: "Máquina!",
        year: 1970,
        country: regions.SPAIN,
        criteria: [criteria.LENGTHY_TRACKS, criteria.JAM, criteria.ROCK, criteria.C_PSYCHE],
        selectedTrackTitle: "Why (1ª Parte)",
        selectedTrackYtId: "iLtu68lwKgQ",
        spotifyId: null,
        deezerId: null,
        designers: ["Jordi Batiste"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "la_maquina_de_hacer_pajaros_la_maquina_de_hacer_pajaros",
        title: `La Máquina De Hacer Pájaros`,
        artist: "La Máquina De Hacer Pájaros",
        year: 1976,
        country: regions.ARGENTINA,
        criteria: [criteria.C_ELECTRO, criteria.SYMPHONIC, criteria.SPANISH, criteria.JAM, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Ah, Te Vi Entre Las Luces",
        selectedTrackYtId: "GNXsl13WT_U",
        spotifyId: "4uXadaCsBVwLK6s5V14Kjw",
        deezerId: "1215800",
        designers: ["Cristóbal Reinoso", "Juan Oreste Gatti"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "la_maquina_de_hacer_pajaros_peliculas",
        title: `Películas`,
        artist: "La Máquina De Hacer Pájaros",
        year: 1977,
        country: regions.ARGENTINA,
        criteria: [criteria.C_ELECTRO, criteria.SYMPHONIC, criteria.SPANISH, criteria.ODD_RHYTHM, criteria.JAM, criteria.BAROQUE],
        selectedTrackTitle: "Qué Se Puede Hacer Salvo Ver Películas",
        selectedTrackYtId: "6Lk5FrtASVo",
        spotifyId: "6hlwylwLskentQQsbTKpcj",
        deezerId: "1217378",
        designers: ["Juan Oreste Gatti"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "marcello_capra_aria_mediterranea",
        title: `Aria Mediterranea`,
        artist: "Manilla Road",
        year: 1978,
        country: regions.ITALY,
        criteria: [criteria.FOLK, criteria.INSTRUMENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.JAM],
        selectedTrackTitle: "Il Sole Sulla Palude",
        selectedTrackYtId: "zXuj2BJ-dsQ",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "marillion_script_for_a_jesters_tear",
        title: `Script For A Jester's Tear`,
        artist: "Marillion",
        year: 1983,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK_OPERA, criteria.ART_POP, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Forgotten Sons",
        selectedTrackYtId: "RtiUoEbwD7Q",
        spotifyId: "5mbtDQJwsioLCEGIT1cbOJ",
        deezerId: "302509",
        designers: ["Mark Wilkinson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "marillion_fugazi",
        title: "Fugazi",
        artist: "Marillion",
        year: 1984,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.GLITTER, criteria.ROCK_OPERA, criteria.ART_POP, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Punch & Judy",
        selectedTrackYtId: "OWrwYsSt6OE",
        spotifyId: "3fyFddxAoeW4JIuczl8lXU",
        deezerId: "302511",
        designers: ["Mark Wilkinson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "marillion_misplaced_childhood",
        title: "Misplaced Childhood",
        artist: "Marillion",
        year: 1985,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.TRANSITION, criteria.ROCK_OPERA, criteria.ART_POP, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Blind Curve",
        selectedTrackYtId: "5aMaGblvd5o",
        spotifyId: "3ExyKxlUkqD41I8tQumMDF",
        deezerId: "51780972",
        designers: ["Mark Wilkinson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "marillion_clutching_at_straws",
        title: "Clutching At Straws",
        artist: "Marillion",
        year: 1987,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.TRANSITION, criteria.ROCK_OPERA, criteria.ART_POP, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Just For The Record",
        selectedTrackYtId: "Q79xkgIXhmU",
        spotifyId: "7M6qdztBAZADkaYJ6bIEhF",
        deezerId: "302510",
        designers: ["Mark Wilkinson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "markus_stockhausen_and_jasper_vant_hof_aqua_sansa",
        title: "Aqua Sansa",
        artist: "Markus Stockhausen & Jasper Van't Hof",
        year: 1980,
        country: regions.GERMANY,
        criteria: [criteria.INSTRUMENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.EXPERIMENTAL, criteria.LENGTHY_TRACKS, criteria.ELECTRO, criteria.C_JAZZ],
        selectedTrackTitle: "Takone",
        selectedTrackYtId: "_KkpjkrRWI8",
        spotifyId: null,
        deezerId: null,
        designers: ["Markus Stockhausen"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "marvin_welch_and_farrar_marvin_welch_and_farrar",
        title: "Marvin, Welch & Farrar",
        artist: "Marvin, Welch & Farrar",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.FOLK, criteria.SOFT, criteria.BAROQUE],
        selectedTrackTitle: "A Thousand Conversations",
        selectedTrackYtId: "Zoa92feWUC8",
        spotifyId: null,
        deezerId: null,
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "marvin_welch_and_farrar_second_opinion",
        title: "Second Opinion",
        artist: "Marvin, Welch & Farrar",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.C_FOLK, criteria.SOFT, criteria.BAROQUE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Tiny Robin",
        selectedTrackYtId: "aUv9VMfMhzs",
        spotifyId: null,
        deezerId: null,
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mary_butterworth_mary_butterworth",
        title: "Mary Butterworth",
        artist: "Mary Butterworth",
        year: 1969,
        country: regions.USA,
        criteria: [criteria.HUMBLE, criteria.BLUESY, criteria.UNCOMMON_INSTRUMENTS, criteria.JAM],
        selectedTrackTitle: "Optional Blues",
        selectedTrackYtId: "0R6hmGzKOhE",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "masayoshi_takanaka_the_rainbow_goblins",
        title: "The Rainbow Goblins",
        artist: "Masayoshi Takanaka",
        year: 1981,
        country: regions.JAPAN,
        criteria: [criteria.ORCHESTRAL_PARTS, criteria.UNCOMMON_INSTRUMENTS, criteria.FANTASY, criteria.STORYLINE, criteria.ODD_RHYTHM, criteria.SOFT_SEVENTIES, criteria.JAZZY_GROOVY, criteria.C_ELECTRO, criteria.JAM],
        selectedTrackTitle: "Tiny Robin",
        selectedTrackYtId: "aUv9VMfMhzs",
        spotifyId: null,
        deezerId: null,
        designers: ["Tsunemi Morimoto"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "masters_apprentices_masters_apprentices",
        title: "Master's Apprentices",
        artist: "Master's Apprentices",
        year: 1971,
        country: regions.AUSTRALIA,
        criteria: [criteria.ROCK, criteria.C_FOLK, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Death Of A King",
        selectedTrackYtId: "d8kO2yqqbVU",
        spotifyId: "4QHGwnJNtpEgYOyjrpoaED",
        deezerId: "218687052",
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "masters_apprentices_a_toast_to_panama_red",
        title: "A Toast To Panama Red",
        artist: "Master's Apprentices",
        year: 1971,
        country: regions.AUSTRALIA,
        criteria: [criteria.ROCK, criteria.C_FOLK],
        selectedTrackTitle: "Games We Play - Part II",
        selectedTrackYtId: "4ZIHyd89Ahw",
        spotifyId: "6m0gexdhgGdsEJhGPDd6zo",
        deezerId: "210333742",
        designers: ["James Keays"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "matching_mole_matching_mole",
        title: "Matching Mole",
        artist: "Matching Mole",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.C_PSYCHE, criteria.C_JAZZ, criteria.TRANSITION, criteria.FUNNY],
        selectedTrackTitle: "Part Of The Dance",
        selectedTrackYtId: "7pvk1eIhFeM",
        spotifyId: "24Z8SaFvPzP8IE6b1Dzj94",
        deezerId: "1215173",
        designers: ["Alan Cracknell"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "matching_mole_little_red_record",
        title: "Little Red Record",
        artist: "Matching Mole",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.C_PSYCHE, criteria.C_JAZZ, criteria.TRANSITION, criteria.FUNNY, criteria.INSTRUMENTAL],
        selectedTrackTitle: "Brandy As In Benj",
        selectedTrackYtId: "3pRLir_Evds",
        spotifyId: "0Qwo3GaODDq65v6xKWKqne",
        deezerId: "683834",
        designers: ["Bob Norrington"],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO introuvable Maurizio Fabrizio - Azzurri Orizzonti
    {
        id: "maurizio_fabrizio_movimenti_nel_cielo",
        title: "Movimenti Nel Cielo",
        artist: "Maurizio Fabrizio",
        year: 1978,
        country: regions.ITALY,
        criteria: [criteria.BAROQUE, criteria.UNCOMMON_INSTRUMENTS, criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.ORCHESTRAL_PARTS, criteria.ODD_RHYTHM, criteria.C_FOLK, criteria.PIANO],
        selectedTrackTitle: "Movenze Degli Anelli Di Saturno",
        selectedTrackYtId: "cqVCGN8r5m4",
        spotifyId: "3g1iBYuYe2Un4Q3KuoBEro",
        deezerId: "597967",
        designers: ["Mario Convertino"],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO introuvable Maurizio Fabrizio - Primo
    // TODO introuvable Maurizio Fabrizio - Personaggi
    {
        id: "maxophone_maxophone",
        title: "Maxophone",
        artist: "Maxophone",
        year: 1975,
        country: regions.ITALY,
        criteria: [criteria.SYMPHONIC, criteria.C_JAZZ, criteria.UNCOMMON_INSTRUMENTS, criteria.ITALIAN, criteria.BAROQUE, criteria.ODD_RHYTHM, criteria.RENAISSANCE, criteria.C_ELECTRO],
        selectedTrackTitle: "Fase",
        selectedTrackYtId: "GWPZ_jPBnAs",
        spotifyId: "2ANyO7tZgN5uS2uIqX9hS8",
        deezerId: "8533980",
        designers: ["Cesare Monti", "Wanda Monti"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "may_blitz_may_blitz",
        title: "May Blitz",
        artist: "May Blitz",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.C_PSYCHE],
        selectedTrackTitle: "Tomorrow May Come",
        selectedTrackYtId: "-JKaFlLHcQ8",
        spotifyId: "6TZiaRqylZpos2gCvCIsLu",
        deezerId: "671893",
        designers: ["Tony Benyon"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "may_blitz_the_2nd_of_may",
        title: "The 2nd Of May",
        artist: "May Blitz",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.JAM, criteria.C_PSYCHE, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Snakes And Ladders",
        selectedTrackYtId: "OKy6SGSGQbw",
        spotifyId: "28ftlSGxhgcNAJSUrPQ8E3",
        deezerId: "424690",
        designers: ["Tony Benyon"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mcchurch_soundroom_delusion",
        title: "Delusion",
        artist: "McChurch Soundroom",
        year: 1971,
        country: regions.SWITZERLAND,
        criteria: [criteria.JAM, criteria.ROCK, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "What Are You Doin'",
        selectedTrackYtId: "jwqADvlRsNU",
        spotifyId: "4Xjz22sBf4GzAoNLi28Yo9",
        deezerId: "99930132",
        designers: ["Holger Matthies"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mcluhan_anomaly",
        title: "Anomaly",
        artist: "McLuhan",
        year: 1972,
        country: regions.USA,
        criteria: [criteria.FUNNY, criteria.FANFARE, criteria.LENGTHY_TRACKS, criteria.ODD_RHYTHM, criteria.C_PSYCHE, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "The Monster Bride",
        selectedTrackYtId: "OKy6SGSGQbw",
        spotifyId: null,
        deezerId: null,
        designers: [`Al D'Agostino`],
        similarAlbums: ["frank_zappa_big_swifty"],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "mcoil_all_our_hopes",
        title: "All Our Hopes",
        artist: "McOil",
        year: 1979,
        country: regions.GERMANY,
        criteria: [criteria.HEAVY, criteria.C_ELECTRO, criteria.JAM],
        selectedTrackTitle: "This Time Should Never End",
        selectedTrackYtId: "b0xz88ajD4w",
        spotifyId: "5vf9QLDZx84LPqZClUPWJN",
        deezerId: null,
        designers: [`Alex Pohle`],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "meat_loaf_bat_out_of_hell",
        title: "Bat Out Of Hell",
        artist: "Meat Loaf",
        year: 1977,
        country: regions.USA,
        criteria: [criteria.ROCK, criteria.HEAVY, criteria.ROCK_OPERA, criteria.SPECTACULAR, criteria.ORCHESTRAL_PARTS, criteria.FEMALE, criteria.FANFARE],
        selectedTrackTitle: "Bat Out Of Hell",
        selectedTrackYtId: "x7ES7ueI7p0",
        spotifyId: "6mvI80w5r78niBmwtu7RF9",
        deezerId: "13195340",
        designers: [`Richard Corben`],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "meat_loaf_dead_ringer",
        title: "Dead Ringer",
        artist: "Meat Loaf",
        year: 1981,
        country: regions.USA,
        criteria: [criteria.ROCK, criteria.HEAVY, criteria.ROCK_OPERA, criteria.SPECTACULAR, criteria.ARENA, criteria.FEMALE, criteria.FANFARE],
        selectedTrackTitle: "Peel Out",
        selectedTrackYtId: "xEQDvMxARKw",
        spotifyId: "2Y9CaNn1xUX2EJWIiBG45i",
        deezerId: "70986",
        designers: [`Bernie Wrightson`],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "melmoth_la_devanture_des_ivresses",
        title: "La Devanture Des Ivresses",
        artist: "Melmoth",
        year: 1970,
        country: regions.FRANCE,
        criteria: [criteria.EXPERIMENTAL, criteria.FRENCH, criteria.UNCOMMON_INSTRUMENTS, criteria.C_FOLK],
        selectedTrackTitle: "Vous Direz Que Je Suis Tombé",
        selectedTrackYtId: "C1JyoHx0ikw",
        spotifyId: "1BFdltbpS4gS5pI0QcflY7",
        deezerId: "300000",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "melmoth_obsolete",
        title: "Obsolète",
        artist: "Melmoth",
        year: 1971,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.C_FOLK, criteria.LENGTHY_TRACKS, criteria.JAM],
        selectedTrackTitle: "Cielo Drive / 17",
        selectedTrackYtId: "hM1gROzHBKQ",
        spotifyId: "452SYttSnCqRGkely3Epfz",
        deezerId: "299999",
        designers: ["Benjamin Baltimore", "Dashiell Hedayat"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "memoriance_et_apres",
        title: "Et Après...",
        artist: "Mémoriance",
        year: 1976,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.LENGTHY_TRACKS, criteria.C_ELECTRO, criteria.ODD_RHYTHM, criteria.SYMPHONIC],
        selectedTrackTitle: "Et Après...",
        selectedTrackYtId: "L7_TWbKS5b4",
        spotifyId: null,
        deezerId: null,
        designers: ["Michel Aze"],
        similarAlbums: ["pulsar_the_strands_of_the_future"],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "memoriance_lecume_des_jours",
        title: `L'écume Des Jours `,
        artist: "Mémoriance",
        year: 1979,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.PATCHWORK, criteria.C_ELECTRO, criteria.STORYLINE, criteria.ODD_RHYTHM, criteria.ROCK_OPERA, criteria.TRANSITION],
        selectedTrackTitle: "Une Femme Si Bête",
        selectedTrackYtId: "DaEQUMnx0x0",
        spotifyId: null,
        deezerId: null,
        designers: ["Hubert Pathieu"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "merlin_merlin",
        title: "Merlin",
        artist: "Merlin",
        year: 1984,
        country: regions.GERMANY,
        criteria: [criteria.FEMALE, criteria.SOFT, criteria.C_FOLK, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "You Know That...",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "merlin_ar_merlin",
        title: "Merlin",
        artist: "Merlin (AR)",
        year: 1980,
        country: regions.ARGENTINA,
        criteria: [criteria.SPANISH, criteria.GLITTER, criteria.C_ELECTRO, criteria.TECHNICAL, criteria.BAROQUE, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Hablar Del Camino",
        selectedTrackYtId: "mYWcwsZN730",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO INTROUVABLE Messengers - First Message - PROG?
    {
        id: "messengers_children_of_tomorrow",
        title: "Children Of Tomorrow",
        artist: "Messengers",
        year: 1977,
        country: regions.GERMANY,
        criteria: [criteria.FEMALE, criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.ORCHESTRAL_PARTS, criteria.UNCOMMON_INSTRUMENTS, criteria.JAM],
        selectedTrackTitle: "Sacrewinsky",
        selectedTrackYtId: "SYVR1DcK8Eg",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: ["chicago_chicago_vii"],
        isAGem: false,
    },
    {
        id: "metabolisme_tempus_fugit",
        title: "Tempus Fugit",
        artist: "Métabolisme",
        year: 1977,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC],
        selectedTrackTitle: "Apôtres Et Martyrs",
        selectedTrackYtId: "VX7hkYazq58",
        spotifyId: "0xcbIKxMZRUy5MpMQhMyg2",
        deezerId: "438874",
        designers: ["Marie-France Peronne"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "metropolis_metropolis",
        title: "Metropolis",
        artist: "Metropolis",
        year: 1974,
        country: regions.GERMANY,
        criteria: [criteria.C_PSYCHE, criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Dreamweaver",
        selectedTrackYtId: "7ukt0a0y6T8",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mia_transparencias",
        title: "Transparencias",
        artist: "MIA",
        year: 1976,
        country: regions.ARGENTINA,
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.RENAISSANCE, criteria.LENGTHY_TRACKS, criteria.FEMALE, criteria.SPANISH],
        selectedTrackTitle: "Transparencias",
        selectedTrackYtId: "cWt-kTqPSrY",
        spotifyId: null,
        deezerId: null,
        designers: ["Liliana Vitale", "Emilio Rivoira", "María Pita", "Donvi"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mia_magicos_juegos_del_tiempo",
        title: "Mágicos Juegos Del Tiempo",
        artist: "MIA",
        year: 1977,
        country: regions.ARGENTINA,
        criteria: [criteria.FEMALE, criteria.SPANISH, criteria.RENAISSANCE, criteria.C_FOLK, criteria.SOFT, criteria.ODD_RHYTHM, criteria.C_JAZZ],
        selectedTrackTitle: null,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Donvi"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mia_en_vivo",
        title: "En Vivo",
        artist: "MIA",
        year: 1977,
        country: regions.ARGENTINA,
        criteria: [criteria.LIVE, criteria.SYMPHONIC, criteria.SPECTACULAR, criteria.FEMALE, criteria.SPANISH],
        selectedTrackTitle: "Lo Que Hay De Humano En Mí",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Donvi", "Kike Sanzol"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mia_cornonstipicum",
        title: "Cornonstipicum",
        artist: "MIA",
        year: 1978,
        country: regions.ARGENTINA,
        criteria: [criteria.SYMPHONIC, criteria.LENGTHY_TRACKS, criteria.FEMALE, criteria.C_PSYCHE, criteria.ODD_RHYTHM, criteria.C_FOLK],
        selectedTrackTitle: "Cornonstipicum",
        selectedTrackYtId: "W07m0jWv1oc",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "mia_conciertos",
        title: "Conciertos",
        artist: "MIA",
        year: 1979,
        country: regions.ARGENTINA,
        criteria: [criteria.LIVE, criteria.LENGTHY_TRACKS, criteria.FEMALE, criteria.BLENDS, criteria.SPANISH, criteria.RENAISSANCE],
        selectedTrackTitle: "Iridio Puro",
        selectedTrackYtId: "ohVayEHmCj8",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "michel_berger_puzzle",
        title: "Puzzle",
        artist: "Michel Berger",
        year: 1971,
        country: regions.FRANCE,
        criteria: [criteria.ORCHESTRAL_PARTS, criteria.SYMPHONIC, criteria.INSTRUMENTAL, criteria.ODD_RHYTHM, criteria.PIANO],
        selectedTrackTitle: `1er Mouvement`,
        selectedTrackYtId: "Wki01ktgthM",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "michel_berger_and_luc_plamondon_starmania",
        title: "Starmania",
        artist: "Michel Berger & Luc Plamondon",
        year: 1978,
        country: regions.FRANCE,
        criteria: [criteria.ROCK_OPERA, criteria.FEMALE, criteria.SOFT_SEVENTIES, criteria.TRANSITION, criteria.STORYLINE],
        selectedTrackTitle: `S.O.S. D'un Terrien En Détresse`,
        selectedTrackYtId: "slCipWPDdHw",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: ["andrew_lloyd_webber_and_tim_rice_jesus_christ_superstar", "johnny_hallyday_hamlet"],
        isAGem: false,
    },
    {
        id: "michel_fugain_un_enfant_dans_la_ville",
        title: "Un Enfant De La Ville",
        artist: "Michel Fugain",
        year: 1970,
        country: regions.FRANCE,
        criteria: [criteria.ROCK_OPERA, criteria.FEMALE, criteria.ORCHESTRAL_PARTS, criteria.FRENCH, criteria.FANFARE, criteria.SOUNDTRACK],
        selectedTrackTitle: `Des Fous, Des Bêtes`,
        selectedTrackYtId: "7gWWAKrD40Q",
        spotifyId: "6AdAWfz0FBRfBa4aR3VwTN",
        deezerId: "244256",
        designers: [],
        similarAlbums: ["andrew_lloyd_webber_and_tim_rice_jesus_christ_superstar"],
        isAGem: false,
    },
    {
        id: "michel_madore_le_komuso_a_cordes",
        title: "Le Komuso À Cordes",
        artist: "Michel Madore",
        year: 1976,
        country: regions.QUEBEC,
        criteria: [criteria.INSTRUMENTAL, criteria.C_PSYCHE, criteria.C_JAZZ, criteria.C_ELECTRO, criteria.SPACY, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Calligraphie",
        selectedTrackYtId: "MMnA_1jYPCU",
        spotifyId: null,
        deezerId: null,
        designers: ["Jacques Charbonneau"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "michel_madore_la_chambre_nuptiale",
        title: "La Chambre Nuptiale",
        artist: "Michel Madore",
        year: 1979,
        country: regions.QUEBEC,
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.AMBIENT, criteria.SOUND_COLLAGES, criteria.C_PSYCHE, criteria.ELECTRO, criteria.SOUNDTRACK],
        selectedTrackTitle: "Les Anges Qui Passent",
        selectedTrackYtId: "-XR_7DT0E-c",
        spotifyId: null,
        deezerId: null,
        designers: ["Francine Larivée"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "michel_polnareff_polnareffs",
        title: `Polnareff's`,
        artist: "Michel Polnareff",
        year: 1971,
        country: regions.FRANCE,
        criteria: [criteria.ART_POP, criteria.TRANSITION, criteria.FRENCH, criteria.ORCHESTRAL_PARTS, criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.FANFARE],
        selectedTrackTitle: `Computer's Dream`,
        selectedTrackYtId: "9kZndPjJAKo",
        spotifyId: "296OUPKaMjneCseFDKksHi",
        deezerId: "124264",
        designers: ["Georges Spitzer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mikael_ramel_till_dej",
        title: "Till Dej",
        artist: "Mikael Ramel",
        year: 1972,
        country: regions.SWEDEN,
        criteria: [criteria.SWEDISH, criteria.C_FOLK, criteria.ODD_RHYTHM, criteria.UNCOMMON_INSTRUMENTS, criteria.SOUND_COLLAGES, criteria.C_PSYCHE, criteria.FUNNY, criteria.JAM],
        selectedTrackTitle: "Artificiell Prana",
        selectedTrackYtId: "JiXtNthOOUM",
        spotifyId: "24ZHF2rzvO63ItEdERgtk7",
        deezerId: "123822",
        designers: ["Lorne De Wolfe", "Ted Ström", "Staffan Winbergh"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "mikael_ramel_extra_vagansa",
        title: "Extra Vagansa",
        artist: "Mikael Ramel",
        year: 1974,
        country: regions.SWEDEN,
        criteria: [criteria.SWEDISH, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.SOFT_SEVENTIES, criteria.FANFARE],
        selectedTrackTitle: "Apfigur",
        selectedTrackYtId: "w11v8orDe3E",
        spotifyId: "7xSz3WWEmCWX51ReVXyuMj",
        deezerId: "121960",
        designers: ["Lorne De Wolfe", "Mikael Ramel", "Staffan Winbergh"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mikael_ramel_3e_skivan",
        title: "3:e Skivan",
        artist: "Mikael Ramel",
        year: 1977,
        country: regions.SWEDEN,
        criteria: [criteria.SWEDISH, criteria.ODD_RHYTHM, criteria.FOLK, criteria.FEMALE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Fäbodrock",
        selectedTrackYtId: "NsLZD4IuuXY",
        spotifyId: "71BoZDB10EkvUKabSTsCes",
        deezerId: "79883072",
        designers: ["Rolf Scherrer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mike_oldfield_tubular_bells",
        title: "Tubular Bells",
        artist: "Mike Oldfield",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.ODD_RHYTHM, criteria.C_FOLK, criteria.SOFT, criteria.AMBIENT],
        selectedTrackTitle: "Tubular Bells (Part II)",
        selectedTrackYtId: "4pfzuFvFIeI",
        spotifyId: "0a3YQpBnRzJzNktOjb6Dum",
        deezerId: "10232416",
        designers: ["Trevor Key"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mike_oldfield_hergest_ridge",
        title: "Hergest Ridge",
        artist: "Mike Oldfield",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.C_ELECTRO, criteria.C_FOLK, criteria.FANFARE],
        selectedTrackTitle: "Hergest Ridge (Part I)",
        selectedTrackYtId: "DPQPYwWgxTY",
        spotifyId: "50PyBlT9PggDbi4Hauw9du",
        deezerId: "620753",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mike_oldfield_ommadawn",
        title: "Ommadawn",
        artist: "Mike Oldfield",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.C_ELECTRO, criteria.C_FOLK, criteria.FANFARE, criteria.SPIRITUAL],
        selectedTrackTitle: "Ommadawn (Part I)",
        selectedTrackYtId: "vShVl_Xd_Tc",
        spotifyId: "200p7O3raeXT2jNhmzK4TE",
        deezerId: "620607",
        designers: ["David Bailey"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mike_oldfield_incantations",
        title: "Incantations",
        artist: "Mike Oldfield",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.C_ELECTRO, criteria.C_FOLK, criteria.SPIRITUAL, criteria.FEMALE],
        selectedTrackTitle: "Incantations (Part I)",
        selectedTrackYtId: "todo",
        spotifyId: "0O6OgkgdNbYYLQj06FLFhf",
        deezerId: "1166175",
        designers: ["Trevor Key"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "mike_oldfield_platinum",
        title: "Platinum",
        artist: "Mike Oldfield",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.C_ELECTRO, criteria.C_FOLK, criteria.C_JAZZ, criteria.TRANSITION, criteria.ODD_RHYTHM, criteria.SOFT_SEVENTIES, criteria.FEMALE],
        selectedTrackTitle: "Platinum II: Platinum",
        selectedTrackYtId: "xqL9xxJexeY",
        spotifyId: "2o6JBxKf6RpoWRchz1Tst8",
        deezerId: "4009611",
        designers: ["Trevor Key"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mike_oldfield_qe2",
        title: "QE2",
        artist: "Mike Oldfield",
        year: 1980,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.C_ELECTRO, criteria.C_FOLK, criteria.FEMALE, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Mirage",
        selectedTrackYtId: "HRkfe2NabUo",
        spotifyId: "29mnCT1UKm7DduLNWdi842",
        deezerId: "4009601",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mike_oldfield_five_miles_out",
        title: "Five Miles Out",
        artist: "Mike Oldfield",
        year: 1982,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.NEO_EIGHTIES, criteria.C_ELECTRO, criteria.LENGTHY_TRACKS, criteria.FEMALE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Orabidoo",
        selectedTrackYtId: "0K28Km7PYuU",
        spotifyId: "1NqFhS3YNSTxowqOJ0TjOR",
        deezerId: "6874390",
        designers: ["Gerald Coulson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mike_oldfield_crises",
        title: "Crises",
        artist: "Mike Oldfield",
        year: 1983,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.NEO_EIGHTIES, criteria.LENGTHY_TRACKS, criteria.ODD_RHYTHM, criteria.FEMALE, criteria.C_ELECTRO],
        selectedTrackTitle: "Crises",
        selectedTrackYtId: "pJ_vgFF52w0",
        spotifyId: "56irNmW0iq9Flh41YbAv55",
        deezerId: "6874398",
        designers: ["Terry Ilott"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mike_oldfield_discovery",
        title: "Discovery",
        artist: "Mike Oldfield",
        year: 1984,
        country: regions.ENGLAND,
        criteria: [criteria.TRANSITION, criteria.NEO_EIGHTIES, criteria.FEMALE, criteria.TRANSITION, criteria.SYMPHONIC, criteria.ART_POP, criteria.C_ELECTRO],
        selectedTrackTitle: "The Lake",
        selectedTrackYtId: "44d0TF_XcFs",
        spotifyId: "6ipA0yGZ9puU2mu8oKIw8e",
        deezerId: "12279556",
        designers: ["Dan Kramer"],
        similarAlbums: ["kate_bush_never_for_ever"],
        isAGem: false,
    },
    {
        id: "mike_oldfield_islands",
        title: "Islands",
        artist: "Mike Oldfield",
        year: 1987,
        country: regions.ENGLAND,
        criteria: [criteria.SPECTACULAR, criteria.NEO_EIGHTIES, criteria.ELECTRO, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.FEMALE],
        selectedTrackTitle: "The Wind Chimes",
        selectedTrackYtId: "dzPW5WsPIo0",
        spotifyId: null,
        deezerId: null,
        designers: ["Icon"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miklagard_miklagard",
        title: "Miklagård",
        artist: "Miklagård",
        year: 1979,
        country: regions.SWEDEN,
        criteria: [criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.SWEDISH, criteria.C_ELECTRO],
        selectedTrackTitle: "Soldaten",
        selectedTrackYtId: "qcLbMdv1Ht0",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_in_a_silent_way",
        title: "In A Silent Way",
        artist: "Miles Davis",
        year: 1969,
        country: regions.USA,
        criteria: [criteria.LENGTHY_TRACKS, criteria.EXPERIMENTAL, criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.JAM, criteria.SOFT],
        selectedTrackTitle: `Shhh / Peaceful`,
        selectedTrackYtId: null,
        spotifyId: "0Hs3BomCdwIWRhgT57x22T",
        deezerId: "1210678",
        designers: ["Lee Friedlander"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_bitches_brew",
        title: "Bitches Brew",
        artist: "Miles Davis",
        year: 1970,
        country: regions.USA,
        criteria: [criteria.LENGTHY_TRACKS, criteria.EXPERIMENTAL, criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.JAM, criteria.SOPHISTICATED],
        selectedTrackTitle: `Pharaoh's Dance`,
        selectedTrackYtId: "d8QzACfFGlw",
        spotifyId: "3Q0zkOZEOC855ErOOJ1AdO",
        deezerId: "645702",
        designers: ["Mati Klarwein"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_jack_johnson",
        title: "Jack Johnson",
        artist: "Miles Davis",
        year: 1971,
        country: regions.USA,
        criteria: [criteria.LENGTHY_TRACKS, criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.SOUNDTRACK, criteria.JAM, criteria.JAZZY_GROOVY],
        selectedTrackTitle: `Yesternow`,
        selectedTrackYtId: "5c-iU0kQBro",
        spotifyId: "0xr31or2qYglJpiX6pODjY",
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_live_evil",
        title: "Live-Evil",
        artist: "Miles Davis",
        year: 1971,
        country: regions.USA,
        criteria: [criteria.LENGTHY_TRACKS, criteria.EXPERIMENTAL, criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.C_PSYCHE, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `Nem Um Talvez`,
        selectedTrackYtId: "TWs7cY-fEn0",
        spotifyId: "4eK5DQxLCshZCUk6D5a8Q1",
        deezerId: "1213267",
        designers: ["Mati Klarwein"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_on_the_corner",
        title: "On The Corner",
        artist: "Miles Davis",
        year: 1972,
        country: regions.USA,
        criteria: [criteria.LENGTHY_TRACKS, criteria.EXPERIMENTAL, criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.C_PSYCHE, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS, criteria.C_PSYCHE, criteria.TRANSITION],
        selectedTrackTitle: `Helen Butte`,
        selectedTrackYtId: null,
        spotifyId: "3lDkLLzW8arbO2OXCK1QTJ",
        deezerId: "1211445",
        designers: ["Corky McCoy"],
        similarAlbums: [], // TODO similar: hzrbie hancock sextant?
        isAGem: false,
    },
    {
        id: "miles_davis_agharta",
        title: "Agharta",
        artist: "Miles Davis",
        year: 1975,
        country: regions.USA,
        criteria: [criteria.LIVE, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.AFROBEAT, criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.C_PSYCHE, criteria.EXPERIMENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.INSTRUMENTAL],
        selectedTrackTitle: `Maiysha`,
        selectedTrackYtId: null,
        spotifyId: "7ACMLIVtCkZP7EzxzsZISW",
        deezerId: "112907",
        designers: ["Tadanori Yokoo"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_pangaea",
        title: "Pangaea",
        artist: "Miles Davis",
        year: 1976,
        country: regions.USA,
        criteria: [criteria.LIVE, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.AFROBEAT, criteria.C_JAZZ, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.SOFT],
        selectedTrackTitle: `Gondwana`,
        selectedTrackYtId: null,
        spotifyId: "0lYz13Pd1IYa7kZVoTUlN4",
        deezerId: "115608",
        designers: ["Teruhisa Tajima"],
        similarAlbums: [],
        isAGem: false, // TODO almost a gem
    },
    {
        id: "miles_davis_dark_magus",
        title: "Dark Magus",
        artist: "Miles Davis",
        year: 1977,
        country: regions.USA,
        criteria: [criteria.LIVE, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.AFROBEAT, criteria.C_JAZZ, criteria.C_PSYCHE, criteria.EXPERIMENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.INSTRUMENTAL],
        selectedTrackTitle: `Moja`,
        selectedTrackYtId: null,
        spotifyId: "0oNoEAy0RMBOqwRYtkhKRb",
        deezerId: "1211435",
        designers: ["Teruhisa Tajima"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_the_man_with_the_horn",
        title: "The Man With The Horn",
        artist: "Miles Davis",
        year: 1981,
        country: regions.USA,
        criteria: [criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.JAM, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: `Back Seat Betty`,
        selectedTrackYtId: "x3gnLVrBDUc",
        spotifyId: "1fRSDRiFk922cV3bgFCdtz",
        deezerId: "6919003",
        designers: ["Cindy Brown", "John Berg"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_star_people",
        title: "Star People",
        artist: "Miles Davis",
        year: 1983,
        country: regions.USA,
        criteria: [criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.C_ELECTRO, criteria.NEO_EIGHTIES],
        selectedTrackTitle: `Speak`,
        selectedTrackYtId: "acrzwF266L0",
        spotifyId: "2j4kRyY7kLm9NuciAHyzg5",
        deezerId: "7496447",
        designers: ["Janet Perr"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_decoy",
        title: "Decoy",
        artist: "Miles Davis",
        year: 1983,
        country: regions.USA,
        criteria: [criteria.C_JAZZ, criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.JAM],
        selectedTrackTitle: `Code M.D.`,
        selectedTrackYtId: "hH60cY1xoCk",
        spotifyId: "6TnYoLaDsyGqf987l4bLb1",
        deezerId: "1459749",
        designers: ["Gilles Larrain"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_youre_under_arrest",
        title: `You're Under Arrest`,
        artist: "Miles Davis",
        year: 1985,
        country: regions.USA,
        criteria: [criteria.C_JAZZ, criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.INSTRUMENTAL],
        selectedTrackTitle: `Katia`,
        selectedTrackYtId: "5piPBgYZffw",
        spotifyId: "5ITQ0X0gnSOo89AASdHV2o",
        deezerId: "121293",
        designers: ["Gilles Larrain"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "miles_davis_aura",
        title: `Aura`,
        artist: "Miles Davis",
        year: 1989,
        country: regions.USA,
        criteria: [criteria.JAZZ, criteria.C_PSYCHE, criteria.NEO_EIGHTIES, criteria.INSTRUMENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.AMBIENT],
        selectedTrackTitle: `Violet`,
        selectedTrackYtId: "QH9VYQufbfc",
        spotifyId: "3FxWza4JZVZHVjZ4jTQAav",
        deezerId: "1408167",
        designers: ["Gilles Larrain"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "minotaurus_fly_away",
        title: `Fly Away`,
        artist: "Minotaurus",
        year: 1978,
        country: regions.GERMANY,
        criteria: [criteria.C_ELECTRO, criteria.JAM, criteria.SOFT_SEVENTIES, criteria.SYMPHONIC],
        selectedTrackTitle: `Fly Away`,
        selectedTrackYtId: "YRvI6qc679w",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mirthrandir_for_you_the_old_women",
        title: `For You The Old Women`,
        artist: "Mirthrandir",
        year: 1976,
        country: regions.USA,
        criteria: [criteria.SYMPHONIC, criteria.FANFARE, criteria.ODD_RHYTHM, criteria.SPECTACULAR, criteria.C_ELECTRO, criteria.TECHNICAL, criteria.LENGTHY_TRACKS, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `For You The Old Women`,
        selectedTrackYtId: "1o3mNCf_kQY",
        spotifyId: null,
        deezerId: null,
        designers: ["Patrick Milbourn"],
        similarAlbums: ["emerson_lake_and_palmer_tarkus"],
        isAGem: false, // TODO almost
    },
    {
        id: "missing_link_nevergreen",
        title: `Nevergreen!`,
        artist: "Missing Link",
        year: 1972,
        country: regions.GERMANY,
        criteria: [criteria.UNCOMMON_INSTRUMENTS, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Sorcery`,
        selectedTrackYtId: "PB9exQV0ogQ",
        spotifyId: "5S0h2mawxtWodGYbqKlV7q",
        deezerId: "258653352",
        designers: ["Holger Brandt"],
        similarAlbums: ["titus_groan_titus_groan"],
        isAGem: false,
    },
    {
        id: "mona_lisa_lescapade",
        title: `L'escapade`,
        artist: "Mona Lisa",
        year: 1974,
        country: regions.FRANCE,
        criteria: [criteria.BAROQUE, criteria.SOUND_COLLAGES, criteria.FRENCH, criteria.RENAISSANCE, criteria.ROCK_OPERA, criteria.C_PSYCHE, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `Petit Homme De La Terre`,
        selectedTrackYtId: "4arCLteaWng",
        spotifyId: "6hwOdxRtj39XSIDY6219oi",
        deezerId: "431910",
        designers: ["Gérard Lecoeur"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "mona_lisa_grimaces",
        title: `Grimaces`,
        artist: "Mona Lisa",
        year: 1975,
        country: regions.FRANCE,
        criteria: [criteria.BAROQUE, criteria.FRENCH, criteria.RENAISSANCE, criteria.ROCK_OPERA, criteria.UNCOMMON_INSTRUMENTS, criteria.SYMPHONIC, criteria.C_ELECTRO],
        selectedTrackTitle: `Le Jardin Des Illusions`,
        selectedTrackYtId: "61fpJjdqrLE",
        spotifyId: "5aMbrbuWAraclVuKj5e0zC",
        deezerId: "505941",
        designers: ["François Fernandez"],
        similarAlbums: [], // similar ange
        isAGem: false,
    },
    {
        id: "mona_lisa_le_petit_violon_de_mr_gregoire",
        title: `Le Petit Violon De Mr. Grégoire`,
        artist: "Mona Lisa",
        year: 1976,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.RENAISSANCE, criteria.ROCK_OPERA, criteria.ODD_RHYTHM, criteria.C_ELECTRO],
        selectedTrackTitle: `Le Chant Des Glaces`,
        selectedTrackYtId: "uc920FSbGLc",
        spotifyId: "6nqQ9azhh4VRDM1KZnryQf",
        deezerId: "45640",
        designers: ["Philippe Huart"],
        similarAlbums: [], // similar ange
        isAGem: false,
    },
    {
        id: "mona_lisa_avant_quil_ne_soit_trop_tard",
        title: `Avant Qu'il Ne Soit Trop Tard`,
        artist: "Mona Lisa",
        year: 1977,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.SYMPHONIC, criteria.ROCK_OPERA, criteria.SPECTACULAR, criteria.ODD_RHYTHM, criteria.C_ELECTRO, criteria.TOUCHING_VOCALS],
        selectedTrackTitle: `Avant Qu'il Ne Soit Trop Tard`,
        selectedTrackYtId: "Uy-aiuk47K8",
        spotifyId: "0SQsxxWLDBCKg57NeOfb5k",
        deezerId: "45641",
        designers: ["Michel Lecoeur"],
        similarAlbums: [], // similar ange
        isAGem: false,
    },
    {
        id: "mona_lisa_vers_demain",
        title: `Vers Demain`,
        artist: "Mona Lisa",
        year: 1979,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.C_ELECTRO, criteria.ROCK_OPERA, criteria.SOUND_COLLAGES],
        selectedTrackTitle: `Maria`,
        selectedTrackYtId: "oVpzEuB9U_A",
        spotifyId: "0bzn0NMQZIcq7KvkDF3gnl",
        deezerId: "504710",
        designers: ["Bob Anton"],
        similarAlbums: [], // similar maneige 9pm?
        isAGem: false,
    },
    {
        id: "the_moody_blues_days_of_future_passed",
        title: "Days Of Future Passed",
        artist: "The Moody Blues",
        year: 1967,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.C_PSYCHE, criteria.ROCK_OPERA, criteria.CRISPY_SIXTIES],
        selectedTrackTitle: "Evening: The Sunset / Twilight Time",
        selectedTrackYtId: "C012iKu9s-8",
        spotifyId: "3ZS8uTlViMWAMM1q6lgPRu",
        deezerId: "224746",
        designers: ["David Anstey"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_moody_blues_in_search_of_the_lost_chord",
        title: "In Search Of The Lost Chord",
        artist: "The Moody Blues",
        year: 1968,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.C_PSYCHE, criteria.FOLK, criteria.TRANSITION, criteria.BAROQUE, criteria.ORIENTAL],
        selectedTrackTitle: "The Actor",
        selectedTrackYtId: "29ihZ_TbFqY",
        spotifyId: "0Rdx3jfi6h97W5VjQsuMOp",
        deezerId: "119073",
        designers: ["Phil Travers"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_moody_blues_on_the_threshold_of_a_dream",
        title: "On The Threshold Of A Dream",
        artist: "The Moody Blues",
        year: 1969,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.C_PSYCHE, criteria.FOLK, criteria.C_ELECTRO, criteria.SOUND_COLLAGES, criteria.TRANSITION],
        selectedTrackTitle: "Have You Heard (Part I)",
        selectedTrackYtId: "oCsKshg2BsY",
        spotifyId: "5QOVCdPUb8A6DhfpoAr7ta",
        deezerId: "160275",
        designers: ["Phil Travers"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_moody_blues_to_our_childrens_childrens_children",
        title: `To Our Children's Children's Children`,
        artist: "The Moody Blues",
        year: 1969,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.C_PSYCHE, criteria.FOLK, criteria.C_ELECTRO, criteria.SOUND_COLLAGES, criteria.TRANSITION, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Beyond",
        selectedTrackYtId: "Eem7AQmQdbE",
        spotifyId: "58MFBLIicSgR672qGeZc2q",
        deezerId: "125229",
        designers: ["Phil Travers"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_moody_blues_a_question_of_balance",
        title: `A Question Of Balance`,
        artist: "The Moody Blues",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.FOLK, criteria.ORCHESTRAL_PARTS, criteria.TRANSITION],
        selectedTrackTitle: `Don't You Feel Small`,
        selectedTrackYtId: "zjICZoqspv4",
        spotifyId: "1TOvW3icPZmigoT9CrRav5",
        deezerId: "119074",
        designers: ["Phil Travers"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_moody_blues_every_good_boy_deserves_favour",
        title: `Every Good Boy Deserves Favour`,
        artist: "The Moody Blues",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.SOUND_COLLAGES, criteria.C_PSYCHE, criteria.TRANSITION, criteria.BAROQUE, criteria.C_FOLK],
        selectedTrackTitle: "One More Time To Live",
        selectedTrackYtId: "nkRlGY35aU4",
        spotifyId: "0kmbfs4yxvWj8VXxg6y8H4",
        deezerId: "104944",
        designers: ["Phil Travers"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_moody_blues_seventh_sojourn",
        title: `Seventh Sojourn`,
        artist: "The Moody Blues",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.C_FOLK, criteria.SOFT, criteria.TRANSITION],
        selectedTrackTitle: "Lost In A Lost World",
        selectedTrackYtId: "80nUhHofw0U",
        spotifyId: "6wYmkzmLnW7vZwtuGCu3fy",
        deezerId: "245512",
        designers: ["Phil Travers"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_moody_blues_octave",
        title: `Octave`,
        artist: "The Moody Blues",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.BAROQUE, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: `Steppin' In A Slide Zone`,
        selectedTrackYtId: "RZXMeaZJJOY",
        spotifyId: "58Lnkf8TmX0GyxK45vfN1K",
        deezerId: "85822402",
        designers: [],
        similarAlbums: [], // TODO barclay james harvest
        isAGem: false,
    },
    {
        id: "the_moody_blues_long_distance_voyager",
        title: `Long Distance Voyager`,
        artist: "The Moody Blues",
        year: 1981,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.C_ELECTRO, criteria.BAROQUE],
        selectedTrackTitle: "Veteran Cosmic Rocker",
        selectedTrackYtId: "a6zoGo_jRCU",
        spotifyId: "4t5Za54Hk2E1vSxvtGoRSE",
        deezerId: "85836712",
        designers: ["Arts Union Glasgow", "Cream"],
        similarAlbums: ["electric_light_orchestra_time"],
        isAGem: false,
    },
    {
        id: "mor_stations",
        title: `Stations`,
        artist: "Mor",
        year: 1973,
        country: regions.FRANCE,
        criteria: [criteria.C_FOLK, criteria.FRENCH, criteria.SOFT, criteria.HUMBLE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "7h Du Soir",
        selectedTrackYtId: "PecTAGBx6cU",
        spotifyId: null,
        deezerId: null,
        designers: ["Georges Spitzer", "Yves Quentel"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "morgen_morgen",
        title: `Morgen`,
        artist: "Morgen",
        year: 1969,
        country: regions.USA,
        criteria: [criteria.CRISPY_SIXTIES, criteria.HEAVY, criteria.ROCK, criteria.JAM, criteria.C_PSYCHE, criteria.SPACY],
        selectedTrackTitle: "Of Dreams",
        selectedTrackYtId: "xfZArCES2hw",
        spotifyId: "7Lh2ZcU4QiVz8JupvKkhP4",
        deezerId: "6746861",
        designers: ["Edvard Munch", "Henry Epstein", "Steve Morgen", "William Shepard"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "move_move",
        title: `Move`,
        artist: "Move",
        year: 1968,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.C_PSYCHE, criteria.BAROQUE, criteria.FANFARE],
        selectedTrackTitle: "Fire Brigade",
        selectedTrackYtId: "E8ovyswna6U",
        spotifyId: null,
        deezerId: null,
        designers: ["The Fool"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "move_shazam",
        title: `Shazam`,
        artist: "Move",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.HEAVY, criteria.C_PSYCHE, criteria.BAROQUE, criteria.SOUND_COLLAGES, criteria.SYMPHONIC, criteria.C_FOLK],
        selectedTrackTitle: "Cherry Blossom Clinic (Revisited)",
        selectedTrackYtId: "MHAzNU4Vsus",
        spotifyId: null,
        deezerId: null,
        designers: ["Nickleby"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "move_looking_on",
        title: `Looking On`,
        artist: "Move",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.HEAVY, criteria.C_PSYCHE, criteria.GREASY_SEVENTIES, criteria.UNCOMMON_INSTRUMENTS, criteria.FANFARE, criteria.SPECTACULAR, criteria.SYMPHONIC, criteria.JAM],
        selectedTrackTitle: "What?",
        selectedTrackYtId: "Q3S-U6jJjD0",
        spotifyId: null,
        deezerId: null,
        designers: ["Graphreaks"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "move_message_from_the_country",
        title: `Message From The Country`,
        artist: "Move",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.GREASY_SEVENTIES, criteria.UNCOMMON_INSTRUMENTS, criteria.ROCK],
        selectedTrackTitle: "The Minister",
        selectedTrackYtId: "hWfO0lJ1mV8",
        spotifyId: null,
        deezerId: null,
        designers: ["Roy Wood"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "moving_gelatine_plates_moving_gelatine_plates",
        title: `Moving Gelatine Plates`,
        artist: "Moving Gelatine Plates",
        year: 1971,
        country: regions.FRANCE,
        criteria: [criteria.ODD_RHYTHM, criteria.C_JAZZ, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.LENGTHY_TRACKS, criteria.INSTRUMENTAL],
        selectedTrackTitle: "Gelatine",
        selectedTrackYtId: "J97dZAblVMA",
        spotifyId: null,
        deezerId: null,
        designers: ["Monique Poitrat"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "moving_gelatine_plates_the_world_of_genius_hans",
        title: `The World Of Genius Hans`,
        artist: "Moving Gelatine Plates",
        year: 1972,
        country: regions.FRANCE,
        criteria: [criteria.ODD_RHYTHM, criteria.C_JAZZ, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.LENGTHY_TRACKS, criteria.INSTRUMENTAL],
        selectedTrackTitle: "The World Of Genius Hans",
        selectedTrackYtId: "aXrE9AhdmZE",
        spotifyId: null,
        deezerId: null,
        designers: ["Henri Noblecourt"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "murray_head_nigel_lived",
        title: `Nigel Lived`,
        artist: "Murray Head",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.C_FOLK, criteria.SOUND_COLLAGES, criteria.JAZZY_GROOVY, criteria.SOFT, criteria.ORCHESTRAL_PARTS, criteria.C_PSYCHE],
        selectedTrackTitle: "Junk",
        selectedTrackYtId: "_q2bB1YC1d4",
        spotifyId: "2ZR6j7zPCID6qUeBrRAOhy",
        deezerId: "5983857",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "museo_rosenbach_zarathustra",
        title: "Zarathustra",
        artist: "Museo Rosenbach",
        year: 1973,
        country: regions.ITALY,
        criteria: [criteria.CONCEPT, criteria.TRANSITION, criteria.SYMPHONIC, criteria.SPECTACULAR, criteria.ITALIAN, criteria.TOUCHING_VOCALS, criteria.RENAISSANCE],
        selectedTrackTitle: `Zarathustra I: L'ultimo Uomo`,
        selectedTrackYtId: "uC9hegZIC2g",
        spotifyId: null,
        deezerId: null,
        designers: ["Wanda Spinello"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "ml_bongers_project_pacific_prison",
        title: "Pacific Prison",
        artist: "M.L. Bongers Project",
        year: 1978,
        country: regions.GERMANY,
        criteria: [criteria.STORYLINE, criteria.TRANSITION, criteria.SOUND_COLLAGES, criteria.C_ELECTRO, criteria.SCI_FI, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "A Deadly Smile",
        selectedTrackYtId: "px1CIxbSN0o",
        spotifyId: null,
        deezerId: null,
        designers: ["Michel Verdbois"],
        similarAlbums: [],
        isAGem: false,
    },
]

export default albums
