import { regions } from "../regions"
import { criteria } from "../criteria"

/**
 * @type {Array.<import(".").Album>}
 */
const albums = [
    {
        id: "r_m_tocak_r_m_tocak",
        title: "R. M. Točak",
        artist: "R. M. Točak",
        year: 1977,
        country: regions.SERBIA,
        criteria: [criteria.ODD_RHYTHM, criteria.INSTRUMENTAL, criteria.JAM, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Oro",
        selectedTrackYtId: "Hn96aaTyJRA",
        spotifyId: null,
        deezerId: null,
        designers: ["Rade Mudrinić"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rainbow_rainbow",
        title: "Rainbow",
        artist: "Rainbow",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.JAM, criteria.ROCK, criteria.HEAVY, criteria.FANTASY],
        selectedTrackTitle: "Catch The Rainbow",
        selectedTrackYtId: "p3VgV31vmUE",
        spotifyId: "3LXOrVXLXwRiOguE446OZo",
        deezerId: "162197",
        designers: ["David Willardson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rainbow_rising",
        title: "Rising",
        artist: "Rainbow",
        year: 1976,
        country: regions.ENGLAND,
        criteria: [criteria.JAM, criteria.ROCK, criteria.SPECTACULAR, criteria.HEAVY, criteria.FANTASY, criteria.ARENA],
        selectedTrackTitle: "Stargazer",
        selectedTrackYtId: "rVXy1OhaERY",
        spotifyId: "3uIT4I4Dy7Pq1j0aSjzPW9",
        deezerId: "124376",
        designers: ["Ken Kelly"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rainbow_long_live_rock_n_roll",
        title: `Long Live Rock 'N' Roll`,
        artist: "Rainbow",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.JAM, criteria.ROCK, criteria.SPECTACULAR, criteria.HEAVY, criteria.FANTASY, criteria.ARENA],
        selectedTrackTitle: "Gates Of Babylon",
        selectedTrackYtId: "MHCdCbTxypU",
        spotifyId: "56JX1fNOjTa7Bj7G18nxSq",
        deezerId: "6058392",
        designers: ["Debbie Hall", "Maxi Chan"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralf_nowy_lucifers_dream",
        title: `Lucifer's Dream`,
        artist: "Ralf Nowy",
        year: 1973,
        country: regions.GERMANY,
        criteria: [criteria.UNCOMMON_INSTRUMENTS, criteria.C_PSYCHE, criteria.INSTRUMENTAL, criteria.ORCHESTRAL_PARTS, criteria.JAZZY_GROOVY, criteria.ORIENTAL],
        selectedTrackTitle: "Breadhead",
        selectedTrackYtId: "M1NPLoAXlRY",
        spotifyId: "5svUx39Ii3WDQ7JwGCeB0l",
        deezerId: "392109",
        designers: ["Albert Leuthenmayr"],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO Ralf Nowy - Escalation introuvable
    // null + null
    // TODO Ralf Nowy - Nowy 2 introuvable
    // null + null
    {
        id: "ralph_lundsten_erik_xiv_och_ristningar",
        title: "Erik XIV Och Ristningar",
        artist: "Ralph Lundsten",
        year: 1969,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.C_PSYCHE, criteria.AMBIENT],
        selectedTrackTitle: "Manteldans",
        selectedTrackYtId: "wBQTKxn14ls",
        spotifyId: null,
        deezerId: null,
        designers: ["Hans Arnold"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_olskog",
        title: "Ölskog",
        artist: "Ralph Lundsten",
        year: 1970,
        country: regions.SWEDEN,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.C_PSYCHE, criteria.AMBIENT, criteria.LENGTHY_TRACKS, criteria.SWEDISH],
        selectedTrackTitle: "Through A Landscape Of Mirrors",
        selectedTrackYtId: "rNjAgLprkdQ",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_gustav_iii_nattmara",
        title: "Gustav III / Nattmara",
        artist: "Ralph Lundsten",
        year: 1971,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.AMBIENT, criteria.UNCOMMON_INSTRUMENTS, criteria.MEDIEVAL, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: "Nattmara",
        selectedTrackYtId: "JVu9LPd9i84",
        spotifyId: null,
        deezerId: null,
        designers: ["Hans Arnold"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_fadervar",
        title: "Fadervår",
        artist: "Ralph Lundsten",
        year: 1972,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.SOUND_COLLAGES, criteria.AMBIENT, criteria.SPIRITUAL, criteria.FEMALE],
        selectedTrackTitle: "Anrop - Fader Vår Som Är I Himmelen",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Gustave Doré"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_stromkarlen",
        title: "Strömkarlen",
        artist: "Ralph Lundsten",
        year: 1973,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.SOUND_COLLAGES, criteria.AMBIENT, criteria.C_PSYCHE, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "I Landet Längesen",
        selectedTrackYtId: "JJqojzNXjaA",
        spotifyId: null,
        deezerId: null,
        designers: ["Hans Arnold"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_skrack_och_skratt_resor_i_okanda_varldar",
        title: "Skräck Och Skratt, Resor I Okända Världar",
        artist: "Ralph Lundsten",
        year: 1973,
        country: regions.SWEDEN,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.C_PSYCHE],
        selectedTrackTitle: "Midnattstimmen I: Gengångarnatt",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_svit_for_elektroniskt_dragspel_gunnar_pa_lidarande",
        title: "Svit För Elektroniskt Dragspel / Gunnar På Lidarände",
        artist: "Ralph Lundsten",
        year: 1973,
        country: regions.SWEDEN,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.C_PSYCHE, criteria.SOUND_COLLAGES],
        selectedTrackTitle: "Svit För Elektroniskt Dragspel II: Pastoral",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_shangri_la",
        title: "Shangri-La",
        artist: "Ralph Lundsten",
        year: 1975,
        country: regions.SWEDEN,
        criteria: [criteria.INSTRUMENTAL, criteria.TRANSITION, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: "Shangri-La",
        selectedTrackYtId: "Gg0dopo1q4U",
        spotifyId: null,
        deezerId: null,
        designers: ["Hans Arnold"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_johannes_och_huldran",
        title: "Johannes Och Huldran",
        artist: "Ralph Lundsten",
        year: 1975,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: "Skogen Vaknar",
        selectedTrackYtId: "VGc6e62ldEo",
        spotifyId: null,
        deezerId: null,
        designers: ["Inger Edelfeldt"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_ralph_lundstens_universe",
        title: `Ralph Lundsten's Universe`,
        artist: "Ralph Lundsten",
        year: 1976,
        country: regions.SWEDEN,
        criteria: [criteria.INSTRUMENTAL, criteria.TRANSITION, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO, criteria.SCI_FI, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "The Blue Planet",
        selectedTrackYtId: "nc207RhZQDQ",
        spotifyId: "3PEQcKyh9TvtBxdDLhs92R",
        deezerId: null,
        designers: ["Tim White"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_discophrenia",
        title: "Discophrenia",
        artist: "Ralph Lundsten",
        year: 1978,
        country: regions.SWEDEN,
        criteria: [criteria.INSTRUMENTAL, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.ELECTRO, criteria.SCI_FI, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Discophrenia",
        selectedTrackYtId: "wgWUJBJ4Tt8",
        spotifyId: null,
        deezerId: null,
        designers: ["Birgitta Hartzell-Wittgenstein"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_alpha_ralpha_boulevard",
        title: "Alpha Ralpha Boulevard",
        artist: "Ralph Lundsten",
        year: 1979,
        country: regions.SWEDEN,
        criteria: [criteria.INSTRUMENTAL, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO, criteria.SCI_FI, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Alpha Ralpha Boulevard",
        selectedTrackYtId: "uKL5tj0FHDk",
        spotifyId: null,
        deezerId: null,
        designers: ["William Feilding"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_paradissymfonin",
        title: "Paradissymfonin",
        artist: "Ralph Lundsten",
        year: 1980,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.SOFT, criteria.AMBIENT, criteria.ELECTRO, criteria.NEO_EIGHTIES, criteria.SPIRITUAL, criteria.FEMALE, criteria.UNCOMMON_INSTRUMENTS, criteria.ORCHESTRAL_PARTS],
        selectedTrackTitle: "Himmelens Port",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Gustave Doré"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_en_midvinter_saga",
        title: "En Midvintersaga",
        artist: "Ralph Lundsten",
        year: 1981,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.SOFT, criteria.AMBIENT, criteria.ELECTRO, criteria.NEO_EIGHTIES, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: "Vintersymfoni",
        selectedTrackYtId: "s7Y8u-ERFFw",
        spotifyId: null,
        deezerId: null,
        designers: ["Jenny Nyström"],
        similarAlbums: ["jean_michel_jarre_les_chants_magnetiques"],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_the_new_age",
        title: "The New Age",
        artist: "Ralph Lundsten",
        year: 1982,
        country: regions.SWEDEN,
        criteria: [criteria.INSTRUMENTAL, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.ELECTRO, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Time Storm",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Ulf Hinders"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_pop_age_en_sommersaga",
        title: "Pop Age / En Sommersaga",
        artist: "Ralph Lundsten",
        year: 1983,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.SOUND_COLLAGES, criteria.INSTRUMENTAL, criteria.ELECTRO, criteria.C_PSYCHE, criteria.AMBIENT, criteria.NEO_EIGHTIES, criteria.ORCHESTRAL_PARTS],
        selectedTrackTitle: "Sommarlängtan",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Hans Arnold"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_trolltagen_dreamscape",
        title: "Trolltagen / Dreamscape",
        artist: "Ralph Lundsten",
        year: 1984,
        country: regions.SWEDEN,
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.ELECTRO, criteria.AMBIENT, criteria.NEO_EIGHTIES, criteria.C_PSYCHE],
        selectedTrackTitle: "Vallsommar",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Ulf Hinders", "John Bauer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_valkommen",
        title: "Välkommen",
        artist: "Ralph Lundsten",
        year: 1985,
        country: regions.SWEDEN,
        criteria: [criteria.INSTRUMENTAL, criteria.ELECTRO, criteria.AMBIENT, criteria.NEO_EIGHTIES, criteria.C_FOLK],
        selectedTrackTitle: "Jungfrugrottan",
        selectedTrackYtId: "WKSVVmKdpG8",
        spotifyId: null,
        deezerId: null,
        designers: ["Ulf Hinders", "John Bauer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ralph_lundsten_the_dream_master",
        title: "The Dream Master",
        artist: "Ralph Lundsten",
        year: 1986,
        country: regions.SWEDEN,
        criteria: [criteria.INSTRUMENTAL, criteria.ELECTRO, criteria.AMBIENT, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Suite Amoroso III: Divineness",
        selectedTrackYtId: "SF-4bzEBRTc",
        spotifyId: null,
        deezerId: null,
        designers: ["Hans Arnold"],
        similarAlbums: ["jean_michel_jarre_rendez_vous", "ozric_tentacles_pungent_effulgent"],
        isAGem: false,
    },
    {
        id: "ramases_space_hymns",
        title: "Space Hymns",
        artist: "Ramses",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.C_FOLK, criteria.C_PSYCHE, criteria.ART_POP, criteria.FEMALE],
        selectedTrackTitle: "Earth People",
        selectedTrackYtId: "wj1ijRZvPX4",
        spotifyId: null,
        deezerId: null,
        designers: ["Roger Dean"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ramases_glass_top_coffin",
        title: "Glass Top Coffin",
        artist: "Ramses",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.C_FOLK, criteria.C_PSYCHE, criteria.ART_POP, criteria.ORCHESTRAL_PARTS, criteria.FEMALE],
        selectedTrackTitle: "Stepping Stones",
        selectedTrackYtId: "RDQCDViuubQ",
        spotifyId: null,
        deezerId: null,
        designers: ["Dave Field"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ramses_la_leyla",
        title: "La Leyla",
        artist: "Ramses",
        year: 1976,
        country: regions.GERMANY,
        criteria: [criteria.SOFT, criteria.C_ELECTRO, criteria.HUMBLE, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "La Leyla",
        selectedTrackYtId: "FmiSuG7PuVs",
        spotifyId: null,
        deezerId: null,
        designers: ["Helga Bartkowiak"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ramses_eternity_rise",
        title: "Eternity Rise",
        artist: "Ramses",
        year: 1978,
        country: regions.GERMANY,
        criteria: [criteria.SOFT, criteria.C_ELECTRO, criteria.HUMBLE, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "Only Yesterday",
        selectedTrackYtId: "KYfxukQkw10",
        spotifyId: null,
        deezerId: null,
        designers: ["Helga Bartkowiak"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ramses_light_fantastic",
        title: "Light Fantastic",
        artist: "Ramses",
        year: 1981,
        country: regions.GERMANY,
        criteria: [criteria.SOFT, criteria.C_ELECTRO, criteria.HUMBLE, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "Across The Everglades",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Helga Bartkowiak", "Norbert Leidecker"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ray_owens_moon_moon",
        title: "Moon",
        artist: `Ray Owen's Moon`,
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.C_ELECTRO, criteria.ROCK, criteria.HEAVY],
        selectedTrackTitle: "Talk To Me",
        selectedTrackYtId: "S8yPhGvgqBo",
        spotifyId: null,
        deezerId: null,
        designers: ["Lance", "Hamish & Gustav"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "raymond_vincent_metronomics",
        title: "Metronomics",
        artist: "Raymond Vincent",
        year: 1973,
        country: regions.BELGIUM,
        criteria: [criteria.INSTRUMENTAL, criteria.C_FOLK, criteria.PATCHWORK],
        selectedTrackTitle: "La Mouette",
        selectedTrackYtId: "5g1Ppivoqu0",
        spotifyId: null,
        deezerId: null,
        designers: ["Josse Goffin"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rayuela_rayuela",
        title: "Rayuela",
        artist: "Rayuela",
        year: 1977,
        country: regions.ARGENTINA,
        criteria: [criteria.SPANISH, criteria.C_FOLK, criteria.ODD_RHYTHM, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS, criteria.SYMPHONIC],
        selectedTrackTitle: "Acaso Tú Crees",
        selectedTrackYtId: "xvFAdSlMJlA",
        spotifyId: "6Mf2B18iryfL3SSSRnQyZX",
        deezerId: "12994476",
        designers: ["Mauricio Tarrab", "Leopoldo Loustou"],
        similarAlbums: ["busqueda_busqueda"],
        isAGem: false, // TODO almost
    },
    {
        id: "recreation_dont_open",
        title: `Don't Open`,
        artist: "Recreation",
        year: 1970,
        country: regions.BELGIUM,
        criteria: [criteria.GREASY_SEVENTIES, criteria.JAM, criteria.INSTRUMENTAL, criteria.BAROQUE, criteria.TRANSITION, criteria.SOUND_COLLAGES],
        selectedTrackTitle: `Running For Life`,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Helmut Wenske"],
        similarAlbums: [], // TODO similardébut de beggar's opera
        isAGem: false,
    },
    {
        id: "recreation_music_or_not_music",
        title: "Music Or Not Music",
        artist: "Recreation",
        year: 1972,
        country: regions.BELGIUM,
        criteria: [criteria.GREASY_SEVENTIES, criteria.C_PSYCHE, criteria.JAM, criteria.FUNNY, criteria.PATCHWORK, criteria.TRANSITION, criteria.SOUND_COLLAGES, criteria.INSTRUMENTAL],
        selectedTrackTitle: `My Grandmother Likes Andy Williams, Too`,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Nicole Claveloux"],
        similarAlbums: [], // TODO similar aporhidte child 666 + début de beggar's opera
        isAGem: true,
        description: `TODO description`, // Assez fou, enchainement de scaynettes musicales sans sens apparent, mais juste du délire par ci par là
    },
    {
        id: "red_noise_sarcelle_locheres",
        title: "Sarcelles-Lochères",
        artist: "Red Noise",
        year: 1971,
        country: regions.FRANCE,
        criteria: [criteria.PATCHWORK, criteria.LENGTHY_TRACKS, criteria.SOUND_COLLAGES, criteria.C_PSYCHE, criteria.FUNNY, criteria.FRENCH, criteria.EXPERIMENTAL, criteria.TRANSITION],
        selectedTrackTitle: "Caka Slow / Vertebrate Twist",
        selectedTrackYtId: "Wh-itFLMyQA",
        spotifyId: "2Zfkl2tAc8agaz7tuXJqua",
        deezerId: "76148162",
        designers: ["Patrick Vian", "H. Van der Meer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "renaissance_renaissance",
        title: "Renaissance",
        artist: "Renaissance",
        year: 1969,
        country: regions.ENGLAND,
        criteria: [criteria.LENGTHY_TRACKS, criteria.PIANO, criteria.FEMALE, criteria.SYMPHONIC, criteria.BAROQUE, criteria.C_PSYCHE],
        selectedTrackTitle: "Kings And Queens",
        selectedTrackYtId: "zrkk6nCDIgQ",
        spotifyId: "7q83UUrA1wQFE3Ie8eASQf",
        deezerId: "13155452",
        designers: ["Claude Génisson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "renaissance_illusion",
        title: "Illusion",
        artist: "Renaissance",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.LENGTHY_TRACKS, criteria.PIANO, criteria.FEMALE, criteria.SYMPHONIC, criteria.BAROQUE, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Past Orbits Of Dust",
        selectedTrackYtId: "ttYpwsNP-Ko",
        spotifyId: "73X5R1QE5mWhPpzoJyFfvs",
        deezerId: "11341312",
        designers: ["Paul Whitehead"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "renaissance_prologue",
        title: "Prologue",
        artist: "Renaissance",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.FEMALE, criteria.SYMPHONIC, criteria.BAROQUE, criteria.SOUND_COLLAGES],
        selectedTrackTitle: "Kiev",
        selectedTrackYtId: "9_aFVlIcyFg",
        spotifyId: "4sIXQwVVGsvXcRDhrlHP0X",
        deezerId: "425198",
        designers: ["Hipgnosis", "Ronchetti & Day"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "renaissance_ashes_are_burning",
        title: "Ashes Are Burning",
        artist: "Renaissance",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.FEMALE, criteria.SYMPHONIC, criteria.BAROQUE, criteria.ORCHESTRAL_PARTS, criteria.C_FOLK, criteria.GLITTER],
        selectedTrackTitle: "Ashes Are Burning",
        selectedTrackYtId: "hZecf4CVCgw",
        spotifyId: "1C2fgiQmiTF9Dr8NdbPSou",
        deezerId: "425197",
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "renaissance_turn_of_the_cards",
        title: "Turn Of The Cards",
        artist: "Renaissance",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.FEMALE, criteria.SYMPHONIC, criteria.BAROQUE, criteria.ORCHESTRAL_PARTS, criteria.SPECTACULAR],
        selectedTrackTitle: "Mother Russia",
        selectedTrackYtId: "A1BpLYGdWcY",
        spotifyId: "2mmafFQ8DFTVcoVMWNwv05",
        deezerId: "2749991",
        designers: ["Hipgnosis", "Joe Petagno"],
        similarAlbums: [],
        isAGem: false, // TODO?
    },
    {
        id: "renaissance_scheherazade_and_other_stories",
        title: "Scheherazade And Other Stories",
        artist: "Renaissance",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.FEMALE, criteria.SYMPHONIC, criteria.UNCOMMON_INSTRUMENTS, criteria.LENGTHY_TRACKS, criteria.ORCHESTRAL_PARTS, criteria.SPECTACULAR],
        selectedTrackTitle: "Song Of Scheherazade",
        selectedTrackYtId: "6dH5y0BUXZ4",
        spotifyId: "1D0uoLl9Uf7bfBQjJfmlHc",
        deezerId: "2744051",
        designers: ["Hipgnosis", "Colin Elgie"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "renaissance_novella",
        title: "Novella",
        artist: "Renaissance",
        year: 1977,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.FEMALE, criteria.SYMPHONIC, criteria.LENGTHY_TRACKS, criteria.ORCHESTRAL_PARTS, criteria.BAROQUE, criteria.SPECTACULAR],
        selectedTrackTitle: "Touching Once (Is So Hard To Keep)",
        selectedTrackYtId: "Kl2ciFt6OWY",
        spotifyId: "6xEfCIaJl4l82Daok0SgA6",
        deezerId: "52582962",
        designers: ["Pamela Brown"],
        similarAlbums: [],
        isAGem: false, // TODO ?
    },
    {
        id: "renaissance_a_song_for_all_seasons",
        title: "A Song For All Seasons",
        artist: "Renaissance",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.FEMALE, criteria.SYMPHONIC, criteria.ORCHESTRAL_PARTS, criteria.UNCOMMON_INSTRUMENTS, criteria.ODD_RHYTHM, criteria.SPECTACULAR],
        selectedTrackTitle: "The Day Of The Dreamer",
        selectedTrackYtId: "eBELR6Y5oFc",
        spotifyId: "5nsCt8ifWdDINlQrL4nQlB",
        deezerId: "52582912",
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "renaissance_azure_dor",
        title: "Azure D'or",
        artist: "Renaissance",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.FEMALE, criteria.C_ELECTRO, criteria.SYMPHONIC, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "The Discovery",
        selectedTrackYtId: "IbVyVKm08Cc",
        spotifyId: "5pAWagPaGpn9XbuDQAlAlw",
        deezerId: "52582932",
        designers: ["Richard Gray"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "renaissance_camera_camera",
        title: "Camera Camera",
        artist: "Renaissance",
        year: 1981,
        country: regions.ENGLAND,
        criteria: [criteria.FEMALE, criteria.C_ELECTRO, criteria.SYMPHONIC, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Jigswaw",
        selectedTrackYtId: "8wAcPjQMn0Q",
        spotifyId: "6VOtlxfcXgukRqfqmVzXXH",
        deezerId: "279484882",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "renaissance_time_line",
        title: "Time-Line",
        artist: "Renaissance",
        year: 1983,
        country: regions.ENGLAND,
        criteria: [criteria.FEMALE, criteria.C_ELECTRO, criteria.SYMPHONIC, criteria.NEO_EIGHTIES, criteria.ROCK, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Flight",
        selectedTrackYtId: "5H_lLDZ9c-I",
        spotifyId: "4GtMwEZj1Tq5xDkVQzKA49",
        deezerId: "274637172",
        designers: ["Graham Humphreys", "Brian Aris"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "return_to_forever_return_to_forever",
        title: "Return To Forever",
        artist: "Return To Forever",
        year: 1972,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.INSTRUMENTAL, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Crystal Silence",
        selectedTrackYtId: "69rjdr7SR0Q",
        spotifyId: "6M0IAJHwQ6dFNtTkFsXCJc",
        deezerId: "124358",
        designers: ["Michael Manoogian"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "return_to_forever_light_as_a_feather",
        title: "Light As A Feather",
        artist: "Return To Forever",
        year: 1972,
        country: regions.USA,
        criteria: [criteria.JAM, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Spain",
        selectedTrackYtId: "a_OEJ0wqt2g",
        spotifyId: "2wkmxijYToqAr0ATgcNSsn",
        deezerId: "239959",
        designers: ["Hamish Grimes"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "return_to_forever_hymn_of_the_seventh_galaxy",
        title: "Hymn Of The Seventh Galaxy",
        artist: "Return To Forever",
        year: 1973,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "After The Cosmic Rain",
        selectedTrackYtId: "MWPo6oqHvJ8",
        spotifyId: "0ddNu3IWO5iEHoBe9qOr5L",
        deezerId: "230734",
        designers: ["Don Brautigan", "Neville Potter"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "return_to_forever_where_have_i_known_you_before",
        title: "Where Have I Known You Before",
        artist: "Return To Forever",
        year: 1974,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Song To The Pharoah Kings",
        selectedTrackYtId: "q-XDtjCwS9Q",
        spotifyId: "1LAARZVfnq12x7Ueei4jx7",
        deezerId: "248142",
        designers: ["Petra Kinkele", "Neville Potter", "Herb Deiwitz"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "return_to_forever_no_mystery",
        title: "No Mystery",
        artist: "Return To Forever",
        year: 1975,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Celebration Suite (Part I)",
        selectedTrackYtId: "LBawRSufDlU",
        spotifyId: "0OjgANiCv3GFQWq1B8No1j",
        deezerId: null,
        designers: ["Petra Kinkele", "Bill Levy", "Neville Potter"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "return_to_forever_romantic_warrior",
        title: "Romantic Warrior",
        artist: "Return To Forever",
        year: 1976,
        country: regions.USA,
        criteria: [criteria.CONCEPT, criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.JAZZ, criteria.JAZZY_GROOVY, criteria.MEDIEVAL],
        selectedTrackTitle: "Duel Of The Jester And The Tyrant",
        selectedTrackYtId: "sa21WPH4_U4",
        spotifyId: "1R2UR5wAs50dpbHkhUtLH7",
        deezerId: "6750057",
        designers: ["Wilson McLean"],
        similarAlbums: ["chick_corea_the_leprechaun"],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "return_to_forever_musicmagic",
        title: "Musicmagic",
        artist: "Return To Forever",
        year: 1977,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZ, criteria.JAZZY_GROOVY, criteria.SOFT_SEVENTIES, criteria.FEMALE],
        selectedTrackTitle: "The Endless Night",
        selectedTrackYtId: "STXJFzaAj0U",
        spotifyId: "0dmDVVzPAjPHmAND1gq8LY",
        deezerId: "114702",
        designers: ["Catherine Loeb"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "la_revolution_francaise_la_revolution_francaise",
        title: "La Révolution Française",
        artist: "La Révolution Française",
        year: 1973,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.ODD_RHYTHM, criteria.SPECTACULAR, criteria.ROCK_OPERA, criteria.PATCHWORK, criteria.STORYLINE, criteria.ORCHESTRAL_PARTS, criteria.TRANSITION, criteria.FANFARE, criteria.FEMALE],
        selectedTrackTitle: "Le Procès De Louis XVI : Réquisitoire / Exécution",
        selectedTrackYtId: "o97Xff6ReYw",
        spotifyId: "6K6SzeA8aDcF4eib3uH1A9",
        deezerId: "3890411",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "richard_wright_wet_dream",
        title: "Wet Dream",
        artist: "Richard Wright",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT_SEVENTIES, criteria.JAM, criteria.PIANO, criteria.ART_POP, criteria.C_ELECTRO],
        selectedTrackTitle: "Waves",
        selectedTrackYtId: "h5ESm72E4t0",
        spotifyId: null,
        deezerId: null,
        designers: ["Hipgnosis"],
        similarAlbums: ["supertramp_even_in_the_quietest_moments"],
        isAGem: false,
    },
    {
        id: "rick_wakeman_the_six_wives_of_henry_viii",
        title: "The Six Wives Of Henry VIII",
        artist: "Rick Wakeman",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.INSTRUMENTAL, criteria.CONCEPT, criteria.C_ELECTRO, criteria.FEMALE, criteria.SYMPHONIC, criteria.PIANO, criteria.SPECTACULAR, criteria.ODD_RHYTHM, criteria.JAM, criteria.TECHNICAL, criteria.MEDIEVAL],
        selectedTrackTitle: "Catherine Of Aragon",
        selectedTrackYtId: "aDuBhDzjYyI",
        spotifyId: "7KqisP47OG3PCtbLknLJPT",
        deezerId: "9640566",
        designers: [],
        similarAlbums: [],
        isAGem: false, // TODO almost
    },
    {
        id: "rick_wakeman_journey_to_the_centre_of_the_earth",
        title: "Journey To The Centre Of The Earth",
        artist: "Rick Wakeman",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.LIVE, criteria.LENGTHY_TRACKS, criteria.CONCEPT, criteria.C_ELECTRO, criteria.FEMALE, criteria.SYMPHONIC, criteria.PIANO, criteria.SPECTACULAR, criteria.ORCHESTRAL_PARTS, criteria.TECHNICAL, criteria.UNCOMMON_INSTRUMENTS, criteria.STORYLINE, criteria.ROCK_OPERA, criteria.JAM, criteria.FANTASY],
        selectedTrackTitle: "The Battle",
        selectedTrackYtId: "D6afHlAJRhk",
        spotifyId: "4GeRzDetT2K0322NomtKkj",
        deezerId: "231934",
        designers: [],
        similarAlbums: ["Michael Wade", "Mike Doud"],
        isAGem: false,
    },
    {
        id: "rick_wakeman_the_myths_and_legends_of_king_arthur_and_the_knights_of_the_round_table",
        title: "The Myths And Legends Of King Arthur And The Knights Of The Round Table",
        artist: "Rick Wakeman",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.MEDIEVAL, criteria.CONCEPT, criteria.BLENDS, criteria.SYMPHONIC, criteria.PIANO, criteria.SPECTACULAR, criteria.ORCHESTRAL_PARTS, criteria.TECHNICAL, criteria.UNCOMMON_INSTRUMENTS, criteria.JAM, criteria.ROCK_OPERA, criteria.FANFARE, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Guinevere",
        selectedTrackYtId: "p0YjXZprzKM",
        spotifyId: "0ALQd0pjofVj8QQecUnP6l",
        deezerId: "9640570",
        designers: [],
        similarAlbums: ["Mike Doud", "Geoff Halpin", "Chris Moore"],
        isAGem: false,
    },
    {
        id: "rick_wakeman_no_earthly_connection",
        title: "No Earthly Connection",
        artist: "Rick Wakeman",
        year: 1976,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.C_ELECTRO, criteria.SYMPHONIC, criteria.ODD_RHYTHM, criteria.SPECTACULAR, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: "Music Reincarnate",
        selectedTrackYtId: "7M74FijmFy8",
        spotifyId: "7Kw6q6WZhz0BC7SJN99PLB",
        deezerId: "14780667",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rick_wakeman_rick_wakemans_criminal_record",
        title: `Rick Wakeman's Criminal Record`,
        artist: "Rick Wakeman",
        year: 1977,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.C_ELECTRO, criteria.SYMPHONIC, criteria.ODD_RHYTHM, criteria.SPECTACULAR, criteria.LENGTHY_TRACKS, criteria.FUNNY, criteria.INSTRUMENTAL],
        selectedTrackTitle: "Statue Of Justice",
        selectedTrackYtId: "Qs8ZCTawzuo",
        spotifyId: "049g2vTXTkorBp4ncKsn8C",
        deezerId: "118876",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rick_wakeman_rhapsodies",
        title: `Rhapsodies`,
        artist: "Rick Wakeman",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.C_ELECTRO, criteria.ODD_RHYTHM, criteria.FUNNY, criteria.INSTRUMENTAL],
        selectedTrackTitle: "Pedra Da Gavea",
        selectedTrackYtId: "0Xh7a5psiwA",
        spotifyId: "1BPJzSu8TBskqIFEuP8AsA",
        deezerId: "11603336",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rick_wakeman_1984",
        title: `1984`,
        artist: "Rick Wakeman",
        year: 1981,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.C_ELECTRO, criteria.FEMALE, criteria.ROCK_OPERA, criteria.FANFARE],
        selectedTrackTitle: "The Hymn",
        selectedTrackYtId: "aUXLWiBO5JM",
        spotifyId: "4cC2z63HedG20N5332wvIZ",
        deezerId: "6023702",
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rick_wakeman_and_mario_fasciano_black_knights_at_the_court_of_ferdinand_iv",
        title: `Black Knights At The Court Of Ferdinand IV`,
        artist: "Rick Wakeman & Mario Fasciano",
        year: 1988,
        country: regions.ITALY,
        criteria: [criteria.CONCEPT, criteria.ELECTRO, criteria.ITALIAN, criteria.ROCK_OPERA, criteria.NEO_EIGHTIES, criteria.SYMPHONIC],
        selectedTrackTitle: "Favola",
        selectedTrackYtId: "NK347jqyPuc",
        spotifyId: "70Nfp7VBkXii0X9bmSln6a",
        deezerId: "3797481",
        designers: ["Augusto De Luca"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "riff_raff_riff_raff",
        title: `Riff Raff`,
        artist: "Riff Raff",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.JAM, criteria.JAZZY_GROOVY, criteria.C_FOLK, criteria.ODD_RHYTHM, criteria.UNCOMMON_INSTRUMENTS, criteria.BLUESY],
        selectedTrackTitle: "La Même Chose",
        selectedTrackYtId: "6tENfKOAsp4",
        spotifyId: null,
        deezerId: null,
        designers: ["Dave Field"],
        similarAlbums: ["titus_groan_titus_groan"],
        isAGem: false,
    },
    {
        id: "riff_raff_original_man",
        title: `Original Man`,
        artist: "Riff Raff",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.JAM, criteria.JAZZY_GROOVY, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.BLUESY],
        selectedTrackTitle: "Speed",
        selectedTrackYtId: "k3sDDfjZou4",
        spotifyId: null,
        deezerId: null,
        designers: ["Foster & Knowles"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "robert_connolly_plateau",
        title: "Plateau",
        artist: "Robert Connolly",
        year: 1978,
        country: regions.CANADA,
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.C_ELECTRO, criteria.SCI_FI],
        selectedTrackTitle: "Journey",
        selectedTrackYtId: "c4t_ThUzI48",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO Robert John Gallo - Free - 1971 - INTROUVABLE
    {
        id: "robert_john_gallo_painted_poetry",
        title: "Painted Poetry",
        artist: "Robert John Gallo",
        year: 1972,
        country: regions.USA,
        criteria: [criteria.FOLK, criteria.SOFT, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Tear Down The Circus",
        selectedTrackYtId: "_tYcKRGeJEs",
        spotifyId: "2DS9CCT4PpYTUek8RQvZCr",
        deezerId: "553150",
        designers: ["Nancy Wagner"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "robert_wyatt_the_end_of_an_ear",
        title: "The End Of An Ear",
        artist: "Robert Wyatt",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.EXPERIMENTAL, criteria.C_PSYCHE, criteria.FUNNY, criteria.C_JAZZ, criteria.TRANSITION, criteria.UNCOMMON_INSTRUMENTS, criteria.INSTRUMENTAL],
        selectedTrackTitle: "To Saintly Bridget",
        selectedTrackYtId: "_tYcKRGeJEs",
        spotifyId: "7evYgE9uJgR4EQbmgNnyo4",
        deezerId: "1460849",
        designers: ["Lipscombe Lubbock Ewart And Hollands"],
        similarAlbums: [], // similar henry cow
        isAGem: false,
    },
    {
        id: "robert_wyatt_rock_bottom",
        title: "Rock Bottom",
        artist: "Robert Wyatt",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.C_PSYCHE, criteria.C_ELECTRO, criteria.C_JAZZ, criteria.TRANSITION, criteria.UNCOMMON_INSTRUMENTS, criteria.SPACY],
        selectedTrackTitle: "Little Red Riding Hood Hit The Road",
        selectedTrackYtId: "8wZu6RapRyY",
        spotifyId: "72t34rHQENHfAK5kDLZjuG",
        deezerId: "427442",
        designers: ["Alfreda Benge"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "robert_wyatt_ruth_is_stranger_than_richard",
        title: "Ruth Is Stranger Than Richard",
        artist: "Robert Wyatt",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.PIANO, criteria.C_PSYCHE, criteria.SPACY, criteria.TRANSITION, criteria.UNCOMMON_INSTRUMENTS, criteria.ART_POP, criteria.C_JAZZ],
        selectedTrackTitle: "Solar Flares",
        selectedTrackYtId: "Q_ouozEomFU",
        spotifyId: "3ODvvITG5B0hecCUFguHl0",
        deezerId: "4502371",
        designers: ["Alfreda Benge"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "robert_wyatt_old_rottenhat",
        title: "Old Rottenhat",
        artist: "Robert Wyatt",
        year: 1985,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.ART_POP, criteria.C_ELECTRO],
        selectedTrackTitle: "Vandalusia",
        selectedTrackYtId: "WjGzHSU2KHU",
        spotifyId: "65SKiF0KDsjC0OD7HIL9mz",
        deezerId: "427440",
        designers: ["Alfreda Benge", "Caryn Gough"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "robert_wyatt_dondestan",
        title: "Dondestan",
        artist: "Robert Wyatt",
        year: 1991,
        country: regions.ENGLAND,
        criteria: [criteria.C_ELECTRO, criteria.SOFT, criteria.ART_POP, criteria.TRANSITION],
        selectedTrackTitle: "Costa",
        selectedTrackYtId: "75yX2kfz9XQ",
        spotifyId: "6djYV9B6p1weDkZDno6ecQ",
        deezerId: "427438",
        designers: ["Alfreda Benge"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rockets_rockets",
        title: "Rockets",
        artist: "Rockets",
        year: 1976,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.FRENCH, criteria.SCI_FI],
        selectedTrackTitle: "Apesanteur",
        selectedTrackYtId: "59m238yE4RM",
        spotifyId: "5ggDWFSJhjx2C77XWXjZRJ",
        deezerId: "7410146",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rockets_on_the_road_again",
        title: "On The Road Again",
        artist: "Rockets",
        year: 1978,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.FRENCH, criteria.SCI_FI],
        selectedTrackTitle: "Astrolights",
        selectedTrackYtId: "zUXYgMp8TpE",
        spotifyId: "19kPLq1L1mMjlfGDfJJ9No",
        deezerId: null,
        designers: ["Georges Spitzer", "Guido Harari"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rockets_plasteroid",
        title: "Plasteroïd",
        artist: "Rockets",
        year: 1979,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.SCI_FI],
        selectedTrackTitle: "Anastasis",
        selectedTrackYtId: "-NPZdqXXR5M",
        spotifyId: "3Ckp0RWxi8PMevZHiyCjdk",
        deezerId: "7379299",
        designers: ["Renaud Marchand", "Jean-Jacques Mahuteau"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rockets_galaxy",
        title: "Galaxy",
        artist: "Rockets",
        year: 1980,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.SCI_FI, criteria.FRENCH, criteria.ODD_RHYTHM, criteria.NEO_EIGHTIES, criteria.TRANSITION],
        selectedTrackTitle: "Prophecy",
        selectedTrackYtId: "5B3bGkgUaL4",
        spotifyId: "6oprEDexG4JtfqorLPI5AN",
        deezerId: "7375574",
        designers: ["Wojtek Siudmak", "Jean-Jacques Mahuteau"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rockets_three_point_fourteen_pi",
        title: "3.14 Pi",
        artist: "Rockets",
        year: 1981,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.SCI_FI, criteria.NEO_EIGHTIES, criteria.FRENCH, criteria.FEMALE, criteria.SOUND_COLLAGES],
        selectedTrackTitle: "Astro Storm",
        selectedTrackYtId: "4mW_bv1DGts",
        spotifyId: "0lwZB935LuBI91sn8UKOn3",
        deezerId: "7347530",
        designers: ["Wojtek Siudmak", "CGD Studio"],
        similarAlbums: [], // similar à du kraftwerk là (écouter king of the universe pour s'en rendre compte)
        isAGem: false,
    },
    {
        id: "roger_glover_the_butterfly_ball_and_the_grasshoppers_feast",
        title: `The Butterfly Ball And The Grasshopper's Feast`,
        artist: "Roger Glover",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.STORYLINE, criteria.ODD_RHYTHM, criteria.TRANSITION, criteria.BLENDS, criteria.PATCHWORK, criteria.ROCK_OPERA, criteria.FANFARE, criteria.FANTASY, criteria.FEMALE, criteria.PIANO],
        selectedTrackTitle: "Love Is All",
        selectedTrackYtId: "YK2Pltm8ZsQ",
        spotifyId: "0qyBo8KTEcKMyXVgahZ1Ps",
        deezerId: "13015474",
        designers: ["Alan Aldridge", "Harry Wilcock"],
        similarAlbums: [],
        isAGem: true,
        description: `Roger Glover gathered a lot of music performers to create a Rock Opera based on the eponym children's poem. This results in a colorful and enthusiastic piece with as much vocals as there are characters, and folkloric instruments to carry the cliché of old fantasy storybooks.`,
    },
    {
        id: "roger_waters_the_pros_and_cons_of_hitch_hiking",
        title: "The Pros And Cons Of Hitch Hiking",
        artist: "Roger Waters",
        year: 1984,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.C_FOLK, criteria.TRANSITION, criteria.NEO_EIGHTIES, criteria.FEMALE, criteria.TOUCHING_VOCALS],
        selectedTrackTitle: "4:33 AM (Running Shoes)",
        selectedTrackYtId: "XxEILZh5-qg",
        spotifyId: "7nCAVgLq6kcrCb4pw2uXGH",
        deezerId: "1444075",
        designers: ["Gerald Scarfe"],
        similarAlbums: ["pink_floyd_the_final_cut"],
        isAGem: false,
    },
    {
        id: "roger_waters_radio_kaos",
        title: "Radio K.A.O.S.",
        artist: "Roger Waters",
        year: 1987,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.NEO_EIGHTIES, criteria.ROCK, criteria.FEMALE, criteria.C_ELECTRO, criteria.TOUCHING_VOCALS, criteria.SOCIOPOLITICAL],
        selectedTrackTitle: "Who Needs Information",
        selectedTrackYtId: "IXKZNQvYB24",
        spotifyId: "7ID0EuIjKxSNFw6dqOWDmo",
        deezerId: "1448081",
        designers: ["Kate Hepburn", "Pearce Marchbank"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "roger_waters_amused_to_death",
        title: "Amused To Death",
        artist: "Roger Waters",
        year: 1992,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.NEO_EIGHTIES, criteria.TRANSITION, criteria.SOUNDTRACK, criteria.FEMALE, criteria.SOCIOPOLITICAL, criteria.ARENA],
        selectedTrackTitle: "What God Wants, Part III",
        selectedTrackYtId: "OccmcfZ9ZnY",
        spotifyId: "5RqQH15mFgHI984n25pFg3",
        deezerId: "10819024",
        designers: ["Tony Kaye"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "roger_waters_and_ron_geesin_music_from_the_body",
        title: "Music From The Body",
        artist: "Roger Waters & Ron Geesin",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.EXPERIMENTAL, criteria.TRANSITION, criteria.SOFT, criteria.UNCOMMON_INSTRUMENTS, criteria.SOUND_COLLAGES, criteria.C_PSYCHE, criteria.C_FOLK, criteria.PATCHWORK, criteria.SOUNDTRACK],
        selectedTrackTitle: "The Womb Bit",
        selectedTrackYtId: "vR-PDPS1-Pg",
        spotifyId: "45ViLs3I1DxFkbbO2BxaoK",
        deezerId: "715740",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_rolling_stones_their_satanic_majesties_request",
        title: "Their Satanic Majesties Request",
        artist: "The Rolling Stones",
        year: 1967,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `She's A Rainbow`,
        selectedTrackYtId: "6c1BThu95d8",
        spotifyId: "2SE7fs002NlNc3cw3SQLRC",
        deezerId: "912338",
        designers: ["Michael Cooper", "Artchie", "The Rolling Stones"],
        similarAlbums: ["the_beatles_sgt_peppers_lonely_hearts_club_band"],
        isAGem: false,
    },
    {
        id: "room_preflight",
        title: "Pre-Flight",
        artist: "Room",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.SYMPHONIC, criteria.FANFARE, criteria.ORCHESTRAL_PARTS, criteria.FEMALE, criteria.BLUESY],
        selectedTrackTitle: "Pre-Flight - Parts I & II",
        selectedTrackYtId: "seNGN86WqiQ",
        spotifyId: "1Kq0qKw3jFjIQfuCEJs7PA",
        deezerId: "668580",
        designers: ["Roy Putt"],
        similarAlbums: ["black_sabbath_black_sabbath"],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "rose_a_taste_of_neptune",
        title: "A Taste Of Neptune",
        artist: "Rose",
        year: 1977,
        country: regions.CANADA,
        criteria: [criteria.ROCK, criteria.C_ELECTRO, criteria.GLITTER],
        selectedTrackTitle: "A Taste Of Neptune",
        selectedTrackYtId: "Ku0JfmiYwSU",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rosebud_rosebud",
        title: "Rosebud",
        artist: "Rosebud",
        year: 1971,
        country: regions.USA,
        criteria: [criteria.ART_POP, criteria.C_FOLK, criteria.FEMALE, criteria.FRENCH],
        selectedTrackTitle: "Lorelei",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: "298710",
        designers: ["Henry Diltz"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ross_ross",
        title: "Ross",
        artist: "Ross",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.JAM, criteria.ROCK],
        selectedTrackTitle: "Changes",
        selectedTrackYtId: "Lsk9IwsC_zg",
        spotifyId: null,
        deezerId: null,
        designers: ["Patrick Woodroffe"],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO INTROUVABLE Ross - The Pit & The Pendulum - 1974 - Ken Marcus, Tom Wilkes - null + null
    {
        id: "il_rovescio_della_medaglia_la_bibbia",
        title: "La Bibbia",
        artist: "Il Rovescio Della Medaglia",
        year: 1971,
        country: regions.ITALY,
        criteria: [criteria.C_PSYCHE, criteria.ITALIAN, criteria.CONCEPT, criteria.SYMPHONIC, criteria.TRANSITION, criteria.JAM, criteria.ODD_RHYTHM, criteria.BAROQUE, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.SPIRITUAL],
        selectedTrackTitle: "La Creazione",
        selectedTrackYtId: "s6AcjJNrJpo",
        spotifyId: null,
        deezerId: "279205672",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "il_rovescio_della_medaglia_io_come_io",
        title: "Io Come Io",
        artist: "Il Rovescio Della Medaglia",
        year: 1972,
        country: regions.ITALY,
        criteria: [criteria.ITALIAN, criteria.SYMPHONIC, criteria.JAZZY_GROOVY, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Fenomeno",
        selectedTrackYtId: "fzzzkemi7qU",
        spotifyId: "0dId6y5HdhMKNjAdS14rUg",
        deezerId: "1435888",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "il_rovescio_della_medaglia_contaminazione",
        title: "Contaminazione",
        artist: "Il Rovescio Della Medaglia",
        year: 1973,
        country: regions.ITALY,
        criteria: [criteria.ITALIAN, criteria.BAROQUE, criteria.TRANSITION, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS, criteria.C_PSYCHE, criteria.ORCHESTRAL_PARTS],
        selectedTrackTitle: "Il Suono Del Silenzio",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: ["Impiglia E Mancini"],
        isAGem: false,
    },
    {
        id: "roxy_music_roxy_music",
        title: "Roxy Music",
        artist: "Roxy Music",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.UNCOMMON_INSTRUMENTS, criteria.FANFARE, criteria.C_PSYCHE],
        selectedTrackTitle: "Sea Breezes",
        selectedTrackYtId: "Nqmf39ZOJRc",
        spotifyId: "4uUtkBGEiq357ts7HZYuYF",
        deezerId: "55790122",
        designers: ["CCS"],
        similarAlbums: [], // TODO aladin sane ?
        isAGem: false,
    },
    {
        id: "roxy_music_for_your_pleasure",
        title: "For Your Pleasure",
        artist: "Roxy Music",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.C_PSYCHE],
        selectedTrackTitle: "In Every Dream Home A Heartache",
        selectedTrackYtId: "LSniBxXjK_8",
        spotifyId: "6gKMWnGptVs6yT2MgCxw29",
        deezerId: null,
        designers: ["CCS"],
        similarAlbums: [], // TODO similar tencc
        isAGem: false,
    },
    {
        id: "roxy_music_stranded",
        title: "Stranded",
        artist: "Roxy Music",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.FRENCH],
        selectedTrackTitle: "A Song For Europe",
        selectedTrackYtId: "auOBhaXEDvA",
        spotifyId: "46lN88zXwgNHAQnN9wWjiC",
        deezerId: "302070",
        designers: ["Bob Bowkett", "Smile", "Antony Price"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "roxy_music_country_life",
        title: "Country Life",
        artist: "Roxy Music",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.GERMAN, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Triptych",
        selectedTrackYtId: "YxXFVpCy3jI",
        spotifyId: "59RclwjkzMJTJZNxrfGdLC",
        deezerId: "302071",
        designers: ["CCS", "Bob Bowkett", "Nicholas De Ville"],
        similarAlbums: [], // TODO similar tencc
        isAGem: false,
    },
    {
        id: "roxy_music_siren",
        title: "Siren",
        artist: "Roxy Music",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.C_PSYCHE],
        selectedTrackTitle: "Sentimental Fool",
        selectedTrackYtId: "KY_TiaJGjdo",
        spotifyId: "5Tpor3YZBVEJ9tWD5L31mH",
        deezerId: "313602",
        designers: ["Bryan Ferry", "Adrianne Hunter", "Antony Price", "Bob Bowkett", "Celine", "Graham Hughes", "Nicholas De Ville"],
        similarAlbums: [], // TODO similar tencc
        isAGem: false,
    },
    {
        id: "roxy_music_manifesto",
        title: "Manifesto",
        artist: "Roxy Music",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.C_PSYCHE, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "Stronger Through The Years",
        selectedTrackYtId: "NjvG0k4GWfU",
        spotifyId: "1LDD2nUQ17tm1WMchsevtp",
        deezerId: "302073",
        designers: ["Bryan Ferry", "Antony Price", "Cream", "Neil Kirk", "Sally Feldman"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "roy_wood_boulders",
        title: "Boulders",
        artist: "Roy Wood",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.C_FOLK, criteria.FANFARE, criteria.FUNNY, criteria.BAROQUE, criteria.GREASY_SEVENTIES],
        selectedTrackTitle: "Miss Clarke And The Computer",
        selectedTrackYtId: "BTxp7cqrQjA",
        spotifyId: "3Q1T4z81ocgsJzWBNjSMMQ",
        deezerId: "300464",
        designers: ["Roy Wood"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "roy_wood_mustard",
        title: "Mustard",
        artist: "Roy Wood",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.BLENDS, criteria.BAROQUE, criteria.C_PSYCHE, criteria.GREASY_SEVENTIES],
        selectedTrackTitle: "Get On Down Home",
        selectedTrackYtId: "6n5Y25fE-f0",
        spotifyId: null,
        deezerId: null,
        designers: ["Roy Wood"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rush_rush",
        title: "Rush",
        artist: "Rush",
        year: 1974,
        country: regions.CANADA,
        criteria: [criteria.ROCK, criteria.HEAVY],
        selectedTrackTitle: "Working Man",
        selectedTrackYtId: "iIGKlicb8n0",
        spotifyId: "57ystaP7WpAOxvCxKFxByS",
        deezerId: "117238",
        designers: ["Paul Weldon"],
        similarAlbums: ["led_zeppelin_led_zeppelin"],
        isAGem: false,
    },
    {
        id: "rush_fly_by_night",
        title: "Fly By Night",
        artist: "Rush",
        year: 1975,
        country: regions.CANADA,
        criteria: [criteria.ROCK, criteria.HEAVY],
        selectedTrackTitle: "By-Tor & The Snow Dog",
        selectedTrackYtId: "2UU62UcP_BA",
        spotifyId: "3ZtICWkqezf0bBTUwY1Khe",
        deezerId: "117239",
        designers: ["Eraldo Carugati", "AGI, Chicago", "Jim Ladwig", "Joe Kotleba"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rush_caress_of_steel",
        title: "Caress Of Steel",
        artist: "Rush",
        year: 1975,
        country: regions.CANADA,
        criteria: [criteria.HEAVY, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC],
        selectedTrackTitle: "The Fountain Of Lamneth",
        selectedTrackYtId: "4mC7j-fxqfs",
        spotifyId: "3U3iBmoTag1wxENqHq2ZqF",
        deezerId: "13629406",
        designers: ["Hugh Syme"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rush_2112",
        title: "2112",
        artist: "Rush",
        year: 1976,
        country: regions.CANADA,
        criteria: [criteria.HEAVY, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC],
        selectedTrackTitle: "2112",
        selectedTrackYtId: "AZm1_jtY1SQ",
        spotifyId: "3eBrvZnagmIDbdgse7cjI6",
        deezerId: "6159884",
        designers: ["Hugh Syme"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "rush_a_farewell_to_kings",
        title: "A Farewell To Kings",
        artist: "Rush",
        year: 1977,
        country: regions.CANADA,
        criteria: [criteria.HEAVY, criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Xanadu",
        selectedTrackYtId: "SEuOoMprDqg",
        spotifyId: "18i33u5FvfvgHjZMulpyO2",
        deezerId: "162134",
        designers: ["Hugh Syme", "Bob King", "Yosh Inouye"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "rush_hemispheres",
        title: "Hemispheres",
        artist: "Rush",
        year: 1978,
        country: regions.CANADA,
        criteria: [criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Cygnus X-1 Book II: Hemispheres",
        selectedTrackYtId: "J3AJUjtWTgc",
        spotifyId: "2vrM9ltjKIvNg3nkwXoJuc",
        deezerId: "229925",
        designers: ["Hugh Syme", "Bob King", "Yosh Inouye"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "rush_permanent_waves",
        title: "Permanent Waves",
        artist: "Rush",
        year: 1980,
        country: regions.CANADA,
        criteria: [criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Jacob's Ladder`,
        selectedTrackYtId: "iuKEp-ropCc",
        spotifyId: "3nUNxSh2szhmN7iifAKv5i",
        deezerId: "124360",
        designers: ["Hugh Syme", "Neil Peart"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rush_moving_pictures",
        title: "Moving Pictures",
        artist: "Rush",
        year: 1981,
        country: regions.CANADA,
        criteria: [criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ODD_RHYTHM, criteria.TECHNICAL],
        selectedTrackTitle: "The Camera Eye",
        selectedTrackYtId: "fjrHJhMHyIM",
        spotifyId: "2xg7iIKoSqaDNpDbJnyCjY",
        deezerId: "942295",
        designers: ["Hugh Syme"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rush_signals",
        title: "Signals",
        artist: "Rush",
        year: 1982,
        country: regions.CANADA,
        criteria: [criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Digital Man",
        selectedTrackYtId: "0fOjsIxinDk",
        spotifyId: "0gAhBCBqahVbuOgROHwISD",
        deezerId: "245685",
        designers: ["Hugh Syme"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rush_grace_under_pressure",
        title: "Grace Under Pressure",
        artist: "Rush",
        year: 1984,
        country: regions.CANADA,
        criteria: [criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA, criteria.ODD_RHYTHM],
        selectedTrackTitle: "The Body Electric",
        selectedTrackYtId: "r3Dju2i4FZw",
        spotifyId: "20RfdO7fta9qlXEWTFSWuT",
        deezerId: "228401",
        designers: ["Hugh Syme"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rush_power_windows",
        title: "Power Windows",
        artist: "Rush",
        year: 1985,
        country: regions.CANADA,
        criteria: [criteria.ODD_RHYTHM, criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA],
        selectedTrackTitle: "Marathon",
        selectedTrackYtId: "cxxgEzVkEjI",
        spotifyId: "4g5nPCL3oFaJB0402Kedm8",
        deezerId: "1958541",
        designers: ["Hugh Syme"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "rush_hold_your_fire",
        title: "Hold Your Fire",
        artist: "Rush",
        year: 1987,
        country: regions.CANADA,
        criteria: [criteria.FEMALE, criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA],
        selectedTrackTitle: "Open Secrets",
        selectedTrackYtId: "ypwtq1ShnHI",
        spotifyId: "3OSQvwW2BElGZfjhsHJEru",
        deezerId: "117782",
        designers: ["Hugh Syme"],
        similarAlbums: [], // TODO similar to yes neo eighties?
        isAGem: false,
    },
    {
        id: "rush_presto",
        title: "Presto",
        artist: "Rush",
        year: 1989,
        country: regions.CANADA,
        criteria: [criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Superconductor",
        selectedTrackYtId: "g0tpASDwr_0",
        spotifyId: "2DhyqYUQtUBdeT1YOe9o3R",
        deezerId: "340048",
        designers: ["Hugh Syme"],
        similarAlbums: [], // TODO similar to genesis
        isAGem: false,
    },
    {
        id: "rush_roll_the_bones",
        title: "Roll The Bones",
        artist: "Rush",
        year: 1991,
        country: regions.CANADA,
        criteria: [criteria.NEO_EIGHTIES, criteria.ARENA, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Where's My Thing?`,
        selectedTrackYtId: "hOj0eO3zCbc",
        spotifyId: "2DhyqYUQtUBdeT1YOe9o3R",
        deezerId: "340048",
        designers: ["Hugh Syme"],
        similarAlbums: [], // TODO similar to genesis
        isAGem: false,
    },
    {
        id: "rush_counterparts",
        title: "Counterparts",
        artist: "Rush",
        year: 1993,
        country: regions.CANADA,
        criteria: [criteria.ROCK, criteria.HEAVY, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Double Agent`,
        selectedTrackYtId: "vFN-9KjV4F4",
        spotifyId: "0BknttIOsexUKtdMdLrxQo",
        deezerId: "1698709",
        designers: ["Hugh Syme"],
        similarAlbums: [],
        isAGem: false,
    },
]

export default albums
