import regions from '../regions'
import { criteria } from '../criteria'

const albums = [
    {
        id: 'rainbow_rainbow',
        title: 'Rainbow',
        artist: 'Rainbow',
        year: 1975,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.JAM, criteria.ROCK, criteria.HEAVY, criteria.FANTASY],
        selectedTrackTitle: 'Catch The Rainbow',
        selectedTrackYtId: 'p3VgV31vmUE',
        spotifyId: '3LXOrVXLXwRiOguE446OZo',
        deezerId: '162197',
        designers: ['David Willardson'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rainbow_rising',
        title: 'Rising',
        artist: 'Rainbow',
        year: 1976,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.JAM, criteria.ROCK, criteria.SPECTACULAR, criteria.HEAVY, criteria.FANTASY, criteria.ARENA],
        selectedTrackTitle: 'Stargazer',
        selectedTrackYtId: 'rVXy1OhaERY',
        spotifyId: '3uIT4I4Dy7Pq1j0aSjzPW9',
        deezerId: '124376',
        designers: ['Ken Kelly'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rainbow_long_live_rock_n_roll',
        title: `Long Live Rock 'N' Roll`,
        artist: 'Rainbow',
        year: 1978,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.JAM, criteria.ROCK, criteria.SPECTACULAR, criteria.HEAVY, criteria.FANTASY, criteria.ARENA],
        selectedTrackTitle: 'Gates Of Babylon',
        selectedTrackYtId: 'MHCdCbTxypU',
        spotifyId: '56JX1fNOjTa7Bj7G18nxSq',
        deezerId: '6058392',
        designers: ['Debbie Hall', 'Maxi Chan'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_erik_xiv_och_ristningar',
        title: 'Erik XIV Och Ristningar',
        artist: 'Ralph Lundsten',
        year: 1969,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.C_PSYCHE, criteria.AMBIENT],
        selectedTrackTitle: 'Manteldans',
        selectedTrackYtId: 'wBQTKxn14ls',
        spotifyId: null,
        deezerId: null,
        designers: ['Hans Arnold'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_olskog',
        title: 'Ölskog',
        artist: 'Ralph Lundsten',
        year: 1970,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.C_PSYCHE, criteria.AMBIENT, criteria.LENGTHY_TRACKS, criteria.SWEDISH],
        selectedTrackTitle: 'Through A Landscape Of Mirrors',
        selectedTrackYtId: 'rNjAgLprkdQ',
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_gustav_iii_nattmara',
        title: 'Gustav III / Nattmara',
        artist: 'Ralph Lundsten',
        year: 1971,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.AMBIENT, criteria.UNCOMMON_INSTRUMENTS, criteria.MEDIEVAL, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: 'Nattmara',
        selectedTrackYtId: 'JVu9LPd9i84',
        spotifyId: null,
        deezerId: null,
        designers: ['Hans Arnold'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_fadervar',
        title: 'Fadervår',
        artist: 'Ralph Lundsten',
        year: 1972,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.SOUND_COLLAGES, criteria.AMBIENT, criteria.SPIRITUAL, criteria.FEMALE],
        selectedTrackTitle: 'Anrop - Fader Vår Som Är I Himmelen',
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ['Gustave Doré'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_stromkarlen',
        title: 'Strömkarlen',
        artist: 'Ralph Lundsten',
        year: 1973,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.SOUND_COLLAGES, criteria.AMBIENT, criteria.C_PSYCHE, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: 'I Landet Längesen', // TODO par defaut
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ['Hans Arnold'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_skrack_och_skratt_resor_i_okanda_varldar',
        title: 'Skräck Och Skratt, Resor I Okända Världar',
        artist: 'Ralph Lundsten',
        year: 1973,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.C_PSYCHE],
        selectedTrackTitle: 'Midnattstimmen I: Gengångarnatt',
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_svit_for_elektroniskt_dragspel_gunnar_pa_lidarande',
        title: 'Svit För Elektroniskt Dragspel / Gunnar På Lidarände',
        artist: 'Ralph Lundsten',
        year: 1973,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.EXPERIMENTAL, criteria.C_PSYCHE, criteria.SOUND_COLLAGES],
        selectedTrackTitle: 'Svit För Elektroniskt Dragspel II: Pastoral',
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_shangri_la',
        title: 'Shangri-La',
        artist: 'Ralph Lundsten',
        year: 1975,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.TRANSITION, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: 'Shangri-La',
        selectedTrackYtId: 'Gg0dopo1q4U',
        spotifyId: null,
        deezerId: null,
        designers: ['Hans Arnold'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_ralph_lundstens_universe',
        title: `Ralph Lundsten's Universe`,
        artist: 'Ralph Lundsten',
        year: 1976,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.TRANSITION, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO, criteria.SCI_FI],
        selectedTrackTitle: 'The Blue Planet',
        selectedTrackYtId: 'nc207RhZQDQ',
        spotifyId: '3PEQcKyh9TvtBxdDLhs92R',
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_discophrenia',
        title: 'Discophrenia',
        artist: 'Ralph Lundsten',
        year: 1978,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.ELECTRO, criteria.SCI_FI],
        selectedTrackTitle: 'Discophrenia',
        selectedTrackYtId: 'wgWUJBJ4Tt8',
        spotifyId: null,
        deezerId: null,
        designers: ['Birgitta Hartzell-Wittgenstein'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_alpha_ralpha_boulevard',
        title: 'Alpha Ralpha Boulevard',
        artist: 'Ralph Lundsten',
        year: 1979,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO, criteria.SCI_FI],
        selectedTrackTitle: 'Alpha Ralpha Boulevard',
        selectedTrackYtId: 'uKL5tj0FHDk',
        spotifyId: null,
        deezerId: null,
        designers: ['William Feilding'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_paradissymfonin',
        title: 'Paradissymfonin',
        artist: 'Ralph Lundsten',
        year: 1980,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.SOFT, criteria.AMBIENT, criteria.ELECTRO, criteria.NEO_EIGHTIES],
        selectedTrackTitle: 'Himmelens Port',
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ['Gustave Doré'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ralph_lundsten_the_new_age',
        title: 'The New Age',
        artist: 'Ralph Lundsten',
        year: 1982,
        country: regions.SWEDEN,
        cover: '.jpg',
        criteria: [criteria.CONCEPT, criteria.INSTRUMENTAL, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.ELECTRO, criteria.NEO_EIGHTIES],
        selectedTrackTitle: 'Time Storm',
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ['Ulf Hinders'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ramses_la_leyla',
        title: 'La Leyla',
        artist: 'Ramses',
        year: 1976,
        country: regions.GERMANY,
        cover: '.jpg',
        criteria: [criteria.SOFT, criteria.C_ELECTRO, criteria.HUMBLE, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: 'La Leyla',
        selectedTrackYtId: 'FmiSuG7PuVs',
        spotifyId: null,
        deezerId: null,
        designers: ['Helga Bartkowiak'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ramses_eternity_rise',
        title: 'Eternity Rise',
        artist: 'Ramses',
        year: 1978,
        country: regions.GERMANY,
        cover: '.jpg',
        criteria: [criteria.SOFT, criteria.C_ELECTRO, criteria.HUMBLE, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: 'Only Yesterday',
        selectedTrackYtId: 'KYfxukQkw10',
        spotifyId: null,
        deezerId: null,
        designers: ['Helga Bartkowiak'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'ramses_light_fantastic',
        title: 'Light Fantastic',
        artist: 'Ramses',
        year: 1981,
        country: regions.GERMANY,
        cover: '.jpg',
        criteria: [criteria.SOFT, criteria.C_ELECTRO, criteria.HUMBLE, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: 'Across The Everglades',
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ['Helga Bartkowiak', 'Norbert Leidecker'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'raymond_vincent_metronomics',
        title: 'Metronomics',
        artist: 'Raymond Vincent',
        year: 1973,
        country: regions.BELGIUM,
        cover: '.jpg',
        criteria: [criteria.INSTRUMENTAL, criteria.C_FOLK, criteria.PATCHWORK],
        selectedTrackTitle: 'La Mouette',
        selectedTrackYtId: '5g1Ppivoqu0',
        spotifyId: null,
        deezerId: null,
        designers: ['Josse Goffin'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'recreation_dont_open',
        title: `Don't Open`,
        artist: 'Recreation',
        year: 1970,
        country: regions.BELGIUM,
        cover: '.jpg',
        criteria: [criteria.GREASY_SEVENTIES, criteria.JAM, criteria.INSTRUMENTAL, criteria.BAROQUE, criteria.TRANSITION, criteria.SOUND_COLLAGES],
        selectedTrackTitle: `Running For Life`,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ['Helmut Wenske'],
        similarAlbums: [], // TODO similardébut de beggar's opera
        isAGem: false,
    },
    {
        id: 'recreation_music_or_not_music',
        title: 'Music Or Not Music',
        artist: 'Recreation',
        year: 1972,
        country: regions.BELGIUM,
        cover: '.jpg',
        criteria: [criteria.GREASY_SEVENTIES, criteria.C_PSYCHE, criteria.JAM, criteria.FUNNY, criteria.PATCHWORK, criteria.TRANSITION, criteria.SOUND_COLLAGES, criteria.INSTRUMENTAL],
        selectedTrackTitle: `My Grandmother Likes Andy Williams, Too`,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ['Nicole Claveloux'],
        similarAlbums: [], // TODO similar aporhidte child 666 + début de beggar's opera
        isAGem: true,
        description: `TODO description` // Assez fou, enchainement de scaynettes musicales sans sens apparent, mais juste du délire par ci par là
    },
    {
        id: 'return_to_forever_return_to_forever',
        title: 'Return To Forever',
        artist: 'Return To Forever',
        year: 1972,
        country: regions.USA,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.INSTRUMENTAL, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: 'Crystal Silence',
        selectedTrackYtId: '69rjdr7SR0Q',
        spotifyId: '6M0IAJHwQ6dFNtTkFsXCJc',
        deezerId: '124358',
        designers: ['Michael Manoogian'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'return_to_forever_light_as_a_feather',
        title: 'Light As A Feather',
        artist: 'Return To Forever',
        year: 1972,
        country: regions.USA,
        cover: '.jpg',
        criteria: [criteria.JAM, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: 'Spain',
        selectedTrackYtId: 'a_OEJ0wqt2g',
        spotifyId: '2wkmxijYToqAr0ATgcNSsn',
        deezerId: '239959',
        designers: ['Hamish Grimes'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'return_to_forever_hymn_of_the_seventh_galaxy',
        title: 'Hymn Of The Seventh Galaxy',
        artist: 'Return To Forever',
        year: 1973,
        country: regions.USA,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: 'After The Cosmic Rain',
        selectedTrackYtId: 'MWPo6oqHvJ8',
        spotifyId: '0ddNu3IWO5iEHoBe9qOr5L',
        deezerId: '230734',
        designers: ['Don Brautigan', 'Neville Potter'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'return_to_forever_where_have_i_known_you_before',
        title: 'Where Have I Known You Before',
        artist: 'Return To Forever',
        year: 1974,
        country: regions.USA,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: 'Song To The Pharoah Kings',
        selectedTrackYtId: 'q-XDtjCwS9Q',
        spotifyId: '1LAARZVfnq12x7Ueei4jx7',
        deezerId: '248142',
        designers: ['Petra Kinkele', 'Neville Potter', 'Herb Deiwitz'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'return_to_forever_no_mystery',
        title: 'No Mystery',
        artist: 'Return To Forever',
        year: 1975,
        country: regions.USA,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: 'Celebration Suite (Part I)',
        selectedTrackYtId: 'LBawRSufDlU',
        spotifyId: '0OjgANiCv3GFQWq1B8No1j',
        deezerId: null,
        designers: ['Petra Kinkele', 'Bill Levy', 'Neville Potter'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'return_to_forever_romantic_warrior',
        title: 'Romantic Warrior',
        artist: 'Return To Forever',
        year: 1976,
        country: regions.USA,
        cover: '.jpg',
        criteria: [criteria.CONCEPT, criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.JAZZ, criteria.JAZZY_GROOVY, criteria.MEDIEVAL],
        selectedTrackTitle: 'Duel Of The Jester And The Tyrant',
        selectedTrackYtId: 'sa21WPH4_U4',
        spotifyId: '1R2UR5wAs50dpbHkhUtLH7',
        deezerId: '6750057',
        designers: ['Wilson McLean'],
        similarAlbums: ['chick_corea_the_leprechaun'],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: 'return_to_forever_musicmagic',
        title: 'Musicmagic',
        artist: 'Return To Forever',
        year: 1977,
        country: regions.USA,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZ, criteria.JAZZY_GROOVY, criteria.SOFT_SEVENTIES, criteria.FEMALE],
        selectedTrackTitle: 'The Endless Night',
        selectedTrackYtId: 'STXJFzaAj0U',
        spotifyId: '0dmDVVzPAjPHmAND1gq8LY',
        deezerId: '114702',
        designers: ['Catherine Loeb'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'la_revolution_francaise_la_revolution_francaise',
        title: 'La Révolution Française',
        artist: 'La Révolution Française',
        year: 1973,
        country: regions.FRANCE,
        cover: '.jpg',
        criteria: [criteria.FRENCH, criteria.ODD_RHYTHM, criteria.SPECTACULAR, criteria.ROCK_OPERA, criteria.PATCHWORK, criteria.STORYLINE, criteria.ORCHESTRAL_PARTS, criteria.TRANSITION, criteria.FANFARE, criteria.FEMALE],
        selectedTrackTitle: 'Le Procès De Louis XVI : Réquisitoire / Exécution',
        selectedTrackYtId: 'o97Xff6ReYw',
        spotifyId: '6K6SzeA8aDcF4eib3uH1A9',
        deezerId: '3890411',
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'robert_connolly_plateau',
        title: 'Plateau',
        artist: 'Robert Connolly',
        year: 1978,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.C_ELECTRO, criteria.SCI_FI],
        selectedTrackTitle: 'Journey',
        selectedTrackYtId: 'c4t_ThUzI48',
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'roger_glover_the_butterfly_ball_and_the_grasshoppers_feast',
        title: `The Butterfly Ball And The Grasshopper's Feast`,
        artist: 'Roger Glover',
        year: 1974,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.STORYLINE, criteria.ODD_RHYTHM, criteria.TRANSITION, criteria.BLENDS, criteria.PATCHWORK, criteria.ROCK_OPERA, criteria.FANFARE, criteria.FANTASY, criteria.FEMALE, criteria.PIANO],
        selectedTrackTitle: 'Love Is All',
        selectedTrackYtId: 'YK2Pltm8ZsQ',
        spotifyId: '0qyBo8KTEcKMyXVgahZ1Ps',
        deezerId: '13015474',
        designers: ['Alan Aldridge', 'Harry Wilcock'],
        similarAlbums: [],
        isAGem: true,
        description: `Roger Glover gathered a lot of music performers to create a Rock Opera based on the eponym children's poem. This results in a colorful and enthusiastic piece with as much vocals as there are characters, and folkloric instruments to carry the cliché of old fantasy storybooks.`,
    },
    {
        id: 'roger_waters_and_ron_geesin_music_from_the_body',
        title: 'Music From The Body',
        artist: 'Roger Waters & Ron Geesin',
        year: 1970,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.CONCEPT, criteria.EXPERIMENTAL, criteria.TRANSITION, criteria.SOFT, criteria.UNCOMMON_INSTRUMENTS, criteria.SOUND_COLLAGES, criteria.C_PSYCHE, criteria.C_FOLK, criteria.PATCHWORK, criteria.SOUNDTRACK],
        selectedTrackTitle: 'The Womb Bit',
        selectedTrackYtId: 'vR-PDPS1-Pg',
        spotifyId: '45ViLs3I1DxFkbbO2BxaoK',
        deezerId: '715740',
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'the_rolling_stones_their_satanic_majesties_request',
        title: 'Their Satanic Majesties Request',
        artist: 'The Rolling Stones',
        year: 1967,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.C_PSYCHE, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `She's A Rainbow`,
        selectedTrackYtId: '6c1BThu95d8',
        spotifyId: '2SE7fs002NlNc3cw3SQLRC',
        deezerId: '912338',
        designers: ['Michael Cooper', 'Artchie', 'The Rolling Stones'],
        similarAlbums: ['the_beatles_sgt_peppers_lonely_hearts_club_band'],
        isAGem: false,
    },
    {
        id: 'roy_wood_boulders',
        title: 'Boulders',
        artist: 'Roy Wood',
        year: 1973,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ART_POP, criteria.C_FOLK, criteria.FANFARE, criteria.FUNNY, criteria.BAROQUE, criteria.GREASY_SEVENTIES],
        selectedTrackTitle: 'Miss Clarke And The Computer',
        selectedTrackYtId: 'BTxp7cqrQjA',
        spotifyId: '3Q1T4z81ocgsJzWBNjSMMQ',
        deezerId: '300464',
        designers: ['Roy Wood'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'roy_wood_mustard',
        title: 'Mustard',
        artist: 'Roy Wood',
        year: 1975,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ART_POP, criteria.BLENDS, criteria.BAROQUE, criteria.C_PSYCHE, criteria.GREASY_SEVENTIES],
        selectedTrackTitle: 'Get On Down Home',
        selectedTrackYtId: '6n5Y25fE-f0',
        spotifyId: null,
        deezerId: null,
        designers: ['Roy Wood'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rush_rush',
        title: 'Rush',
        artist: 'Rush',
        year: 1974,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.ROCK, criteria.HEAVY],
        selectedTrackTitle: 'Working Man',
        selectedTrackYtId: 'iIGKlicb8n0',
        spotifyId: '57ystaP7WpAOxvCxKFxByS',
        deezerId: '117238',
        designers: ['Paul Weldon'],
        similarAlbums: ['led_zeppelin_led_zeppelin'],
        isAGem: false,
    },
    {
        id: 'rush_fly_by_night',
        title: 'Fly By Night',
        artist: 'Rush',
        year: 1975,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.ROCK, criteria.HEAVY],
        selectedTrackTitle: 'By-Tor & The Snow Dog',
        selectedTrackYtId: '2UU62UcP_BA',
        spotifyId: '3ZtICWkqezf0bBTUwY1Khe',
        deezerId: '117239',
        designers: ['Eraldo Carugati', 'AGI, Chicago', 'Jim Ladwig', 'Joe Kotleba'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rush_caress_of_steel',
        title: 'Caress Of Steel',
        artist: 'Rush',
        year: 1975,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.HEAVY, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC],
        selectedTrackTitle: 'The Fountain Of Lamneth',
        selectedTrackYtId: '4mC7j-fxqfs',
        spotifyId: '3U3iBmoTag1wxENqHq2ZqF',
        deezerId: '13629406',
        designers: ['Hugh Syme'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rush_2112',
        title: '2112',
        artist: 'Rush',
        year: 1976,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.HEAVY, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC],
        selectedTrackTitle: '2112',
        selectedTrackYtId: 'AZm1_jtY1SQ',
        spotifyId: '3eBrvZnagmIDbdgse7cjI6',
        deezerId: '6159884',
        designers: ['Hugh Syme'],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: 'rush_a_farewell_to_kings',
        title: 'A Farewell To Kings',
        artist: 'Rush',
        year: 1977,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.HEAVY, criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: 'Xanadu',
        selectedTrackYtId: 'SEuOoMprDqg',
        spotifyId: '18i33u5FvfvgHjZMulpyO2',
        deezerId: '162134',
        designers: ['Hugh Syme', 'Bob King', 'Yosh Inouye'],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: 'rush_hemispheres',
        title: 'Hemispheres',
        artist: 'Rush',
        year: 1978,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: 'Cygnus X-1 Book II: Hemispheres',
        selectedTrackYtId: 'J3AJUjtWTgc',
        spotifyId: '2vrM9ltjKIvNg3nkwXoJuc',
        deezerId: '229925',
        designers: ['Hugh Syme', 'Bob King', 'Yosh Inouye'],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: 'rush_permanent_waves',
        title: 'Permanent Waves',
        artist: 'Rush',
        year: 1980,
        country: regions.CANADA,
        cover: '.png',
        criteria: [criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Jacob's Ladder`,
        selectedTrackYtId: 'iuKEp-ropCc',
        spotifyId: '3nUNxSh2szhmN7iifAKv5i',
        deezerId: '124360',
        designers: ['Hugh Syme', 'Neil Peart'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rush_moving_pictures',
        title: 'Moving Pictures',
        artist: 'Rush',
        year: 1981,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ODD_RHYTHM, criteria.TECHNICAL],
        selectedTrackTitle: 'The Camera Eye',
        selectedTrackYtId: 'fjrHJhMHyIM',
        spotifyId: '2xg7iIKoSqaDNpDbJnyCjY',
        deezerId: '942295',
        designers: ['Hugh Syme'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rush_signals',
        title: 'Signals',
        artist: 'Rush',
        year: 1982,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA, criteria.ODD_RHYTHM],
        selectedTrackTitle: 'Digital Man',
        selectedTrackYtId: '0fOjsIxinDk',
        spotifyId: '0gAhBCBqahVbuOgROHwISD',
        deezerId: '245685',
        designers: ['Hugh Syme'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rush_grace_under_pressure',
        title: 'Grace Under Pressure',
        artist: 'Rush',
        year: 1984,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA, criteria.ODD_RHYTHM],
        selectedTrackTitle: 'The Body Electric',
        selectedTrackYtId: 'r3Dju2i4FZw',
        spotifyId: '20RfdO7fta9qlXEWTFSWuT',
        deezerId: '228401',
        designers: ['Hugh Syme'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rush_power_windows',
        title: 'Power Windows',
        artist: 'Rush',
        year: 1985,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA],
        selectedTrackTitle: 'Marathon',
        selectedTrackYtId: 'cxxgEzVkEjI',
        spotifyId: '4g5nPCL3oFaJB0402Kedm8',
        deezerId: '1958541',
        designers: ['Hugh Syme'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'rush_hold_your_fire',
        title: 'Hold Your Fire',
        artist: 'Rush',
        year: 1987,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.FEMALE, criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA],
        selectedTrackTitle: 'Open Secrets',
        selectedTrackYtId: 'ypwtq1ShnHI',
        spotifyId: '3OSQvwW2BElGZfjhsHJEru',
        deezerId: '117782',
        designers: ['Hugh Syme'],
        similarAlbums: [], // TODO similar to yes neo eighties?
        isAGem: false,
    },
    {
        id: 'rush_presto',
        title: 'Presto',
        artist: 'Rush',
        year: 1989,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.ARENA, criteria.ODD_RHYTHM],
        selectedTrackTitle: 'Superconductor',
        selectedTrackYtId: 'g0tpASDwr_0',
        spotifyId: '2DhyqYUQtUBdeT1YOe9o3R',
        deezerId: '340048',
        designers: ['Hugh Syme'],
        similarAlbums: [], // TODO similar to genesis
        isAGem: false,
    },
    {
        id: 'rush_roll_the_bones',
        title: 'Roll The Bones',
        artist: 'Rush',
        year: 1991,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.NEO_EIGHTIES, criteria.ARENA, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Where's My Thing?`,
        selectedTrackYtId: 'hOj0eO3zCbc',
        spotifyId: '2DhyqYUQtUBdeT1YOe9o3R',
        deezerId: '340048',
        designers: ['Hugh Syme'],
        similarAlbums: [], // TODO similar to genesis
        isAGem: false,
    },
    {
        id: 'rush_counterparts',
        title: 'Counterparts',
        artist: 'Rush',
        year: 1993,
        country: regions.CANADA,
        cover: '.jpg',
        criteria: [criteria.ROCK, criteria.HEAVY, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Double Agent`,
        selectedTrackYtId: 'vFN-9KjV4F4',
        spotifyId: '0BknttIOsexUKtdMdLrxQo',
        deezerId: '1698709',
        designers: ['Hugh Syme'],
        similarAlbums: [],
        isAGem: false,
    },
]

export default albums