import { regions } from "../regions"
import { criteria } from "../criteria"

/**
 * @type {Array.<import(".").Album>}
 */
const albums = [
    {
        id: "sacbe_sacbe",
        title: "Sacbé",
        artist: "Sacbé",
        year: 1977,
        country: regions.MEXICO,
        criteria: [criteria.FANFARE, criteria.JAZZ, criteria.SOFT_SEVENTIES, criteria.LATINO, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZY_GROOVY, criteria.INSTRUMENTAL, criteria.JAM],
        selectedTrackTitle: "Andromeda",
        selectedTrackYtId: "8bch22jRO-s",
        spotifyId: null,
        deezerId: null,
        designers: ["Enrique Toussaint", "Luis Gil"],
        similarAlbums: ["weather_report_black_market"],
        isAGem: true,
        description: `TODO Description`,
    },
    // TODO INTROUVABLE Sacbé albums
    {
        id: "sacbe_dos_mundos",
        title: "Dos Mundos",
        artist: "Sacbé",
        year: 1988,
        country: regions.MEXICO,
        criteria: [criteria.NEO_EIGHTIES, criteria.JAZZ, criteria.LATINO, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZY_GROOVY, criteria.INSTRUMENTAL, criteria.JAM],
        selectedTrackTitle: "Serendipity",
        selectedTrackYtId: "rC3i99fSRbs",
        spotifyId: null,
        deezerId: null,
        designers: ["Eniac Martínez"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "saint_preux_le_piano_sous_la_mer",
        title: "Le Piano Sous La Mer",
        artist: "Saint-Preux",
        year: 1972,
        country: regions.FRANCE,
        criteria: [criteria.CONCEPT, criteria.UNCOMMON_INSTRUMENTS, criteria.BAROQUE, criteria.SOUND_COLLAGES, criteria.TRANSITION, criteria.FEMALE, criteria.INSTRUMENTAL, criteria.C_PSYCHE],
        selectedTrackTitle: "La Rencontre",
        selectedTrackYtId: "NdYUITdoRNw",
        spotifyId: "3upPUC1BDzyaKYxH02i7wz",
        deezerId: "100832",
        designers: ["Laurent Camil"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "saint_preux_samara",
        title: "Samara",
        artist: "Saint-Preux",
        year: 1976,
        country: regions.FRANCE,
        criteria: [criteria.CONCEPT, criteria.C_ELECTRO, criteria.BAROQUE, criteria.ORCHESTRAL_PARTS, criteria.PIANO, criteria.TRANSITION, criteria.INSTRUMENTAL, criteria.FRENCH, criteria.C_ELECTRO],
        selectedTrackTitle: "Paradis Artificiels",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["François Titeux De La Croix"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "saint_preux_expression",
        title: "Expression",
        artist: "Saint-Preux",
        year: 1978,
        country: regions.FRANCE,
        criteria: [criteria.CONCEPT, criteria.PIANO, criteria.BAROQUE, criteria.ELECTRO, criteria.INSTRUMENTAL],
        selectedTrackTitle: "Expression Part. II",
        selectedTrackYtId: "G4AolcYC6pM",
        spotifyId: null,
        deezerId: null,
        designers: ["David Nils"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "saint_preux_atlantis",
        title: "Atlantis",
        artist: "Saint-Preux",
        year: 1979,
        country: regions.FRANCE,
        criteria: [criteria.CONCEPT, criteria.STORYLINE, criteria.ORCHESTRAL_PARTS, criteria.BLENDS, criteria.TRANSITION, criteria.INSTRUMENTAL, criteria.PIANO, criteria.JAZZY_GROOVY, criteria.ODD_RHYTHM, criteria.BAROQUE, criteria.C_PSYCHE, criteria.SPECTACULAR],
        selectedTrackTitle: "Atlantis March",
        selectedTrackYtId: "i29JpRfSTlQ",
        spotifyId: "5vSSVQiQ3rYYptHtIAR5b6",
        deezerId: "101816",
        designers: [],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "salem_mass_witch_burning",
        title: "Witch Burning",
        artist: "Salem Mass",
        year: 1971,
        country: regions.USA,
        criteria: [criteria.CRISPY_SIXTIES, criteria.C_ELECTRO, criteria.JAM, criteria.C_PSYCHE, criteria.ROCK],
        selectedTrackTitle: "Witch Burning",
        selectedTrackYtId: "TR5OQfnI998",
        spotifyId: "3tuhi1Zg0RRYDWwvs5uMvC",
        deezerId: "154348192",
        designers: ["Mark Libby"],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO INTROUVABLE - Salis - Sa Vida Ita Est - 1971
    // TODO INTROUVABLE - Salis - Seduto Sull'Alba A Guardare - 1974
    {
        id: "salis_dopo_il_buio_la_luce",
        title: "Dopo Il Buio La Luce",
        artist: "Salis",
        year: 1979,
        country: regions.ITALY,
        criteria: [criteria.C_ELECTRO, criteria.INSTRUMENTAL, criteria.JAM, criteria.SYMPHONIC, criteria.ODD_RHYTHM, criteria.ITALIAN, criteria.SOPHISTICATED],
        selectedTrackTitle: "Dopo Il Buio... La Luce",
        selectedTrackYtId: "FLK3fh2gkgU",
        spotifyId: "5ab6IXSfBUiwxnCnc0TplP",
        deezerId: "12333054",
        designers: [],
        similarAlbums: [],
        isAGem: false, // TODO gem true???
    },
    {
        id: "sand_golem",
        title: "Golem",
        artist: "Sand",
        year: 1974,
        country: regions.GERMANY,
        criteria: [criteria.C_PSYCHE, criteria.C_ELECTRO, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: "Sarah",
        selectedTrackYtId: "DsWIGD0-Jis",
        spotifyId: "2BtEy3VFyDyVoOzh9l1aM8",
        deezerId: null,
        designers: ["Silvia Christoph"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "santana_abraxas",
        title: "Abraxas",
        artist: "Santana",
        year: 1970,
        country: regions.USA,
        criteria: [criteria.JAM, criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.SPANISH, criteria.LATINO],
        selectedTrackTitle: "Singing Winds, Crying Beasts",
        selectedTrackYtId: "Xskk5q1DL6A",
        spotifyId: "1CHUXwuge9A7L2KiA3vnR6",
        deezerId: "7740828",
        designers: ["Mati Klarwein"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "santana_santana_iii",
        title: "Santana III",
        artist: "Santana",
        year: 1971,
        country: regions.USA,
        criteria: [criteria.JAM, criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.LATINO, criteria.TRANSITION],
        selectedTrackTitle: "Jungle Strut",
        selectedTrackYtId: "piOEO_0Ffp0",
        spotifyId: "3iE6Jik24CBE0uv1lyyplI",
        deezerId: "1373307",
        designers: ["Heavy Water Light Show", "Joan Chase", "Mary Ann Mayer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "santana_caravanserai",
        title: "Caravanserai",
        artist: "Santana",
        year: 1972,
        country: regions.USA,
        criteria: [criteria.CONCEPT, criteria.ODD_RHYTHM, criteria.INSTRUMENTAL, criteria.JAM, criteria.TRANSITION, criteria.AMBIENT, criteria.C_PSYCHE, criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.SPIRITUAL, criteria.UNCOMMON_INSTRUMENTS, criteria.LATINO],
        selectedTrackTitle: "Waves Within",
        selectedTrackYtId: "VGbSw8dHR3w",
        spotifyId: "0abfpuzzbTUNxasNmX04RU",
        deezerId: "1401719",
        designers: ["Joan Chase"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "santana_welcome",
        title: "Welcome",
        artist: "Santana",
        year: 1973,
        country: regions.USA,
        criteria: [criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.FEMALE, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Mother Africa",
        selectedTrackYtId: "1d-i_NacF9g",
        spotifyId: "0luB0sB15mLFitTOJqJJwT",
        deezerId: "7740338",
        designers: ["Randy Tuten"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "santana_borboletta",
        title: "Borboletta",
        artist: "Santana",
        year: 1974,
        country: regions.USA,
        criteria: [criteria.JAM, criteria.TRANSITION, criteria.UNCOMMON_INSTRUMENTS, criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.LATINO],
        selectedTrackTitle: "Canto De Los Flores",
        selectedTrackYtId: "vlWO_F2D2tw",
        spotifyId: "2SurTgYPtoCJSn7103Uuvk",
        deezerId: "111730",
        designers: ["Barry Imhoff", "Carlos Santana"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "schicke_fuhrs_and_frohling_symphonic_pictures",
        title: "Symphonic Pictures",
        artist: "Schicke, Führs & Fröhling",
        year: 1976,
        country: regions.GERMANY,
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: "Pictures",
        selectedTrackYtId: "xvnRkJdbm6w",
        spotifyId: "1Moy8pZZekoPN0Kow0t7o0",
        deezerId: "7648349",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "schicke_fuhrs_and_frohling_sunburst",
        title: "Sunburst",
        artist: "Schicke, Führs & Fröhling",
        year: 1977,
        country: regions.GERMANY,
        criteria: [criteria.ODD_RHYTHM, criteria.C_ELECTRO],
        selectedTrackTitle: "Troja",
        selectedTrackYtId: "1AfQ2w-fY40",
        spotifyId: "3oWKEuO0zzzfcZrKWI4Gqr",
        deezerId: "7576867",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO https://www.discogs.com/fr/master/254221-SFF-Ticket-To-Everywhere
    {
        id: "scorpions_lonesome_crow",
        title: "Lonesome Crow",
        artist: "Scorpions",
        year: 1972,
        country: regions.GERMANY,
        criteria: [criteria.C_PSYCHE, criteria.JAM],
        selectedTrackTitle: "Leave Me",
        selectedTrackYtId: "1ps2eyeVmXo",
        spotifyId: "22iTF02z2K23GPjUMrMNo3",
        deezerId: "394079",
        designers: [`Wandrey's`],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "scorpions_fly_to_the_rainbow",
        title: "Fly To The Rainbow",
        artist: "Scorpions",
        year: 1974,
        country: regions.GERMANY,
        criteria: [criteria.HEAVY, criteria.ROCK, criteria.JAM],
        selectedTrackTitle: "Fly To The Rainbow",
        selectedTrackYtId: "dGDefpjTqFY",
        spotifyId: "4Iu5d1damGtHlq9kQmXpQQ",
        deezerId: "121494",
        designers: [`Wandrey's`],
        similarAlbums: ["wishbone_ash_argus"],
        isAGem: false,
    },
    {
        id: "semiramis_dedicato_a_frazz",
        title: "Dedicato A Frazz",
        artist: "Semiramis",
        year: 1973,
        country: regions.ITALY,
        criteria: [criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.SYMPHONIC, criteria.SPECTACULAR, criteria.ITALIAN, criteria.BAROQUE, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Luna Park",
        selectedTrackYtId: "T2PVgfv0OR4",
        spotifyId: "0BWTfsFWL3TuBXZ2dBA7GV",
        deezerId: null,
        designers: ["Gordon Faggetter"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "serge_bulot_sanctuaire_deole",
        title: `Sanctuaire D'Éole`,
        artist: "Serge Bulot",
        year: 1980,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.JAM, criteria.C_FOLK, criteria.PATCHWORK, criteria.AMBIENT, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT],
        selectedTrackTitle: "Universalis",
        selectedTrackYtId: "sEcjrE_Spok",
        spotifyId: null,
        deezerId: null,
        designers: ["Jean-Pierre Plünder"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "serge_bulot_les_legendes_de_broceliande",
        title: `Les Légendes De Brocéliande`,
        artist: "Serge Bulot",
        year: 1981,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.JAM, criteria.C_FOLK, criteria.AMBIENT, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT],
        selectedTrackTitle: "Euryale",
        selectedTrackYtId: "9rEtF7kh_jI",
        spotifyId: null,
        deezerId: null,
        designers: ["Jacques Poirier"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "serge_gainsbourg_histoire_de_melody_nelson",
        title: "Histoire De Melody Nelson",
        artist: "Serge Gainsbourg",
        year: 1971,
        country: regions.FRANCE,
        criteria: [criteria.STORYLINE, criteria.CONCEPT, criteria.FRENCH, criteria.SOFT, criteria.ART_POP, criteria.ORCHESTRAL_PARTS, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Melody",
        selectedTrackYtId: "I3WeNexb2a8",
        spotifyId: "66Y8VrfvHnwJSk2ahGOr32",
        deezerId: "22233631",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "serge_gainsbourg_lhomme_a_tete_de_chou",
        title: `L'homme À Tête De Chou`,
        artist: "Serge Gainsbourg",
        year: 1976,
        country: regions.FRANCE,
        criteria: [criteria.STORYLINE, criteria.FRENCH, criteria.SOFT, criteria.ART_POP, criteria.BLENDS],
        selectedTrackTitle: `L'homme À Tête De Chou`,
        selectedTrackYtId: "BM8nWoPLmtA",
        spotifyId: "3gSi23G3zYYvIEBZwJTNEh",
        deezerId: "12494618",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "serge_ramses_secret",
        title: "Secret",
        artist: "Serge Ramses",
        year: 1978,
        country: regions.FRANCE,
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.AMBIENT, criteria.ELECTRO],
        selectedTrackTitle: "Secret",
        selectedTrackYtId: "3K0UOKOdDvE",
        spotifyId: null,
        deezerId: null,
        designers: ["Philippe Huart"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "session_unikuva",
        title: "Unikuva",
        artist: "Session",
        year: 1974,
        country: regions.FINLAND,
        criteria: [criteria.FEMALE, criteria.FINNISH, criteria.JAM, criteria.FANFARE],
        selectedTrackTitle: "Unikuva",
        selectedTrackYtId: "xe78PT1S_fM",
        spotifyId: null,
        deezerId: null,
        designers: ["Esa Kylliäinen"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sex_sex",
        title: "Sex",
        artist: "Sex",
        year: 1971,
        country: regions.QUEBEC,
        criteria: [criteria.ROCK, criteria.HEAVY, criteria.GREASY_SEVENTIES, criteria.JAM, criteria.BLUESY, criteria.C_PSYCHE],
        selectedTrackTitle: "Come, Wake Up!",
        selectedTrackYtId: "WnTGbs2Hj80",
        spotifyId: null,
        deezerId: null,
        designers: ["Pierre Casgrain"],
        similarAlbums: ["deep_purple_in_rock"],
        isAGem: false,
    },
    {
        id: "sex_the_end_of_my_life",
        title: "The End Of My Life",
        artist: "Sex",
        year: 1972,
        country: regions.QUEBEC,
        criteria: [criteria.ROCK, criteria.C_PSYCHE, criteria.JAM, criteria.BLUESY, criteria.UNCOMMON_INSTRUMENTS, criteria.SOUND_COLLAGES],
        selectedTrackTitle: "The End Of My Life",
        selectedTrackYtId: "gSsw8mbBS98",
        spotifyId: "2IO1biX4wzbUE6jDEsrKBH",
        deezerId: "532705412",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "shaa_khan_the_world_will_end_on_friday",
        title: "The World Will End On Friday",
        artist: "Shaa Khan",
        year: 1978,
        country: regions.GERMANY,
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.GREASY_SEVENTIES], // TODO
        selectedTrackTitle: "Graveyard",
        selectedTrackYtId: "FxmP-uXYlss",
        spotifyId: "2D8vjpXYAgQ08K7NOl1skn",
        deezerId: "383606",
        designers: ["Hartmut Noeller", "Gabriele Wichmann"],
        similarAlbums: [], // TODO wishbone ash
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "shaa_khan_anything_wrong",
        title: "Anything Wrong?",
        artist: "Shaa Khan",
        year: 1979,
        country: regions.GERMANY,
        criteria: [criteria.SOFT_SEVENTIES, criteria.C_ELECTRO, criteria.GLITTER, criteria.SYMPHONIC],
        selectedTrackTitle: "Tales Of Schroeder",
        selectedTrackYtId: "5j1OQWWfkhU",
        spotifyId: "1lcOUkdicpVTwV3fhndAjs",
        deezerId: "406664",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "shakti_natural_elements",
        title: "Natural Elements",
        artist: "Shakti",
        year: 1977,
        country: regions.INDIA,
        criteria: [criteria.CONCEPT, criteria.ODD_RHYTHM, criteria.TECHNICAL, criteria.INSTRUMENTAL, criteria.JAM, criteria.ORIENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.C_JAZZ, criteria.C_FOLK, criteria.SPIRITUAL],
        selectedTrackTitle: "Mind Ecology",
        selectedTrackYtId: "d_DajSHROJA",
        spotifyId: "05RPG1hN35ucYL4BqEBZdn",
        deezerId: "241263",
        designers: ["Paula Scher", "John Alcorn"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "shampoo_volume_one",
        title: "Volume One",
        artist: "Shampoo",
        year: 1971,
        country: regions.BELGIUM,
        criteria: [criteria.FANFARE, criteria.C_PSYCHE, criteria.SYMPHONIC, criteria.JAM, criteria.UNCOMMON_INSTRUMENTS, criteria.C_JAZZ, criteria.BAROQUE, criteria.JAZZY_GROOVY, criteria.FRENCH, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Some Reason",
        selectedTrackYtId: "5sBH3GZsSSo",
        spotifyId: null,
        deezerId: null,
        designers: ["Luk Rijckaert"],
        similarAlbums: [], // TODO recreation? atom heart mother? comus?
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "shark_move_ghede_chokras_shark_move",
        title: "Ghede Chokra's Shark Move",
        artist: "Shark Move",
        year: 1971,
        country: regions.INDONESIA,
        criteria: [criteria.JAM, criteria.GREASY_SEVENTIES, criteria.SYMPHONIC, criteria.INDONESIAN],
        selectedTrackTitle: `My Life`,
        selectedTrackYtId: "lJaLZvrQP1U",
        spotifyId: "7aaQ3SGyV6gbBZAlBJlI8D",
        deezerId: null,
        designers: ["Samantha Choq"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_shiver_walpurgis",
        title: "Walpurgis",
        artist: "The Shiver",
        year: 1969,
        country: regions.SWITZERLAND,
        criteria: [criteria.CRISPY_SIXTIES, criteria.C_PSYCHE, criteria.BAROQUE],
        selectedTrackTitle: `Don't Let Me Be Misunderstood`,
        selectedTrackYtId: "GeWSK4wy200",
        spotifyId: null,
        deezerId: null,
        designers: ["H.R. Giger"],
        similarAlbums: ["procol_harum_procol_harum"],
        isAGem: false,
    },
    {
        id: "show_of_hands_formerly_anthrax",
        title: "Formerly Anthrax",
        artist: "Show Of Hands",
        year: 1970,
        country: regions.USA,
        criteria: [criteria.C_JAZZ, criteria.JAZZY_GROOVY, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Moondance",
        selectedTrackYtId: "K-xU0NsSszc",
        spotifyId: "6f45LD92lhHJCOgvn17xez",
        deezerId: "511258",
        designers: ["Robert L. Heimall"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sir_lord_baltimore_kingdom_come",
        title: "Kingdom Come",
        artist: "Sir Lord Baltimore",
        year: 1970,
        country: regions.USA,
        criteria: [criteria.JAM, criteria.ROCK, criteria.HEAVY, criteria.OCCULT, criteria.GREASY_SEVENTIES],
        selectedTrackTitle: "Master Heartache",
        selectedTrackYtId: "wQSz64rU9mM",
        spotifyId: "0VfnxBAij0kKr71OK47BBW",
        deezerId: null,
        designers: ["Doug Taylor"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sky_king_secret_sauce",
        title: "Secret Sauce",
        artist: "Sky King",
        year: 1975,
        country: regions.USA,
        criteria: [criteria.JAM, criteria.ROCK, criteria.JAZZY_GROOVY, criteria.JAZZY_GROOVY, criteria.FEMALE],
        selectedTrackTitle: "Hot Mustard",
        selectedTrackYtId: "ectmDaKVMa4",
        spotifyId: null,
        deezerId: null,
        designers: ["Roger Huyssen"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sloche_jun_oeil",
        title: `J'un Oeil`,
        artist: "Sloche",
        year: 1975,
        country: regions.QUEBEC,
        criteria: [criteria.ODD_RHYTHM, criteria.INSTRUMENTAL, criteria.JAM, criteria.SYMPHONIC, criteria.C_PSYCHE, criteria.FRENCH, criteria.JAZZY_GROOVY],
        selectedTrackTitle: `J'un Oeil`,
        selectedTrackYtId: "Kng5yZJyMj0",
        spotifyId: null,
        deezerId: null,
        designers: ["Gaétan Desbiens"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sloche_stadacone",
        title: "Stadaconé",
        artist: "Sloche",
        year: 1976,
        country: regions.QUEBEC,
        criteria: [criteria.ODD_RHYTHM, criteria.INSTRUMENTAL, criteria.JAM, criteria.SYMPHONIC, criteria.C_PSYCHE, criteria.FRENCH, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Stadaconé",
        selectedTrackYtId: "GlkUhrk8MZg",
        spotifyId: null,
        deezerId: null,
        designers: ["Publiphoto"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "soft_machine_third",
        title: "Third",
        artist: "Soft Machine",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.EXPERIMENTAL, criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.C_ELECTRO, criteria.JAZZ],
        selectedTrackTitle: "Slightly All The Time",
        selectedTrackYtId: "4RwLgA9U_3I",
        spotifyId: "111J9nxmdhyHSLNHeAL1jO",
        deezerId: null,
        designers: ["John Hays"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "solaris_marsbeli_kronikak",
        title: "Marsbéli Krónikák",
        artist: "Solaris",
        year: 1984,
        country: regions.HUNGARY,
        criteria: [criteria.C_ELECTRO, criteria.HUNGARIAN, criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS],
        selectedTrackTitle: "Marsbéli Krónikák IV.-VI.",
        selectedTrackYtId: "L8W02LBnsaY",
        spotifyId: "6ylnpBYu7UG9OyJqvv8sVX",
        deezerId: null,
        designers: ["Herpai Zoltán"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "the_sound_express_the_sound_express",
        title: "The Sound Express",
        artist: "The Sound Express",
        year: 1969,
        country: regions.SWEDEN,
        criteria: [criteria.INSTRUMENTAL, criteria.JAM, criteria.ROCK],
        selectedTrackTitle: "Ebb Och Flod",
        selectedTrackYtId: "iu4s2Y7kHFU",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "space_magic_fly",
        title: "Magic Fly",
        artist: "Space",
        year: 1977,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.FEMALE, criteria.SCI_FI],
        selectedTrackTitle: "Fasten Seat Belt",
        selectedTrackYtId: "yBJMbdE_fdM",
        spotifyId: "5aSkXF27XnK6qPVMNO0NeW",
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "space_deliverance",
        title: "Deliverance",
        artist: "Space",
        year: 1977,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.FEMALE],
        selectedTrackTitle: "Let Me Know The Wonder",
        selectedTrackYtId: "Of0CYYFASPY",
        spotifyId: "6mjB5F4RuGPCDOPdKrCDg4",
        deezerId: null,
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "space_just_blue",
        title: "Just Blue",
        artist: "Space",
        year: 1978,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.FEMALE, criteria.GLITTER, criteria.NEO_EIGHTIES, criteria.TRANSITION],
        selectedTrackTitle: "Secret Dreams",
        selectedTrackYtId: "0vuf3_omJhU",
        spotifyId: "6NELSAcWDWUrezRASIHE2c",
        deezerId: null,
        designers: ["Gribbitt!", "Henry Vizcarra", "Shusei Nagaoka", "Bernard Monié"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "space_deeper_zone",
        title: "Deeper Zone",
        artist: "Space",
        year: 1980,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.FEMALE, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "Deeper Zone",
        selectedTrackYtId: "-7IME_3lsgc",
        spotifyId: "5mOp4lqK68kw3HJX0vzq4M",
        deezerId: null,
        designers: ["Bernard Monié"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spin_spin",
        title: "Spin",
        artist: "Spin",
        year: 1976,
        country: regions.NETHERLANDS,
        criteria: [criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.JAM, criteria.C_JAZZ, criteria.UNCOMMON_INSTRUMENTS, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Excenter",
        selectedTrackYtId: "PrvlV1YfUSk",
        spotifyId: null,
        deezerId: null,
        designers: ["Chris Duinmeijer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spin_whirlwind",
        title: "Whirlwind",
        artist: "Spin",
        year: 1977,
        country: regions.NETHERLANDS,
        criteria: [criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.JAM, criteria.C_JAZZ, criteria.UNCOMMON_INSTRUMENTS, criteria.ODD_RHYTHM, criteria.SOFT_SEVENTIES, criteria.FEMALE, criteria.C_ELECTRO],
        selectedTrackTitle: "Telegraphcanyon-Roadrunner",
        selectedTrackYtId: "qz2LPVPNX00",
        spotifyId: "41tLQIgcDq4JsAenZCJsRO",
        deezerId: "13472843",
        designers: ["Chris Duinmeijer"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spirit_spirit",
        title: "Spirit",
        artist: "Spirit",
        year: 1968,
        country: regions.USA,
        criteria: [criteria.C_PSYCHE, criteria.C_FOLK, criteria.SOFT, criteria.C_JAZZ, criteria.UNCOMMON_INSTRUMENTS, criteria.BAROQUE],
        selectedTrackTitle: "Taurus",
        selectedTrackYtId: "xd8AVbwB_6E",
        spotifyId: "3TX6HT0emzfmlwsiMpE9CX",
        deezerId: "113484",
        designers: ["Corporate Head", "Guy Webster"],
        similarAlbums: ["the_beatles_revolver"],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "spirit_the_family_that_plays_together",
        title: "The Family That Plays Together",
        artist: "Spirit",
        year: 1968,
        country: regions.USA,
        criteria: [criteria.C_PSYCHE, criteria.C_FOLK, criteria.SOFT, criteria.TRANSITION, criteria.BAROQUE],
        selectedTrackTitle: "It SHall Be",
        selectedTrackYtId: "PlHnu3_Kgkc",
        spotifyId: "5zwKg5QUnSfQwkJqfl5cWs",
        deezerId: "112893",
        designers: ["Guy Webster"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spirit_clear",
        title: "Clear",
        artist: "Spirit",
        year: 1969,
        country: regions.USA,
        criteria: [criteria.C_PSYCHE, criteria.ROCK],
        selectedTrackTitle: "Clear",
        selectedTrackYtId: "qpN8xfRFc6k",
        spotifyId: "6u7hh9AVnf4X0HLaZVKo38",
        deezerId: "112732",
        designers: ["Guy Webster"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spirit_twelve_dreams_of_dr_sardonicus",
        title: "Twelve Dream Of Dr. Sardonicus",
        artist: "Spirit",
        year: 1970,
        country: regions.USA,
        criteria: [criteria.C_PSYCHE, criteria.ART_POP],
        selectedTrackTitle: "Space Child",
        selectedTrackYtId: "jpAx5VqzzUo",
        spotifyId: "0NWXyLhHhaeAmu4eovC8Ks",
        deezerId: "112731",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spirogyra_st_radigunds",
        title: "St. Radigunds",
        artist: "Spirogyra",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.FOLK, criteria.FEMALE],
        selectedTrackTitle: "The Duke Of Beaufoot",
        selectedTrackYtId: "D1jNLR9tjXE",
        spotifyId: "5JhbxkXzy1o2RcX14CCwZP",
        deezerId: "671887",
        designers: ["Penny Graeme-Barber", "Pete Rhodes"],
        similarAlbums: ["comus_first_utterance"],
        isAGem: false,
    },
    {
        id: "spirogyra_old_boot_wine",
        title: "Old Boot Wine",
        artist: "Spirogyra",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.FOLK, criteria.FEMALE],
        selectedTrackTitle: "A Canterbury Tale",
        selectedTrackYtId: "o7Z5SIYACAU",
        spotifyId: "7dlDI9sU90DvAJKwaQYGRj",
        deezerId: "67021732",
        designers: ["Pete Rhodes"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spirogyra_bells_boots_and_shambles",
        title: "Bells, Boots And Shambles",
        artist: "Spirogyra",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.FOLK, criteria.FEMALE],
        selectedTrackTitle: "Old Boot Wine",
        selectedTrackYtId: "-Q0rh2uESWY",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spontaneous_combustion_spontaneous_combustion",
        title: "Spontaneous Combustion",
        artist: "Spontaneous Combustion",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.HUMBLE, criteria.C_PSYCHE],
        selectedTrackTitle: "Reminder",
        selectedTrackYtId: "T5ZFr3pV5hM",
        spotifyId: "3IMqxLOXh5FI45nVed8bln",
        deezerId: "302666",
        designers: ["Paul May"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spontaneous_combustion_triad",
        title: "Triad",
        artist: "Spontaneous Combustion",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.C_ELECTRO],
        selectedTrackTitle: "Pan",
        selectedTrackYtId: "mqwTKKwE7MQ",
        spotifyId: "0ydD7INyGyCIpCa6zLzkIY",
        deezerId: "302667",
        designers: ["Paul May"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "spring_spring",
        title: "Spring",
        artist: "Spring",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.GLITTER, criteria.ROCK, criteria.SOFT, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.BAROQUE],
        selectedTrackTitle: "Golden Fleece",
        selectedTrackYtId: "BuP9_sMgu8I",
        spotifyId: "1GX1Mo7djCEq2ZAM2pokGR",
        deezerId: "77355512",
        designers: ["Marcus Keef"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "starcastle_starcastle",
        title: "Starcastle",
        artist: "Starcastle",
        year: 1976,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.GLITTER, criteria.C_ELECTRO, criteria.SPECTACULAR, criteria.FANTASY],
        selectedTrackTitle: "Elliptical Seasons",
        selectedTrackYtId: "sSZepYc219Y",
        spotifyId: "1fxW4E9zQ5RIIc4k1aPZRy",
        deezerId: "115523",
        designers: ["Alex Ebel"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "starcastle_fountains_of_light",
        title: "Fountains Of Light",
        artist: "Starcastle",
        year: 1977,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.GLITTER, criteria.C_ELECTRO, criteria.SPECTACULAR, criteria.FANTASY],
        selectedTrackTitle: "Silver Winds",
        selectedTrackYtId: "0tmM4X3HnDk",
        spotifyId: "6ZtNHnRzacahYX1NeHxiU0",
        deezerId: "4575171",
        designers: ["Peter Lloyd"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "starcastle_citadel",
        title: "Citadel",
        artist: "Starcastle",
        year: 1977,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.GLITTER, criteria.C_ELECTRO, criteria.SPECTACULAR, criteria.FANTASY],
        selectedTrackTitle: "Wings Of White",
        selectedTrackYtId: "Z8qyuL_wpXQ",
        spotifyId: "6r7XlOEXPFtVrJy4mTi0eP",
        deezerId: "897881",
        designers: ["Hildebrandt"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stefano_testa_una_vita_una_balena_bianca_e_altre_cose",
        title: "Una Vita, Una Balena Bianca E Altre Cose",
        artist: "Stefano Testa",
        year: 1977,
        country: regions.ITALY,
        criteria: [criteria.LENGTHY_TRACKS, criteria.FOLK, criteria.ITALIAN, criteria.SOFT_SEVENTIES, criteria.UNCOMMON_INSTRUMENTS, criteria.SYMPHONIC, criteria.ORCHESTRAL_PARTS],
        selectedTrackTitle: "Una Vita",
        selectedTrackYtId: "X0oLlTCGQDg",
        spotifyId: "0e7a5sPggzXsOt5P6hps0x",
        deezerId: "6719345",
        designers: [],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "step_ahead_step_ahead",
        title: "Step Ahead",
        artist: "Step Ahead",
        year: 1982,
        country: regions.FRANCE,
        criteria: [criteria.SYMPHONIC, criteria.GLITTER, criteria.C_ELECTRO, criteria.SPECTACULAR, criteria.HEAVY],
        selectedTrackTitle: "Eyes",
        selectedTrackYtId: "BwMwvVe0c1U",
        spotifyId: null,
        deezerId: null,
        designers: ["Michel Sinier"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "steps_fr_steps",
        title: "Steps",
        artist: "Steps (FR)",
        year: 1977,
        country: regions.FRANCE,
        criteria: [criteria.JAZZ, criteria.INSTRUMENTAL, criteria.C_ELECTRO, criteria.SOFT_SEVENTIES, criteria.ODD_RHYTHM, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Wolves",
        selectedTrackYtId: "todo",
        spotifyId: null,
        deezerId: null,
        designers: ["Mati Klarwein", "Albion Studios", "Jon Tatlow"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_hackett_voyage_of_the_acolyte",
        title: "Voyage Of The Acolyte",
        artist: "Steve Hackett",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.SYMPHONIC, criteria.ODD_RHYTHM, criteria.C_ELECTRO, criteria.TECHNICAL, criteria.SOUND_COLLAGES, criteria.FEMALE, criteria.BAROQUE, criteria.C_FOLK],
        selectedTrackTitle: "Ace Of Wands",
        selectedTrackYtId: "EGu0JhYjRmo",
        spotifyId: "4twSmtePdvfZhSpI2LV5W2",
        deezerId: "301455",
        designers: ["Kim Poor"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "steve_hackett_please_dont_touch",
        title: "Please Don't Touch!",
        artist: "Steve Hackett",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.SYMPHONIC, criteria.ODD_RHYTHM, criteria.BLENDS, criteria.FEMALE, criteria.TRANSITION],
        selectedTrackTitle: "The Voice Of Necam",
        selectedTrackYtId: "ME4tI0Llr-Q",
        spotifyId: "7vg8S93YqrTLgIlEovhqdD",
        deezerId: "311228",
        designers: ["Kim Poor"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_hackett_spectral_mornings",
        title: "Spectral Mornings",
        artist: "Steve Hackett",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.BLENDS, criteria.ODD_RHYTHM, criteria.JAM, criteria.GLITTER, criteria.SYMPHONIC],
        selectedTrackTitle: "Spectral Mornings",
        selectedTrackYtId: "sYSV5iiSajw",
        spotifyId: "3JL21NegF3SeQsuqPdmMNN",
        deezerId: "311226",
        designers: ["Kim Poor"],
        similarAlbums: [],
        isAGem: false, // TODO almost gem
    },
    {
        id: "steve_hackett_defector",
        title: "Defector",
        artist: "Steve Hackett",
        year: 1980,
        country: regions.ENGLAND,
        criteria: [criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.ODD_RHYTHM, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "The Steppes",
        selectedTrackYtId: "B4SwHDD6wzA",
        spotifyId: "0nECUKmdMX4suPNyJ1oLWo",
        deezerId: "301488",
        designers: ["Kim Poor", "Kobz"],
        similarAlbums: ["camel_nude"],
        isAGem: false,
    },
    {
        id: "steve_hackett_cured",
        title: "Cured",
        artist: "Steve Hackett",
        year: 1981,
        country: regions.ENGLAND,
        criteria: [criteria.GLITTER, criteria.ART_POP, criteria.NEO_EIGHTIES, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Overnight Sleeper",
        selectedTrackYtId: "DhQE07j5D8s",
        spotifyId: "3OwlB212tbg6YhJSnPIFU7",
        deezerId: "311227",
        designers: ["Kim Poor"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_hackett_highly_strung",
        title: "Highly Strung",
        artist: "Steve Hackett",
        year: 1983,
        country: regions.ENGLAND,
        criteria: [criteria.NEO_EIGHTIES, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Camino Royale",
        selectedTrackYtId: "H8s9x1BbM_E",
        spotifyId: "7myTu4A3SH8HTGhIuuZFDW",
        deezerId: "311229",
        designers: ["Kim Poor"],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO Steve Hackett - Till We Have Faces PROG? - 1984 - uncommon, neoeighties, instru, c_elecotr, artpop - track What's My Name
    // TODO Steve Hackett - Guitar Noir PROG?
    {
        id: "steve_hillage_fish_rising",
        title: "Fish Rising",
        artist: "Steve Hillage",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.SYMPHONIC, criteria.LENGTHY_TRACKS, criteria.UNCOMMON_INSTRUMENTS, criteria.C_JAZZ, criteria.C_PSYCHE, criteria.SOUND_COLLAGES, criteria.FEMALE, criteria.SPACY],
        selectedTrackTitle: "Solar Musick Suite",
        selectedTrackYtId: "oBhRWkJAK7A",
        spotifyId: "2IfufXMgO8WKAIEeyNbzoY",
        deezerId: "300735",
        designers: ["Steve Hillage"],
        similarAlbums: [],
        isAGem: false, // TODO almost a gem! réécouter
    },
    {
        id: "steve_hillage_l",
        title: "L",
        artist: "Steve Hillage",
        year: 1976,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS, criteria.SPACY, criteria.JAM, criteria.ORIENTAL, criteria.SANSKRIT],
        selectedTrackTitle: "Hurdy Gurdy Glissando",
        selectedTrackYtId: "Q7x445IVnO8",
        spotifyId: "6md4UCQW2J1NvtB0NRXlhE",
        deezerId: "311187",
        designers: ["Ken Dolman", "Clayton Kenny"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_hillage_motivation_radio",
        title: "Motivation Radio",
        artist: "Steve Hillage",
        year: 1977,
        country: regions.ENGLAND,
        criteria: [criteria.C_ELECTRO, criteria.C_PSYCHE, criteria.FEMALE, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Octave Doctors",
        selectedTrackYtId: "KAx51sNo66Q",
        spotifyId: "2aFvgS5URiWVsd6mdB0mtZ",
        deezerId: "300733",
        designers: ["Bob Cato"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_hillage_green",
        title: "Green",
        artist: "Steve Hillage",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.C_ELECTRO, criteria.TRANSITION, criteria.JAZZY_GROOVY, criteria.SPACY, criteria.JAM, criteria.ODD_RHYTHM],
        selectedTrackTitle: "The Glorious Om Riff",
        selectedTrackYtId: "k6n95J5Jggo",
        spotifyId: "3EiyPffQse15BhPxfOYN0r",
        deezerId: "311117",
        designers: [],
        similarAlbums: ["ozric_tentacles_pungent_effulgent"],
        isAGem: false,
    },
    {
        id: "steve_hillage_rainbow_dome_musik",
        title: "Rainbow Dome Musick",
        artist: "Steve Hillage",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.LENGTHY_TRACKS, criteria.SOUND_COLLAGES, criteria.AMBIENT, criteria.ELECTRO, criteria.INSTRUMENTAL],
        selectedTrackTitle: "Garden Of Paradise",
        selectedTrackYtId: "LTa5i2wlE_w",
        spotifyId: "4g631XQPF1MQrY5znRrc8D",
        deezerId: "300731",
        designers: ["Rupert Atwill"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_hillage_open",
        title: "Open",
        artist: "Steve Hillage",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.ELECTRO, criteria.SOFT_SEVENTIES, criteria.FEMALE],
        selectedTrackTitle: "Earthrise",
        selectedTrackYtId: "r728Ur3Y7zw",
        spotifyId: "7IQmMQ0UUEmweEGfd9qRjZ",
        deezerId: "311161",
        designers: ["Simon Ryan"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_howe_beginnings",
        title: "Beginnings",
        artist: "Steve Howe",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.SOPHISTICATED, criteria.ODD_RHYTHM, criteria.UNCOMMON_INSTRUMENTS, criteria.BAROQUE, criteria.BLENDS, criteria.ORCHESTRAL_PARTS],
        selectedTrackTitle: "The Nature Of The Sea",
        selectedTrackYtId: "ZSb9s8E5rtU",
        spotifyId: "5iBOpddHTKZlap604IMKGY",
        deezerId: "1315730",
        designers: ["Roger Dean"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_howe_the_steve_howe_album",
        title: "The Steve Howe Album",
        artist: "Steve Howe",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.SOPHISTICATED, criteria.UNCOMMON_INSTRUMENTS, criteria.BLENDS, criteria.FEMALE],
        selectedTrackTitle: `All's A Chord`,
        selectedTrackYtId: "Q3hMVdwJVRg",
        spotifyId: "6TI6gnnePvPEYRUMW6z6d5",
        deezerId: null,
        designers: ["Roger Dean"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_howe_turbulence",
        title: "Turbulence",
        artist: "Steve Howe",
        year: 1991,
        country: regions.ENGLAND,
        criteria: [criteria.NEO_EIGHTIES, criteria.INSTRUMENTAL, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: `The Inner Battle`,
        selectedTrackYtId: "7ZGpZkOQYl8",
        spotifyId: "2C2eSBa3plc2Xm4AmdKowj",
        deezerId: "93386522",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_howe_the_grand_scheme_of_things",
        title: "The Grand Scheme Of Things",
        artist: "Steve Howe",
        year: 1993,
        country: regions.ENGLAND,
        criteria: [criteria.NEO_EIGHTIES, criteria.C_FOLK, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Wayward Course`,
        selectedTrackYtId: "7Jm0P91dsME",
        spotifyId: "3s9Mhhq6813cvaLztBm11E",
        deezerId: "57912992",
        designers: ["Roger Dean"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "steve_vai_flexable",
        title: "Flex-Able",
        artist: "Steve Vai",
        year: 1984,
        country: regions.USA,
        criteria: [criteria.FUNNY, criteria.ODD_RHYTHM, criteria.NEO_EIGHTIES, criteria.BLENDS, criteria.TECHNICAL, criteria.FEMALE, criteria.UNCOMMON_INSTRUMENTS, criteria.C_PSYCHE],
        selectedTrackTitle: "Lovers Are Crazy",
        selectedTrackYtId: "Hmx661gfQoY",
        spotifyId: "6XtKxID8KuVRBlszv7sy3D",
        deezerId: "112818",
        designers: ["Raul G. Gonzalez"],
        similarAlbums: ["frank_zappa_tinsel_town_rebellion"],
        isAGem: false,
    },
    {
        id: "still_life_still_life",
        title: "Still Life",
        artist: "Still Life",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.JAM, criteria.SPECTACULAR],
        selectedTrackTitle: "Dreams",
        selectedTrackYtId: "cHV3_9d53h0",
        spotifyId: "2gudEqaUK3petkEd23ZIT0",
        deezerId: "73309362",
        designers: ["Design Machine"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stomu_yamashta_red_buddha",
        title: "Red Buddha",
        artist: "Stomu Yamash'ta",
        year: 1971,
        country: regions.JAPAN,
        criteria: [criteria.EXPERIMENTAL, criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.INSTRUMENTAL],
        selectedTrackTitle: "Red Buddha",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stomu_yamashta_the_man_from_the_east",
        title: "The Man From The East",
        artist: "Stomu Yamash'ta",
        year: 1973,
        country: regions.JAPAN,
        criteria: [criteria.SOUNDTRACK, criteria.JAPANESE, criteria.FUNNY, criteria.UNCOMMON_INSTRUMENTS, criteria.C_PSYCHE, criteria.FEMALE],
        selectedTrackTitle: "Mandala",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stomu_yamashta_raindog",
        title: "Raindog",
        artist: "Stomu Yamash'ta",
        year: 1975,
        country: regions.JAPAN,
        criteria: [criteria.C_JAZZ, criteria.LENGTHY_TRACKS, criteria.JAZZY_GROOVY, criteria.FEMALE, criteria.UNCOMMON_INSTRUMENTS, criteria.C_PSYCHE],
        selectedTrackTitle: "Dunes",
        selectedTrackYtId: "t07pRDg4-Dw",
        spotifyId: null,
        deezerId: null,
        designers: ["Eckford / Stimpson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stomu_yamashta_and_come_to_the_edge_floating_music",
        title: "Floating Music",
        artist: "Stomu Yamash'ta & Come To The Edge",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.INSTRUMENTAL, criteria.C_JAZZ, criteria.UNCOMMON_INSTRUMENTS, criteria.ODD_RHYTHM],
        selectedTrackTitle: "Poker Dice",
        selectedTrackYtId: "Mb-opDfWG1Y",
        spotifyId: "1b7AkqqqOfXLCcV1scpK5g",
        deezerId: null,
        designers: ["Gakutei"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stomu_yamashtas_east_wind_freedom_is_frightening",
        title: "Freedom Is Frightening",
        artist: "Stomu Yamash'ta's East Wind",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.C_ELECTRO, criteria.INSTRUMENTAL, criteria.JAM, criteria.ODD_RHYTHM, criteria.FEMALE, criteria.C_JAZZ],
        selectedTrackTitle: "Rolling Nuns",
        selectedTrackYtId: "FZD7Yu1wXz4",
        spotifyId: null,
        deezerId: null,
        designers: ["Saul Bass"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stomu_yamashtas_east_wind_one_by_one",
        title: "One By One",
        artist: "Stomu Yamash'ta's East Wind",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.SOUNDTRACK, criteria.C_JAZZ, criteria.JAM, criteria.JAZZY_GROOVY, criteria.C_PSYCHE, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS, criteria.BAROQUE, criteria.ODD_RHYTHM],
        selectedTrackTitle: "One By One / Hey Man",
        selectedTrackYtId: "VWQSwDTIx_4",
        spotifyId: null,
        deezerId: null,
        designers: ["Albion Studios", "Mick Rock"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stomu_yamashtas_go_go",
        title: "Go",
        artist: "Stomu Yamash'ta's Go",
        year: 1976,
        country: regions.ENGLAND,
        criteria: [criteria.ORCHESTRAL_PARTS, criteria.TRANSITION, criteria.NEO_EIGHTIES, criteria.C_ELECTRO, criteria.FEMALE, criteria.JAM, criteria.C_PSYCHE],
        selectedTrackTitle: "Nature",
        selectedTrackYtId: "c9IjpEXZ4kw",
        spotifyId: null,
        deezerId: null,
        designers: ["Saul Bass"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stomu_yamashtas_go_go_too",
        title: "Go Too",
        artist: "Stomu Yamash'ta's Go",
        year: 1977,
        country: regions.ENGLAND,
        criteria: [criteria.C_ELECTRO, criteria.TRANSITION, criteria.C_JAZZ, criteria.JAM, criteria.FEMALE, criteria.JAZZY_GROOVY, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Seen You Before",
        selectedTrackYtId: "VfX5Q3sWNos",
        spotifyId: "2211TLOo9BTlQMrRIzSybG",
        deezerId: "4014801",
        designers: ["Saul Bass"],
        similarAlbums: [], // TODO similar george duke
        isAGem: false,
    },
    {
        id: "the_storm_the_storm",
        title: "The Storm",
        artist: "The Storm",
        year: 1974,
        country: regions.SPAIN,
        criteria: [criteria.HEAVY, criteria.ROCK, criteria.JAM],
        selectedTrackTitle: "Crazy Machine",
        selectedTrackYtId: "6tHgkW2m-9g",
        spotifyId: null,
        deezerId: "52939772",
        designers: [],
        similarAlbums: ["deep_purple_who_do_we_think_we_are", "atomic_rooster_in_hearing_of_atomic_rooster"],
        isAGem: false,
    },
    {
        id: "strawbs_strawbs",
        title: "Strawbs",
        artist: "Strawbs",
        year: 1969,
        country: regions.ENGLAND,
        criteria: [criteria.FOLK, criteria.SOUND_COLLAGES, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT, criteria.BAROQUE, criteria.ORIENTAL],
        selectedTrackTitle: "That Which Once Was Mine",
        selectedTrackYtId: "Q08ZvJVT9Ww",
        spotifyId: "0cr57UBz01CRby5CoWnnhA",
        deezerId: "109414",
        designers: ["Tom Wilkes"],
        similarAlbums: ["the_incredible_string_band_the_5000_spirits_or_the_layers_of_the_onion"],
        isAGem: false,
    },
    {
        id: "strawbs_dragonfly",
        title: "Dragonfly",
        artist: "Strawbs",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.FOLK, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT, criteria.BAROQUE, criteria.ORIENTAL],
        selectedTrackTitle: "The Vision Of The Lady Of The Lake",
        selectedTrackYtId: "EKjbVzGuCNU",
        spotifyId: "50c9VqWI2sLJtByN0hrzo3",
        deezerId: "6156024",
        designers: ["Roger Saunders"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strawbs_just_a_collection_of_antiques_and_curios",
        title: "Just A Collection Of Antiques And Curios",
        artist: "Strawbs",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.LIVE, criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT, criteria.BAROQUE, criteria.ORIENTAL],
        selectedTrackTitle: "The Antique Suite",
        selectedTrackYtId: "C4WtzQw_LME",
        spotifyId: "4HlO9kW2BJ3M9aTqOkM7DF",
        deezerId: "123096",
        designers: ["Roger Saunders"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strawbs_from_the_witchwood",
        title: "From The Witchwood",
        artist: "Strawbs",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.FOLK, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT, criteria.BAROQUE],
        selectedTrackTitle: "Flight",
        selectedTrackYtId: "MeMDp9-jDQs",
        spotifyId: "2yqVIoYAgSnupSUuQVaYX0",
        deezerId: "230184",
        designers: ["Roger Saunders"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strawbs_grave_new_world",
        title: "Grave New World",
        artist: "Strawbs",
        year: 1972,
        country: regions.ENGLAND,
        criteria: [criteria.C_FOLK, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS, criteria.SPECTACULAR, criteria.TOUCHING_VOCALS],
        selectedTrackTitle: "New World",
        selectedTrackYtId: "MwMwMawCu0E",
        spotifyId: "1u024OvEmklRfbLGDxEWnf",
        deezerId: "228407",
        designers: ["William Blake", "Paper Tiger"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strawbs_bursting_at_the_seams",
        title: "Bursting At The Seams",
        artist: "Strawbs",
        year: 1973,
        country: regions.ENGLAND,
        criteria: [criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.SPECTACULAR, criteria.TOUCHING_VOCALS, criteria.ORCHESTRAL_PARTS],
        selectedTrackTitle: "Tears And Pavan",
        selectedTrackYtId: "tqhnoFu8urc",
        spotifyId: "1qEiYH6MnhGJRBidGcmpE0",
        deezerId: "103822",
        designers: ["John McConnell"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strawbs_hero_and_heroine",
        title: "Hero And Heroine",
        artist: "Strawbs",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.C_FOLK, criteria.TOUCHING_VOCALS, criteria.SOFT, criteria.ODD_RHYTHM, criteria.C_ELECTRO, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "Autumn",
        selectedTrackYtId: "bJaGE4GSCfQ",
        spotifyId: "1L0xniy2sSr8SfM8sD7rdJ",
        deezerId: "162164",
        designers: ["Mike Doud"],
        similarAlbums: [], // TODO similar acqua fragile
        isAGem: false,
    },
    {
        id: "strawbs_ghosts",
        title: "Ghosts",
        artist: "Strawbs",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.C_FOLK, criteria.SOFT, criteria.C_ELECTRO],
        selectedTrackTitle: "Ghosts",
        selectedTrackYtId: "QDBDmLcMgwU",
        spotifyId: "6ivHkiqHZ2HzIhKU6DsLbS",
        deezerId: "162165",
        designers: ["Bill Dare"],
        similarAlbums: [], // TODO similar acqua fragile
        isAGem: false,
    },
    {
        id: "strawbs_nomadness",
        title: "Nomadness",
        artist: "Strawbs",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.PIANO, criteria.C_FOLK],
        selectedTrackTitle: "A Mind Of My Own",
        selectedTrackYtId: "UrLImQl6aAY",
        spotifyId: "7Df8sasgLer1b3zbdtW2Wz",
        deezerId: "160606",
        designers: ["Nick Marshall"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strawbs_deep_cuts",
        title: "Deep Cuts",
        artist: "Strawbs",
        year: 1976,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.C_FOLK],
        selectedTrackTitle: "Turn Me Around",
        selectedTrackYtId: "or1ZcLeehQw",
        spotifyId: "6jLSwipNKPUcMBcCqOlWn0",
        deezerId: "74115372",
        designers: ["Paul May", "Mike Doud"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strawbs_burning_for_you",
        title: "Burning For You",
        artist: "Strawbs",
        year: 1977,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.C_FOLK, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "Alexander The Great",
        selectedTrackYtId: "Uf-syFYORIk",
        spotifyId: "0OkQLOJbTEyumrfBWuJIkS",
        deezerId: "74115512",
        designers: ["Patrick Woodroffe"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strawbs_deadlines",
        title: "Deadlines",
        artist: "Strawbs",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.C_ELECTRO],
        selectedTrackTitle: "Words Of Wisdom",
        selectedTrackYtId: "IiSdwjUdlLE",
        spotifyId: "5kVG8NbTqSI1QvL7ArEQN0",
        deezerId: "130617372",
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "strongbow_strongbow",
        title: "Strongbow",
        artist: "Strongbow",
        year: 1975,
        country: regions.USA,
        criteria: [criteria.GLITTER, criteria.JAM, criteria.C_ELECTRO, criteria.GREASY_SEVENTIES],
        selectedTrackTitle: "Sister Sea",
        selectedTrackYtId: "QkQ9HJYsXyg",
        spotifyId: "6SLoOUux0WZV7NVjmKSKCU",
        deezerId: "103465592",
        designers: ["Milton Sincoff", "Martin Gulser"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stud_stud",
        title: "Stud",
        artist: "Stud",
        year: 1971,
        country: regions.NORTHERN_IRELAND,
        criteria: [criteria.C_FOLK, criteria.JAM, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Horizon",
        selectedTrackYtId: "cqCWn9FV-84",
        spotifyId: "6r7XlOEXPFtVrJy4mTi0eP",
        deezerId: null,
        designers: ["Anne Marie Anderson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "stud_september",
        title: "September",
        artist: "Stud",
        year: 1972,
        country: regions.NORTHERN_IRELAND,
        criteria: [criteria.FOLK, criteria.JAM, criteria.JAZZY_GROOVY, criteria.SOFT],
        selectedTrackTitle: "Samurai",
        selectedTrackYtId: "j72O14jFDGQ",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sunhouse_sunhouse",
        title: "Sunhouse",
        artist: "Sunhouse",
        year: 1977,
        country: regions.BELGIUM,
        criteria: [criteria.INSTRUMENTAL, criteria.JAM, criteria.SOFT, criteria.C_JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: `Don't Skimp With Us`,
        selectedTrackYtId: "1ABQLe-KfEo",
        spotifyId: null,
        deezerId: null,
        designers: ["Anne-Catherine Gerbaud"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "supertramp_supertramp",
        title: "Supertramp",
        artist: "Supertramp",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.JAM, criteria.SOFT, criteria.ROCK, criteria.ART_POP],
        selectedTrackTitle: "Words Unspoken",
        selectedTrackYtId: null,
        spotifyId: "3ma2d5Gk3oc9ffDTT3fOeF",
        deezerId: "245820",
        designers: ["Bob Hook"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "supertramp_indelibly_stamped",
        title: "Indelibly Stamped",
        artist: "Supertramp",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.ROCK, criteria.ART_POP, criteria.PIANO],
        selectedTrackTitle: "Travelled",
        selectedTrackYtId: "OzihNqVYElA",
        spotifyId: "1YTdN3xvwgVdkdKZq6jMH3",
        deezerId: "122946",
        designers: ["Keith Morris", "Bob Hook"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "supertramp_crime_of_the_century",
        title: "Crime Of The Century",
        artist: "Supertramp",
        year: 1974,
        country: regions.ENGLAND,
        criteria: [criteria.CONCEPT, criteria.SOFT, criteria.BLENDS, criteria.C_JAZZ, criteria.ROCK_OPERA, criteria.TOUCHING_VOCALS, criteria.ART_POP, criteria.SOFT_SEVENTIES, criteria.PIANO],
        selectedTrackTitle: "Rudy",
        selectedTrackYtId: "gxW3s_Qk1dk",
        spotifyId: "2wrHaulTgqqkVKx0k7Kq4r",
        deezerId: "9205657",
        designers: ["Paul Wakefield"],
        similarAlbums: [],
        isAGem: true,
        description: `Rick Davies and Roger Hodgson composed heavy-hearted songs to create one of the most subtle, most magnificient, most moving albums we could imagine, with intense vocals and lyrics as desperate as the cover. The album is a theater of unregular song structures and piano-driven melodies, where the other instruments complete parts here and there so that almost every song is a climax itself.`,
    },
    {
        id: "supertramp_crisis_what_crisis",
        title: "Crisis? What Crisis?",
        artist: "Supertramp",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.TOUCHING_VOCALS, criteria.ART_POP, criteria.SOFT_SEVENTIES, criteria.ORCHESTRAL_PARTS, criteria.PIANO],
        selectedTrackTitle: `Another Man's Woman`,
        selectedTrackYtId: "MUPwN0MtY1Y",
        spotifyId: "5Fliz4RQcDktb93l1uYDka",
        deezerId: "224594",
        designers: ["Richard Davies", "Dick Ward", "Fabio Nicoli", "Paul Wakefield"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "supertramp_even_in_the_quietest_moments",
        title: "Even In The Quietest Moments",
        artist: "Supertramp",
        year: 1977,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.TOUCHING_VOCALS, criteria.ART_POP, criteria.SOFT_SEVENTIES, criteria.PIANO],
        selectedTrackTitle: "Even In The Quietest Moments",
        selectedTrackYtId: "7CXcMPdVXp4",
        spotifyId: "4X87hQ57jTYQTcYTaJWK5w",
        deezerId: "103251",
        designers: ["Mike Doud"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "supertramp_breakfast_in_america",
        title: "Breakfast In America",
        artist: "Supertramp",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.TOUCHING_VOCALS, criteria.ART_POP, criteria.SOFT_SEVENTIES, criteria.PIANO],
        selectedTrackTitle: "Child Of Vision",
        selectedTrackYtId: "HlqoYPR9G7w",
        spotifyId: "29B5sIbYPnSjJaD5CloPjf",
        deezerId: "653085",
        designers: ["Mike Doud", "Mick Haggerty"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "supertramp_famous_last_words",
        title: "...Famous Last Words...",
        artist: "Supertramp",
        year: 1982,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.TOUCHING_VOCALS, criteria.ART_POP, criteria.SOFT_SEVENTIES, criteria.PIANO],
        selectedTrackTitle: "Waiting So Long",
        selectedTrackYtId: null,
        spotifyId: "47QAK66loFDceMKTD4RJv1",
        deezerId: "72168592",
        designers: ["Mike Doud", "Norman Moore"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "supertramp_brother_where_you_bound",
        title: "Brother Where You Bound",
        artist: "Supertramp",
        year: 1985,
        country: regions.ENGLAND,
        criteria: [criteria.SOFT, criteria.TOUCHING_VOCALS, criteria.ART_POP, criteria.LENGTHY_TRACKS, criteria.TRANSITION, criteria.SOUND_COLLAGES],
        selectedTrackTitle: "Brother Where You Bound",
        selectedTrackYtId: "tWnepoNsi2I",
        spotifyId: "1KPGi1vxymWs9fInmwmc3d",
        deezerId: "72171382",
        designers: ["Norman Moore"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "surprise_assault_on_merryland",
        title: "Assault On Merryland",
        artist: "Surprise",
        year: 1977,
        country: regions.USA,
        criteria: [criteria.STORYLINE, criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.C_FOLK, criteria.FANTASY, criteria.GLITTER, criteria.HEAVY],
        selectedTrackTitle: "The Acrobat Between The Stars",
        selectedTrackYtId: "9TBwXA_llX0",
        spotifyId: null,
        deezerId: null,
        designers: ["Phil Timper"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "the_surprise_package_free_up",
        title: "Free Up",
        artist: "The Surprise Package",
        year: 1968,
        country: regions.USA,
        criteria: [criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.JAM, criteria.CRISPY_SIXTIES],
        selectedTrackTitle: "Free Up",
        selectedTrackYtId: "ydSDjQlG5PI",
        spotifyId: "3s5YeRdnLltlcRAFuAe6rH",
        deezerId: "63044312",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sway_human_carnage",
        title: "Human Carnage",
        artist: "Sway",
        year: 1979,
        country: regions.BELGIUM,
        criteria: [criteria.HUMBLE, criteria.TRANSITION, criteria.C_PSYCHE, criteria.FUNNY, criteria.C_FOLK],
        selectedTrackTitle: "Why",
        selectedTrackYtId: "veqv9LfOsj0",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sweet_smoke_just_a_poke",
        title: "Just A Poke",
        artist: "Sweet Smoke",
        year: 1970,
        country: regions.USA,
        criteria: [criteria.JAM, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.C_PSYCHE, criteria.C_JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Baby Night",
        selectedTrackYtId: "s6L8ZCAt3DA",
        spotifyId: null,
        deezerId: null,
        designers: ["Jan Fijnheer"],
        similarAlbums: [],
        isAGem: true,
        description: `Two big smooth tracks in the middle Jazz and Rock music, heavily influenced by psychedelism and groove, with hummed vocals. Both tracks are split into sections with rhythm variations and modality changes, but still perfectly flows from start to finish. The music is warm, rousing, captivating - when not completely mezmerizing.`,
    },
    {
        id: "sweet_smoke_darkness_to_light",
        title: "Darkness To Light",
        artist: "Sweet Smoke",
        year: 1973,
        country: regions.USA,
        criteria: [criteria.LIVE, criteria.LENGTHY_TRACKS, criteria.ORIENTAL, criteria.SOUND_COLLAGES, criteria.C_PSYCHE, criteria.C_FOLK],
        selectedTrackTitle: null,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Habo"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sweet_smoke_live",
        title: "Live",
        artist: "Sweet Smoke",
        year: 1974,
        country: regions.USA,
        criteria: [criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZY_GROOVY, criteria.JAM],
        selectedTrackTitle: "First Jam",
        selectedTrackYtId: "tgPocHF2eMw",
        spotifyId: "4JhIdnuJ8nwNma8gUmRIGZ",
        deezerId: "310780",
        designers: ["Kochlowski"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "sweetwater_just_for_you",
        title: "Just For You",
        artist: "Sweetwater",
        year: 1970,
        country: regions.USA,
        criteria: [criteria.SOFT, criteria.JAZZY_GROOVY, criteria.FOLK, criteria.FEMALE],
        selectedTrackTitle: "Song Of Romeo",
        selectedTrackYtId: "_LXdlWNrItQ",
        spotifyId: "76AQ8HRZ2ANKMbH2Wpr5bb",
        deezerId: "82312",
        designers: ["Annette Del Zoppo"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "syd_barret_the_madcap_laughs",
        title: "The Madcap Laughs",
        artist: "Syd Barrett",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.CRISPY_SIXTIES, criteria.C_FOLK],
        selectedTrackTitle: "Long Gone",
        selectedTrackYtId: "nwisdIr61e4",
        spotifyId: "69jyJl6Lyo80nQae0X312i",
        deezerId: "13082894",
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "syd_barret_barrett",
        title: "Barrett",
        artist: "Syd Barrett",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.C_FOLK],
        selectedTrackTitle: "Dominoes",
        selectedTrackYtId: "1tY1aNaIazA",
        spotifyId: "4NPymgNRX8nRAvHVW8yJra",
        deezerId: "7369648",
        designers: ["Syd Barrett"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "synkopy_61_formule_1",
        title: "Formule 1",
        artist: "Synkopy 61",
        year: 1975,
        country: regions.CZECHIA,
        criteria: [criteria.CZECH, criteria.SOUND_COLLAGES, criteria.ORCHESTRAL_PARTS, criteria.SYMPHONIC],
        selectedTrackTitle: "Touhy",
        selectedTrackYtId: "MqxeWfcPshU",
        spotifyId: "03ihxr7oX4nbvC1diYucRq",
        deezerId: "64006352",
        designers: ["Svatopluk Žampa"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
]

export default albums
