import { regions } from "../regions"
import { criteria } from "../criteria"

const albums = [
    {
        id: "t_rex_my_people_were_fair_and_had_sky_in_their_hair_but_now_theyre_content_to_wear_stars_on_their_brows",
        title: `My People Were Fair And Had Sky In Their Hair... But Now They're Content To Wear Stars On Their Brows`,
        artist: "T. Rex",
        year: 1968,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Chateau In Virginia Waters",
        selectedTrackYtId: "qhhbyR0zbyc",
        spotifyId: "07VpaykqDhreXIMNzRNPDS",
        deezerId: "1741501",
        designers: ["George Underwood"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "t_rex_prophets_seers_and_sages_the_angels_of_the_ages",
        title: `Prophets, Seers & Sages The Angel Of The Ages`,
        artist: "T. Rex",
        year: 1968,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.C_PSYCHE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Wind Quartets",
        selectedTrackYtId: "Eu85mMrDeK4",
        spotifyId: "5NoSeEx6IXNqLu6qhMJ0hF",
        deezerId: "9465242",
        designers: ["Peter Sanders"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "t_rex_unicorn",
        title: `Unicorn`,
        artist: "T. Rex",
        year: 1969,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.C_PSYCHE],
        selectedTrackTitle: "The Throat Of Winter",
        selectedTrackYtId: "7X_NPxdyFZA",
        spotifyId: "6SI4Lk6pFuIbHz2GVJTmqF",
        deezerId: "1741241",
        designers: ["Peter Sanders"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "t_rex_a_beard_of_stars",
        title: `A Beard Of Stars`,
        artist: "T. Rex",
        year: 1970,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.C_PSYCHE],
        selectedTrackTitle: "By The Light Of A Magical Moon",
        selectedTrackYtId: "oat9RksVx7s",
        spotifyId: "1EihIcnkkp9Gq0JpCFKtE7",
        deezerId: "7434387",
        designers: ["Peter Sanders", "June Child"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "t_rex_t_rex",
        title: `T. Rex`,
        artist: "T. Rex",
        year: 1970,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.C_PSYCHE, criteria.BAROQUE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "The Wizard",
        selectedTrackYtId: "mfSSmy8B5GA",
        spotifyId: "2ySTMVl1F6ZJleoK3wk78Z",
        deezerId: "116083612",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "t_rex_tanx",
        title: `Tanx`,
        artist: "T. Rex",
        year: 1973,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.ROCK, criteria.C_PSYCHE, criteria.FANFARE, criteria.FEMALE],
        selectedTrackTitle: "Tenement Lady",
        selectedTrackYtId: "RRevLXPuWf0",
        spotifyId: "0XHQyIMqjmsVRJPqFsFbjO",
        deezerId: "1117516",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "t_rex_zinc_alloy_and_the_hidden_riders_of_tomorrow",
        title: `Zinc Alloy And The Hidden Riders Of Tomorrow`,
        artist: "T. Rex",
        year: 1974,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.ART_POP, criteria.C_PSYCHE, criteria.FANFARE, criteria.FEMALE],
        selectedTrackTitle: "Carsmile Smith & The Old Ones",
        selectedTrackYtId: "0xsL8c6XLaI",
        spotifyId: "4rglD4EKEc75OJp5VwTWIZ",
        deezerId: "1117508",
        designers: [],
        similarAlbums: [], // similar david bowie
        isAGem: false,
    },
    {
        id: "tai_phong_tai_phong",
        title: "Taï Phong",
        artist: "Taï Phong",
        year: 1975,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.GLITTER, criteria.SYMPHONIC],
        selectedTrackTitle: "Fields Of Gold",
        selectedTrackYtId: null,
        spotifyId: "3Z8DubxAWENlQd3pxJOKZE",
        deezerId: "8910221",
        designers: ["Lang"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tai_phong_windows",
        title: "Windows",
        artist: "Taï Phong",
        year: 1976,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.GLITTER, criteria.SYMPHONIC, criteria.JAZZY_GROOVY],
        selectedTrackTitle: `When It's The Season`,
        selectedTrackYtId: "aT1ngm-ADkY",
        spotifyId: "3pN57NmhgB98rHwk8b0VJr",
        deezerId: "8910217",
        designers: ["Lang"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO description`,
    },
    {
        id: "tai_phong_last_flight",
        title: "Last Flight",
        artist: "Taï Phong",
        year: 1979,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.GLITTER, criteria.SYMPHONIC, criteria.JAZZY_GROOVY, criteria.JAM, criteria.C_JAZZ, criteria.SOFT_SEVENTIES, criteria.ART_POP],
        selectedTrackTitle: "Last Flight",
        selectedTrackYtId: "LoGhi9weBO8",
        spotifyId: "5GsJLsUq8x3DklXymqiDub",
        deezerId: "8910241",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "talk_talk_spirit_of_eden",
        title: "Spirit Of Eden",
        artist: "Talk Talk",
        year: 1988,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.SOFT, criteria.INSTRUMENTAL, criteria.C_PSYCHE, criteria.ART_POP, criteria.C_JAZZ],
        selectedTrackTitle: "Wealth",
        selectedTrackYtId: "cU3xmt8WVpg",
        spotifyId: "4YXo7p7aubyVIbNLoVlBp9",
        deezerId: "302210",
        designers: ["James Marsh"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "talk_talk_laughing_stock",
        title: "Laughing Stock",
        artist: "Talk Talk",
        year: 1991,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.SOFT, criteria.INSTRUMENTAL, criteria.AMBIENT, criteria.ART_POP, criteria.C_JAZZ],
        selectedTrackTitle: "Myrrhman",
        selectedTrackYtId: "ckNZljhwLfs",
        spotifyId: "7vqMpYHIqqWQQc0IVR03ue",
        deezerId: "161721",
        designers: ["James Marsh"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_electronic_meditation",
        title: "Electronic Meditation",
        artist: "Tangerine Dream",
        year: 1970,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.EXPERIMENTAL, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `Journey Through A Burning Brain`,
        selectedTrackYtId: "V6V0PpUR_dA",
        spotifyId: "2Tdy3aYYZXt74rdIhycvHc",
        deezerId: "116851742",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_alpha_centauri",
        title: "Alpha Centauri",
        artist: "Tangerine Dream",
        year: 1971,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.EXPERIMENTAL, criteria.AMBIENT, criteria.C_ELECTRO, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `Fly And Collision Of Comas Sola`,
        selectedTrackYtId: "sjwYDtANKFM",
        spotifyId: "4r0Rkjd3C9czpc3NbDDdCK",
        deezerId: "127047482",
        designers: ["Monique Froese"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_zeit",
        title: "Zeit",
        artist: "Tangerine Dream",
        year: 1972,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.AMBIENT, criteria.ELECTRO, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: `Zeit`,
        selectedTrackYtId: "zUAKEnasIvc",
        spotifyId: "7l4Kii7depfwIrtB9EDMk6",
        deezerId: "138047522",
        designers: ["Edgar Froese"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_atem",
        title: "Atem",
        artist: "Tangerine Dream",
        year: 1973,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: `Atem`,
        selectedTrackYtId: "gvKfBVUsE0Q",
        spotifyId: "6LlO1Sa0skYxUhdPPSId4h",
        deezerId: "116824512",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_phaedra",
        title: "Phaedra",
        artist: "Tangerine Dream",
        year: 1974,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: `Sequent 'C'`,
        selectedTrackYtId: "Jb_hDcNr5KQ",
        spotifyId: "7KRXWeJYBkyUmwOFTayiQk",
        deezerId: "301955",
        designers: ["Edgar Froese"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_rubycon",
        title: "Rubycon",
        artist: "Tangerine Dream",
        year: 1975,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: "Rubycon (Part I)",
        selectedTrackYtId: "4xl6zlD_hlE",
        spotifyId: "61BhEQyumLEqrRVREfQabB",
        deezerId: "301956",
        designers: ["Monique Froese"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_ricochet",
        title: "Ricochet",
        artist: "Tangerine Dream",
        year: 1975,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SOFT, criteria.LIVE, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: "Ricochet (Part II)",
        selectedTrackYtId: "XCsJOaPDJUE",
        spotifyId: "6iPUDn0rAVYuojEyEU0VJP",
        deezerId: "301957",
        designers: ["Monique Froese"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_stratosfear",
        title: "Stratosfear",
        artist: "Tangerine Dream",
        year: 1976,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.SOFT, criteria.AMBIENT, criteria.C_PSYCHE, criteria.ELECTRO],
        selectedTrackTitle: "Stratosfear",
        selectedTrackYtId: "2w8VsvJ40sM",
        spotifyId: "3gwpouV58Wxl0kd5OIT8m7",
        deezerId: "301958",
        designers: ["Brian Cooke", "Trevor Key"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_encore",
        title: "Encore",
        artist: "Tangerine Dream",
        year: 1977,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.LIVE, criteria.LENGTHY_TRACKS, criteria.ELECTRO, criteria.AMBIENT, criteria.C_PSYCHE],
        selectedTrackTitle: "Cherokee Lane",
        selectedTrackYtId: "3z_7qA2yac0",
        spotifyId: "76ofcWONgm5BNXpKFy9Wxz",
        deezerId: "99692152",
        designers: ["Monique Froese"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_cyclone",
        title: "Cyclone",
        artist: "Tangerine Dream",
        year: 1978,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.LENGTHY_TRACKS, criteria.INSTRUMENTAL, criteria.AMBIENT, criteria.ELECTRO, criteria.UNCOMMON_INSTRUMENTS, criteria.SPACY],
        selectedTrackTitle: "Bent Cold Sidewalk",
        selectedTrackYtId: "tR6Z6Sratvg",
        spotifyId: "3gwpouV58Wxl0kd5OIT8m7",
        deezerId: "99688432",
        designers: ["Edgar Froese"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tangerine_dream_force_majeure",
        title: "Force Majeure",
        artist: "Tangerine Dream",
        year: 1979,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.LENGTHY_TRACKS, criteria.INSTRUMENTAL, criteria.AMBIENT, criteria.ELECTRO, criteria.SPACY],
        selectedTrackTitle: "Cloudburst Flight",
        selectedTrackYtId: "cFTmznY0sgw",
        spotifyId: "3Fwvk0okeHHvxT5s90mK8T",
        deezerId: "99688482",
        designers: ["Monique Froese"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tea_and_symphony_an_asylum_for_the_musically_insane",
        title: "An Asylum For The Musically Insane",
        artist: "Tea And Symphony",
        year: 1969,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.C_PSYCHE, criteria.FUNNY, criteria.FOLK, criteria.CRISPY_SIXTIES],
        selectedTrackTitle: "Sometime",
        selectedTrackYtId: "91xllZBR8ps",
        spotifyId: "5QNTy5elpS2oC2mrVmfNo1",
        deezerId: null,
        designers: ["Peter Thaine"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tea_and_symphony_jo_sago",
        title: "Jo Sago",
        artist: "Tea And Symphony",
        year: 1970,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.STORYLINE, criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZY_GROOVY, criteria.ROCK_OPERA, criteria.FOLK],
        selectedTrackTitle: "Yourself",
        selectedTrackYtId: "YlyCN0xb37g",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "terpandre_terpandre",
        title: "Terpandre",
        artist: "Terpandre",
        year: 1981,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.UNCOMMON_INSTRUMENTS, criteria.C_JAZZ, criteria.ODD_RHYTHM, criteria.SOFT_SEVENTIES, criteria.SOFT, criteria.C_ELECTRO],
        selectedTrackTitle: "Carrousel",
        selectedTrackYtId: "BHGGHyd1amY",
        spotifyId: "2iy60Te5aOKNYi1DESFaHR",
        deezerId: "46213",
        designers: ["Bernard Monerri"],
        similarAlbums: ["aurora_aurora"],
        isAGem: false,
    },
    {
        id: "thalassa_suffer_and_misery",
        title: "Suffer And Misery",
        artist: "Thalassa",
        year: 1982,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.ODD_RHYTHM, criteria.GLITTER, criteria.SOFT, criteria.C_ELECTRO, criteria.NEO_EIGHTIES, criteria.SYMPHONIC],
        selectedTrackTitle: "Far From Me",
        selectedTrackYtId: "o6IZVtde0Es",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "thijs_van_leer_o_my_love",
        title: "O My Love",
        artist: "Thijs Van Leer",
        year: 1975,
        country: regions.NETHERLANDS,
        cover: ".jpg",
        criteria: [criteria.JAZZY_GROOVY, criteria.INSTRUMENTAL, criteria.C_JAZZ, criteria.SOFT, criteria.SOFT_SEVENTIES, criteria.FEMALE, criteria.ART_POP, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Peacemaker",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "thijs_van_leer_nice_to_have_met_you",
        title: "Nice To Have Met You",
        artist: "Thijs Van Leer",
        year: 1975,
        country: regions.NETHERLANDS,
        cover: ".jpg",
        criteria: [criteria.JAZZY_GROOVY, criteria.INSTRUMENTAL, criteria.C_JAZZ, criteria.SOFT, criteria.SOFT_SEVENTIES, criteria.FEMALE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Tonight Beneath The Sky",
        selectedTrackYtId: "QehxfzKP-40",
        spotifyId: null,
        deezerId: null,
        designers: ["Richard L. Hess"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "thin_lizzy_thin_lizzy",
        title: "Thin Lizzy",
        artist: "Thin Lizzy",
        year: 1971,
        country: regions.IRELAND,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.BLUESY],
        selectedTrackTitle: "Eire",
        selectedTrackYtId: "DBLFJo5j0F4",
        spotifyId: "7w9rDEQYLJRWcRUctOFbPy",
        deezerId: "262661",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "thin_lizzy_shades_of_blue_orphanage",
        title: "Shades Of Blue Orphanage",
        artist: "Thin Lizzy",
        year: 1972,
        country: regions.IRELAND,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.ODD_RHYTHM, criteria.SOFT, criteria.BLUESY],
        selectedTrackTitle: "Shades Of Blue Orphanage",
        selectedTrackYtId: "RLOjJZO6Nro",
        spotifyId: "6jXNB46aXlL2oWY03GtFHy",
        deezerId: "245501",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "think_variety",
        title: "Variety",
        artist: "Think",
        year: 1973,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.UNCOMMON_INSTRUMENTS, criteria.JAZZY_GROOVY, criteria.BAROQUE, criteria.LENGTHY_TRACKS, criteria.JAM, criteria.C_PSYCHE, criteria.ODD_RHYTHM],
        selectedTrackTitle: `Variety`,
        selectedTrackYtId: "pZDiFhsfQNM",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: ["bloodrock_whirlwind_tongues"],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "thirsty_moon_thirsty_moon",
        title: "Thirsty Moon",
        artist: "Thirsty Moon",
        year: 1972,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.JAM, criteria.LENGTHY_TRACKS, criteria.INSTRUMENTAL, criteria.SPACY, criteria.C_PSYCHE],
        selectedTrackTitle: `Yellow Sunshine`,
        selectedTrackYtId: "ry6ebAS5o7E",
        spotifyId: "44vEABhvKv1UdqEwjxiVB2",
        deezerId: "273030",
        designers: ["Gil Funccius"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "thirsty_moon_youll_never_come_back",
        title: "You'll Never Come Back",
        artist: "Thirsty Moon",
        year: 1973,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.JAM, criteria.LENGTHY_TRACKS, criteria.INSTRUMENTAL, criteria.SPACY, criteria.C_PSYCHE],
        selectedTrackTitle: `You'll Never Come Back`, // TODO?
        selectedTrackYtId: "TODO",
        spotifyId: "2JHnHWtumTvMT2VwYxTFtH",
        deezerId: "272533",
        designers: ["Gil Funccius"],
        similarAlbums: [],
        isAGem: true, // TODO gem? je crois pas
        description: `TODO Description`,
    },
    {
        id: "thirsty_moon_blitz",
        title: "Blitz",
        artist: "Thirsty Moon",
        year: 1975,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.JAM, criteria.LENGTHY_TRACKS, criteria.INSTRUMENTAL, criteria.C_ELECTRO, criteria.ODD_RHYTHM, criteria.ROCK],
        selectedTrackTitle: `Rainbow`,
        selectedTrackYtId: null,
        spotifyId: "46nGeCVYFZnPnjOWiBsGqo",
        deezerId: "266354",
        designers: ["Gil Funccius"],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO introuvable Thirsty Moon - A Real Good Time - 1976
    // TODO introuvable Thirsty Moon - Star Chaser - 1981
    {
        id: "titus_groan_titus_groan",
        title: "Titus Groan",
        artist: "Titus Groan",
        year: 1970,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.ROCK],
        selectedTrackTitle: `It Wasn't For You`,
        selectedTrackYtId: "7QC1hQyn8-0",
        spotifyId: "0mlj4Hjj145o9dJIc3dm1w",
        deezerId: "8875809",
        designers: ["Sue Baws"],
        similarAlbums: ["fuzzy_duck_fuzzy_duck"],
        isAGem: false,
    },
    {
        id: "tobruk_ad_lib",
        title: "Ad Lib",
        artist: "Tobruk",
        year: 1972,
        country: regions.BRAZIL,
        cover: ".jpg",
        criteria: [criteria.C_PSYCHE, criteria.ROCK],
        selectedTrackTitle: `Theme From My Mind`,
        selectedTrackYtId: "FcrlHdwvPYQ",
        spotifyId: "06LS8528Ve8EzAktmJOBfU",
        deezerId: "113738102",
        designers: ["Serge Holt Smith"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tonton_macoute_tonton_macoute",
        title: "Tonton Macoute",
        artist: "Tonton Macoute",
        year: 1971,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.JAM, criteria.C_JAZZ, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT],
        selectedTrackTitle: `Natural High (Part I)`,
        selectedTrackYtId: "nOKLkTs13Pw",
        spotifyId: null,
        deezerId: null,
        designers: ["Marcus Keef"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tontos_expanding_head_band_zero_time",
        title: "Zero Time",
        artist: `Tonto's Expanding Head Band`,
        year: 1971,
        country: regions.USA,
        cover: ".jpg",
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.C_PSYCHE],
        selectedTrackTitle: "Timewhys",
        selectedTrackYtId: "NqSrswia1-E",
        spotifyId: "1TIAU6CbjQCF6LJ7uTj7O6",
        deezerId: "7530433",
        designers: ["Carol Hertzer"],
        similarAlbums: ["jean_michel_jarre_oxygene"],
        isAGem: false,
    },
    {
        id: "tontos_expanding_head_band_its_about_time",
        title: `It's About Time`,
        artist: `Tonto's Expanding Head Band`,
        year: 1974,
        country: regions.USA,
        cover: ".jpg",
        criteria: [criteria.ELECTRO, criteria.INSTRUMENTAL, criteria.C_PSYCHE, criteria.SOFT, criteria.UNCOMMON_INSTRUMENTS, criteria.TRANSITION],
        selectedTrackTitle: "The Boatman",
        selectedTrackYtId: "R1Bv9UCqbD4",
        spotifyId: null,
        deezerId: null,
        designers: ["Joan Nielsen"],
        similarAlbums: ["jean_michel_jarre_equinoxe"],
        isAGem: false,
    },
    {
        id: "tortilla_flat_fur_ein_3_4_stundchen",
        title: "Für Ein 3/4 Stündchen",
        artist: "Tortilla Flat",
        year: 1974,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.INSTRUMENTAL, criteria.C_JAZZ, criteria.JAM, criteria.GERMAN, criteria.JAZZY_GROOVY, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Rumpelstilzchen",
        selectedTrackYtId: "7FCB5Xqd-Y4",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "totem_totem",
        title: "Totem",
        artist: "Totem",
        year: 1971,
        country: regions.ARGENTINA,
        cover: ".jpg",
        criteria: [criteria.SPANISH, criteria.LATINO, criteria.JAZZY_GROOVY, criteria.JAM, criteria.ROCK],
        selectedTrackTitle: `Dedos`,
        selectedTrackYtId: "zqekc2zaw9A",
        spotifyId: "34ywELgakejCKU2p37wJJ8",
        deezerId: "13169398",
        designers: ["Juan Bernardo Arruabarrena"],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO INTROUVABLE Totem - Descarga - 1972 - 13169422 + 2VuAqlqUuiTA4oCQ1Yn00y
    // TODO INTROUVABLE Totem - Corrupción - 1973 - 13328521 + 04I3FnfN1OPHoFCSOxGMNG
    {
        id: "trapeze_trapeze",
        title: "Trapeze",
        artist: "Trapeze",
        year: 1970,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.SOFT, criteria.FOLK, criteria.FANTASY],
        selectedTrackTitle: `The Giant's Dead Hoorah!`,
        selectedTrackYtId: "zqekc2zaw9A",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "trapeze_medusa",
        title: "Medusa",
        artist: "Trapeze",
        year: 1970,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.ROCK, criteria.C_FOLK],
        selectedTrackTitle: `Medusa`,
        selectedTrackYtId: "d0uVYOWdvz0",
        spotifyId: "2fcOwicqeKPPD3qh6Qe5zZ",
        deezerId: "102073882",
        designers: ["Phil Travers"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "trefle_reflet",
        title: "Reflet",
        artist: "Trèfle",
        year: 1978,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.STORYLINE, criteria.FRENCH, criteria.ROCK_OPERA, criteria.TOUCHING_VOCALS],
        selectedTrackTitle: `L'appel Du Temps`,
        selectedTrackYtId: "sGMIO4h7XMY",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tri_yann_urba",
        title: "Urba",
        artist: "Tri Yann",
        year: 1978,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.CELTIC, criteria.MEDIEVAL, criteria.FRENCH, criteria.BRETON],
        selectedTrackTitle: `Ann Disto Euz A Vro Zaoz`,
        selectedTrackYtId: "xy_UqUz3ZQk",
        spotifyId: "0pqzbaJcKp9RMlNhfcJbkB",
        deezerId: "134536622",
        designers: [],
        similarAlbums: [], // TODO similar malicorne
        isAGem: false,
    },
    {
        id: "tri_yann_an_heol_a_zo_glaz",
        title: "An Heol A Zo Glaz",
        artist: "Tri Yann",
        year: 1981,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.LENGTHY_TRACKS, criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.CELTIC, criteria.MEDIEVAL, criteria.FRENCH, criteria.BRETON, criteria.ODD_RHYTHM],
        selectedTrackTitle: `An Heol A Zo Glaz : Lug / Kan Ar kann / Dañs koz / Kan An Heol / Dañs Nevez`,
        selectedTrackYtId: "9yTAJfiFOIg",
        spotifyId: "6ATONcGr6Rydrr9eufzWEk",
        deezerId: "647137",
        designers: [],
        similarAlbums: ["gryphon_raindance"],
        isAGem: false,
    },
    {
        id: "tri_yann_le_vaisseau_de_pierre",
        title: "Le Vaisseau De Pierre",
        artist: "Tri Yann",
        year: 1988,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.CONCEPT, criteria.UNCOMMON_INSTRUMENTS, criteria.CELTIC, criteria.BLENDS, criteria.FRENCH, criteria.ROCK_OPERA, criteria.NEO_EIGHTIES, criteria.SYMPHONIC, criteria.FEMALE],
        selectedTrackTitle: `Digoradur`,
        selectedTrackYtId: null,
        spotifyId: "6Ocv5Q75AfMQ4D65UBx9jl",
        deezerId: null,
        designers: ["Enki Bilal"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "trikolon_cluster",
        title: "Cluster",
        artist: "Trikolon",
        year: 1969,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.LENGTHY_TRACKS, criteria.BAROQUE, criteria.C_JAZZ, criteria.JAM, criteria.LIVE],
        selectedTrackTitle: "In Search Of The Sun",
        selectedTrackYtId: "eOvUSqUw3Po",
        spotifyId: null,
        deezerId: null,
        designers: ["Ingo Petzke"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "triode_on_na_pas_fini_davoir_tout_vu",
        title: "On N'a Pas Fini D'avoir Tout Vu",
        artist: "Triode",
        year: 1971,
        country: regions.FRANCE,
        cover: ".jpg",
        criteria: [criteria.C_JAZZ, criteria.INSTRUMENTAL, criteria.ODD_RHYTHM, criteria.JAZZY_GROOVY, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Blahsha",
        selectedTrackYtId: "yjbePvFkwFY",
        spotifyId: "5sFETnSQ8MqXdCVWZoMZyM",
        deezerId: "73525172",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "triumvirat_mediterranean_tales",
        title: "Mediterranean Tales",
        artist: "Triumvirat",
        year: 1972,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.ODD_RHYTHM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.SPECTACULAR, criteria.PIANO],
        selectedTrackTitle: "Across The Waters",
        selectedTrackYtId: "msni0_j51IU",
        spotifyId: "2gu5catUel9XVrQT7FQhU8",
        deezerId: "305760",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "triumvirat_illusions_on_a_double_dimple",
        title: "Illusions On A Double Dimple",
        artist: "Triumvirat",
        year: 1973,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.ODD_RHYTHM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_ELECTRO, criteria.SPECTACULAR, criteria.PIANO],
        selectedTrackTitle: "Mister Ten Percent",
        selectedTrackYtId: "7VAA7M5nXx8",
        spotifyId: "1KDrZ0BG6DN9odiHb9sE25",
        deezerId: "305653",
        designers: ["Kochlowski"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "triumvirat_spartacus",
        title: "Spartacus",
        artist: "Triumvirat",
        year: 1975,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.CONCEPT, criteria.ELECTRO, criteria.ART_POP, criteria.PIANO],
        selectedTrackTitle: "The March To The Eternal City",
        selectedTrackYtId: "TmTZpQYMzN8",
        spotifyId: "5CV4ZQy6NS9GcpMUAGZhYE",
        deezerId: "305759",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "tudor_lodge_tudor_lodge",
        title: "Tudor Lodge",
        artist: "Tudor Lodge",
        year: 1971,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.FOLK, criteria.FEMALE, criteria.UNCOMMON_INSTRUMENTS, criteria.SOFT],
        selectedTrackTitle: "Lady's Changing Home",
        selectedTrackYtId: "ldctNtos6eI",
        spotifyId: "2dfISAR6fGNWBk1heHvRBY",
        deezerId: "161747",
        designers: ["Phil Duffy"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "the_turtles_the_turtles_present_the_battle_of_the_band",
        title: "The Turtles Present The Battle Of The Bands",
        artist: "The Turtles",
        year: 1968,
        country: regions.USA,
        cover: ".jpg",
        criteria: [criteria.CONCEPT, criteria.FUNNY, criteria.ROCK, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Food",
        selectedTrackYtId: "2UEE0cjQ8EY",
        spotifyId: "155OAoTAYR4Uu0LpSMvy5W",
        deezerId: "148674",
        designers: [],
        similarAlbums: ["procol_harum_grand_hotel"], // TODO similar electric light orchestra
        isAGem: false,
    },
    {
        id: "the_turtles_turtle_soup",
        title: "Turtle Soup",
        artist: "The Turtles",
        year: 1969,
        country: regions.USA,
        cover: ".jpg",
        criteria: [criteria.ROCK, criteria.C_PSYCHE],
        selectedTrackTitle: "Somewhere Friday Night",
        selectedTrackYtId: "-UawZQJdGe4",
        spotifyId: "0kcb49VdiGSb7Qii0v0jIc",
        deezerId: "204993",
        designers: [],
        similarAlbums: [], // TODO close to early jefferson airplane
        isAGem: false,
    },
    {
        id: "twenty_sixty_six_and_then_reflections_on_the_future",
        title: "Reflections On The Future",
        artist: "Twenty Sixty Six And Then",
        year: 1972,
        country: regions.GERMANY,
        cover: ".jpg",
        criteria: [criteria.LENGTHY_TRACKS, criteria.JAM, criteria.SYMPHONIC, criteria.SOUND_COLLAGES, criteria.ROCK_OPERA, criteria.C_PSYCHE],
        selectedTrackTitle: "Butterking",
        selectedTrackYtId: "7D59S0VnNFs",
        spotifyId: "3SsrcQg9ODrQJgX2PNQMmN",
        deezerId: "12554860",
        designers: ["Günter Karl"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "twink_think_pink",
        title: "Think Pink",
        artist: "Twink",
        year: 1970,
        country: regions.ENGLAND,
        cover: ".jpg",
        criteria: [criteria.C_PSYCHE, criteria.FUNNY, criteria.ORIENTAL, criteria.C_FOLK],
        selectedTrackTitle: "Tiptoe On The Highest Hill",
        selectedTrackYtId: "DP0DO43Q59Y",
        spotifyId: "1VK3FcX004p6M3LdaQukU7",
        deezerId: "437597",
        designers: ["Hipgnosis"],
        similarAlbums: [],
        isAGem: false,
    },
]

export default albums
