import { regions } from "../regions"
import { criteria } from "../criteria"

/**
 * @type {Array.<import(".").Album>}
 */
const albums = [
    {
        id: "van_der_graaf_generator_the_aerosol_grey_machine",
        title: "The Aerosol Grey Machine",
        artist: "Van Der Graaf Generator",
        year: 1969,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.C_FOLK, criteria.CRISPY_SIXTIES],
        selectedTrackTitle: "Octopus",
        selectedTrackYtId: "N91EyGMzvgc",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_der_graaf_generator_the_least_that_we_can_do_is_wave_to_each_other",
        title: "The Least We Can Do Is Wave To Each Other",
        artist: "Van Der Graaf Generator",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.C_FOLK],
        selectedTrackTitle: "After The Flood",
        selectedTrackYtId: "oJUu9-s15PQ",
        spotifyId: "5GuP6isw4DZpsTaucdWkC5",
        deezerId: "306126",
        designers: ["CCS", "Jim Flynn"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_der_graaf_generator_h_to_he_who_am_the_only_one",
        title: "H To He, Who Am The Only One",
        artist: "Van Der Graaf Generator",
        year: 1970,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: "The Emperor In His War Room",
        selectedTrackYtId: "4wtUFJPGE0I",
        spotifyId: "4kpBJuFpZBIuw4PQVxrN4t",
        deezerId: "306127",
        designers: ["Paul Whitehead"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_der_graaf_generator_pawn_hearts",
        title: "Pawn Hearts",
        artist: "Van Der Graaf Generator",
        year: 1971,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: "Lemmings",
        selectedTrackYtId: "_Earfbot_uI",
        spotifyId: "5Lrsef2F6ZHNC5yIUEJouw",
        deezerId: "306125",
        designers: ["Paul Whitehead"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_der_graaf_generator_godbluff",
        title: "Godbluff",
        artist: "Van Der Graaf Generator",
        year: 1975,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_PSYCHE, criteria.C_JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Arrow",
        selectedTrackYtId: "s_o5tMza1og",
        spotifyId: "4irlewoGTUPndEinKcavLF",
        deezerId: "301289",
        designers: ["John Pasche"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_der_graaf_generator_still_life",
        title: "Still Life",
        artist: "Van Der Graaf Generator",
        year: 1976,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: `Childlike Faith In Childhood's End`,
        selectedTrackYtId: "x16-qZJmpKA",
        spotifyId: "3RpOWx6c96pAbtE28GMApV",
        deezerId: "301431",
        designers: ["Paul Brierley"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_der_graaf_generator_world_record",
        title: "World Record",
        artist: "Van Der Graaf Generator",
        year: 1976,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: `Meurglys III, The Songwriter's Guild`,
        selectedTrackYtId: "Xo4IWcGrbbQ",
        spotifyId: "0kmpQ28yR2OJqnUxhjfRLU",
        deezerId: "306163",
        designers: ["A.D. Design"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_der_graaf_generator_the_quiet_zone_the_pleasure_dome",
        title: "The Quiet Zone / The Pleasure Dome",
        artist: "Van Der Graaf Generator",
        year: 1977,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "The Sphinx In The Face",
        selectedTrackYtId: "Xo4IWcGrbbQ",
        spotifyId: "0LkqdSpczzwdC2VlGrMDRB",
        deezerId: "306164",
        designers: ["Frank Sansom", "John Pasche", "Jess Artem", "Robin Schwartz"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_morrison_astral_weeks",
        title: "Astral Weeks",
        artist: "Van Morrison",
        year: 1968,
        country: regions.USA,
        criteria: [criteria.FOLK, criteria.UNCOMMON_INSTRUMENTS, criteria.TOUCHING_VOCALS, criteria.BAROQUE],
        selectedTrackTitle: "Cyprus Avenue",
        selectedTrackYtId: "L8jPDdHd9y8",
        spotifyId: "5PBbOTrlaXQauwwcq2ZiWO",
        deezerId: "345012",
        designers: [],
        similarAlbums: [], // TODO similar elton john
        isAGem: false,
    },
    {
        id: "van_morrison_moondance",
        title: "Moondance",
        artist: "Van Morrison",
        year: 1970,
        country: regions.USA,
        criteria: [criteria.ART_POP, criteria.UNCOMMON_INSTRUMENTS, criteria.BAROQUE],
        selectedTrackTitle: "Moondance",
        selectedTrackYtId: "7kfYOGndVfU",
        spotifyId: "5PfnCqRbdfIDMb1x3MPQam",
        deezerId: "7014850",
        designers: [],
        similarAlbums: ["bruce_springsteen_the_wild_the_innocent_the_e_street_shuffle"], // TODO similar elton john
        isAGem: false,
    },
    {
        id: "van_morrison_hard_nose_the_highway",
        title: "Hard Nose The Highway",
        artist: "Van Morrison",
        year: 1973,
        country: regions.USA,
        criteria: [criteria.FOLK, criteria.FEMALE, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "Snow In San Anselmo",
        selectedTrackYtId: "UjmiN_4g6ZU",
        spotifyId: "2F6h5yYUVNcqqeCG55O8Rw",
        deezerId: "11023474",
        designers: ["Robert Springett"],
        similarAlbums: [], // TODO similar elton john
        isAGem: false,
    },
    {
        id: "van_morrison_veedon_fleece",
        title: "Veedon Fleece",
        artist: "Van Morrison",
        year: 1974,
        country: regions.USA,
        criteria: [criteria.FOLK, criteria.ORCHESTRAL_PARTS, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "You Don't Pull No Punches, But You Don't Push The River",
        selectedTrackYtId: "ZRnFg3ltxgE",
        spotifyId: "1zvI5Kkxus94lhz0RvZWBf",
        deezerId: "11022986",
        designers: ["Tom Collins"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "van_morrison_common_one",
        title: "Common One",
        artist: "Van Morrison",
        year: 1980,
        country: regions.USA,
        criteria: [criteria.FOLK, criteria.SOFT, criteria.SOFT_SEVENTIES, criteria.LENGTHY_TRACKS, criteria.FANFARE, criteria.UNCOMMON_INSTRUMENTS, criteria.JAM],
        selectedTrackTitle: "When Heart Is Open",
        selectedTrackYtId: "5NiIEJ4UB1A",
        spotifyId: "4uUNf38ZQYcbVQqsPxfFNx",
        deezerId: "11030746",
        designers: ["Rudy Legname", "John Paul Jones"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vanessa_city_lips",
        title: "City Lips",
        artist: "Vanessa",
        year: 1975,
        country: regions.NORWAY,
        criteria: [criteria.C_PSYCHE, criteria.C_JAZZ, criteria.JAM, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.C_ELECTRO],
        selectedTrackTitle: "City Lips",
        selectedTrackYtId: "n5513ywp1sk",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vanessa_black_and_white",
        title: "Black And White",
        artist: "Vanessa",
        year: 1976,
        country: regions.NORWAY,
        criteria: [criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.C_JAZZ, criteria.C_ELECTRO, criteria.JAM, criteria.INSTRUMENTAL, criteria.ODD_RHYTHM, criteria.TECHNICAL],
        selectedTrackTitle: "Fragmomentum",
        selectedTrackYtId: "LJtOzi8axUs",
        spotifyId: null,
        deezerId: null,
        designers: ["Willy Haugen"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`, // Jame en folies, du jazz, du psyché, ça part en mini-section où ça en fout partout rythmiquement mais en étant syncho
    },
    {
        id: "vangelis_albedo_039",
        title: "Albedo 0.39",
        artist: "Vangelis",
        year: 1976,
        country: regions.GREECE,
        criteria: [criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.ELECTRO],
        selectedTrackTitle: "Pulstar",
        selectedTrackYtId: "G1cQnhOxqXw",
        spotifyId: "7M2EhhKnJYcmluPNzmB35N",
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vangelis_spiral",
        title: "Spiral",
        artist: "Vangelis",
        year: 1977,
        country: regions.GREECE,
        criteria: [criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.ELECTRO],
        selectedTrackTitle: "Spiral",
        selectedTrackYtId: "iW_qGMRmJAw",
        spotifyId: "6Tz3gRyPvHv8eDT5RZ2xXX",
        deezerId: "1208489",
        designers: ["Michael Hudson"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vangelis_beaubourg",
        title: "Beaubourg",
        artist: "Vangelis",
        year: 1978,
        country: regions.GREECE,
        criteria: [criteria.EXPERIMENTAL, criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.ELECTRO],
        selectedTrackTitle: "Beaubourg (Part I)",
        selectedTrackYtId: "iW_qGMRmJAw",
        spotifyId: "4wC0IlgUIbgVdUm0jH5mPU",
        deezerId: null,
        designers: ["Louis East", "Vangelis"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vauxdvihl_to_dimension_logic",
        title: "To Dimension Logic",
        artist: "Vauxdvihl",
        year: 1994,
        country: regions.GREECE,
        criteria: [criteria.ODD_RHYTHM, criteria.HEAVY, criteria.NEO_EIGHTIES, criteria.TRANSITION],
        selectedTrackTitle: "To Dimension Logic",
        selectedTrackYtId: "iW_qGMRmJAw",
        spotifyId: "1WIvCCikAQJifBsqWmnnTQ",
        deezerId: null,
        designers: [],
        similarAlbums: ["dream_theater_when_dream_and_day_unite", "queensryche_operation_mindcrime"],
        isAGem: false,
    },
    {
        id: "velvett_fogg_velvett_fogg",
        title: `Velvett Fogg`,
        artist: `Velvett Fogg`,
        year: 1969,
        country: regions.ENGLAND,
        criteria: [criteria.C_PSYCHE, criteria.JAM, criteria.GREASY_SEVENTIES, criteria.ROCK],
        selectedTrackTitle: "Yellow Cave Woman",
        selectedTrackYtId: "RJrRAWPTm7w",
        spotifyId: "75iGQvtuxZn2ZqJ0ce3gMp",
        deezerId: "13934446",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vent_dest_vent_dest",
        title: `Vent D'est`,
        artist: `Vent D'est`,
        year: 1980,
        country: regions.FRANCE,
        criteria: [criteria.FRENCH, criteria.C_ELECTRO, criteria.SOFT, criteria.SOFT_SEVENTIES, criteria.JAM, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: "La Toile",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vermillion_sands_water_blue",
        title: "Water Blue",
        artist: "Vermillion Sands",
        year: 1987,
        country: regions.JAPAN,
        criteria: [criteria.C_ELECTRO, criteria.FEMALE, criteria.NEO_EIGHTIES, criteria.JAPANESE, criteria.JAM, criteria.SYMPHONIC, criteria.C_FOLK],
        selectedTrackTitle: "Ashes Of The Time",
        selectedTrackYtId: "VSAuQmrSuvw",
        spotifyId: "6Q4KW9pIkrbRnu14OyLqme",
        deezerId: "7403352",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "victor_perainos_kingdom_come_no_mans_land",
        title: "No Man's Land",
        artist: "Victor Peraino's Kingdom Come",
        year: 1975,
        country: regions.USA,
        criteria: [criteria.C_PSYCHE, criteria.GLITTER, criteria.C_ELECTRO, criteria.SYMPHONIC],
        selectedTrackTitle: "Empires Of Steel",
        selectedTrackYtId: "k0YQlylrdWE",
        spotifyId: "5IpM8tpbrmXQc0Wa6FwqIQ",
        deezerId: "596920",
        designers: ["Jim Beveridge"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vindication_vindication",
        title: "Vindication",
        artist: "Vindication",
        year: 1974,
        country: regions.USA,
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.C_ELECTRO],
        selectedTrackTitle: "Master Law",
        selectedTrackYtId: "__dmTTvVHLU",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "violinski_no_cause_for_alarm",
        title: "No Cause For Alarm",
        artist: "Violinski",
        year: 1979,
        country: regions.ENGLAND,
        criteria: [criteria.ART_POP, criteria.NEO_EIGHTIES],
        selectedTrackTitle: "No Cause For Alarm",
        selectedTrackYtId: "JLf8NGawsrQ",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    // TODO Introuvable - Violinski - Stop Cloning About - 1980
    {
        id: "visitor_2035_visitor_2035",
        title: "Visitor 2035",
        artist: "Visitor 2035",
        year: 1978,
        country: regions.ENGLAND,
        criteria: [criteria.ODD_RHYTHM, criteria.INSTRUMENTAL, criteria.JAM, criteria.C_ELECTRO, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "Center Of The Winds",
        selectedTrackYtId: "7DMy4F3GDiM",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "visitors_visitors",
        title: "Visitors",
        artist: "Visitors",
        year: 1974,
        country: regions.FRANCE,
        criteria: [criteria.C_PSYCHE, criteria.SYMPHONIC, criteria.SPECTACULAR, criteria.FRENCH, criteria.SCI_FI, criteria.ROCK_OPERA, criteria.LATIN],
        selectedTrackTitle: "Dies Irae",
        selectedTrackYtId: "FhAFJw9jy50",
        spotifyId: "1xcA4OIY9He8YNvD1JKa8m",
        deezerId: "431456",
        designers: [],
        similarAlbums: ["rockets_plasteroid"],
        isAGem: false,
    },
    {
        id: "visitors_visitors_81",
        title: "Visitors",
        artist: "Visitors '81",
        year: 1981,
        country: regions.FRANCE,
        criteria: [criteria.ELECTRO, criteria.C_PSYCHE, criteria.FRENCH],
        selectedTrackTitle: "Réveille-Toi - Svegliati - Get Up!",
        selectedTrackYtId: "D4Df28eJRlk",
        spotifyId: "0ZIiwwxY1D0tr8WoOfQrj4",
        deezerId: "67462032",
        designers: ["Wojtek Siudmak"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "vos_voisins_vos_voisins",
        title: "Vos Voisins",
        artist: "Vos Voisins",
        year: 1971,
        country: regions.QUEBEC,
        criteria: [criteria.FRENCH, criteria.JAZZY_GROOVY, criteria.FEMALE, criteria.PIANO, criteria.C_PSYCHE, criteria.C_ELECTRO],
        selectedTrackTitle: "Le Monstre De La Main",
        selectedTrackYtId: "NcMSO2owumA",
        spotifyId: null,
        deezerId: null,
        designers: ["Daniel Couvreur"],
        similarAlbums: [],
        isAGem: false,
    },
]

export default albums
