import regions from '../regions'
import { criteria } from '../criteria'

const albums = [
    {
        id: 'van_der_graaf_generator_the_aerosol_grey_machine',
        title: 'The Aerosol Grey Machine',
        artist: 'Van Der Graaf Generator',
        year: 1969,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.C_PSYCHE, criteria.C_FOLK, criteria.CRISPY_SIXTIES],
        selectedTrackTitle: 'Octopus',
        selectedTrackYtId: 'N91EyGMzvgc',
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'van_der_graaf_generator_the_least_that_we_can_do_is_wave_to_each_other',
        title: 'The Least We Can Do Is Wave To Each Other',
        artist: 'Van Der Graaf Generator',
        year: 1970,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.C_FOLK],
        selectedTrackTitle: 'After The Flood',
        selectedTrackYtId: 'oJUu9-s15PQ',
        spotifyId: '5GuP6isw4DZpsTaucdWkC5',
        deezerId: '306126',
        designers: ['CCS', 'Jim Flynn'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'van_der_graaf_generator_h_to_he_who_am_the_only_one',
        title: 'H To He, Who Am The Only One',
        artist: 'Van Der Graaf Generator',
        year: 1970,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: 'The Emperor In His War Room',
        selectedTrackYtId: '4wtUFJPGE0I',
        spotifyId: '4kpBJuFpZBIuw4PQVxrN4t',
        deezerId: '306127',
        designers: ['Paul Whitehead'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'van_der_graaf_generator_pawn_hearts',
        title: 'Pawn Hearts',
        artist: 'Van Der Graaf Generator',
        year: 1971,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: 'Lemmings',
        selectedTrackYtId: '_Earfbot_uI',
        spotifyId: '5Lrsef2F6ZHNC5yIUEJouw',
        deezerId: '306125',
        designers: ['Paul Whitehead'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'van_der_graaf_generator_godbluff',
        title: 'Godbluff',
        artist: 'Van Der Graaf Generator',
        year: 1975,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.JAM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_PSYCHE, criteria.C_JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: 'Arrow',
        selectedTrackYtId: 's_o5tMza1og',
        spotifyId: '4irlewoGTUPndEinKcavLF',
        deezerId: '301289',
        designers: ['John Pasche'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'van_der_graaf_generator_still_life',
        title: 'Still Life',
        artist: 'Van Der Graaf Generator',
        year: 1976,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: `Childlike Faith In Childhood's End`,
        selectedTrackYtId: 'x16-qZJmpKA',
        spotifyId: '3RpOWx6c96pAbtE28GMApV',
        deezerId: '301431',
        designers: ['Paul Brierley'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'van_der_graaf_generator_world_record',
        title: 'World Record',
        artist: 'Van Der Graaf Generator',
        year: 1976,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.C_JAZZ],
        selectedTrackTitle: `Meurglys III, The Songwriter's Guild`,
        selectedTrackYtId: 'Xo4IWcGrbbQ',
        spotifyId: '0kmpQ28yR2OJqnUxhjfRLU',
        deezerId: '306163',
        designers: ['A.D. Design'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'van_der_graaf_generator_the_quiet_zone_the_pleasure_dome',
        title: 'The Quiet Zone / The Pleasure Dome',
        artist: 'Van Der Graaf Generator',
        year: 1977,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.SYMPHONIC, criteria.C_JAZZ, criteria.JAZZY_GROOVY],
        selectedTrackTitle: 'The Sphinx In The Face',
        selectedTrackYtId: 'Xo4IWcGrbbQ',
        spotifyId: '0LkqdSpczzwdC2VlGrMDRB',
        deezerId: '306164',
        designers: ['Frank Sansom', 'John Pasche', 'Jess Artem', 'Robin Schwartz'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'vanessa_city_lips',
        title: 'City Lips',
        artist: 'Vanessa',
        year: 1975,
        country: regions.NORWAY,
        cover: '.jpg',
        criteria: [criteria.C_PSYCHE, criteria.C_JAZZ, criteria.JAM, criteria.INSTRUMENTAL, criteria.JAZZY_GROOVY, criteria.C_ELECTRO],
        selectedTrackTitle: 'City Lips',
        selectedTrackYtId: 'n5513ywp1sk',
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'vanessa_black_and_white',
        title: 'Black And White',
        artist: 'Vanessa',
        year: 1976,
        country: regions.NORWAY,
        cover: '.jpg',
        criteria: [criteria.LENGTHY_TRACKS, criteria.C_PSYCHE, criteria.JAZZY_GROOVY, criteria.C_JAZZ, criteria.C_ELECTRO, criteria.JAM, criteria.INSTRUMENTAL, criteria.ODD_RHYTHM, criteria.TECHNICAL],
        selectedTrackTitle: 'Fragmomentum',
        selectedTrackYtId: 'LJtOzi8axUs',
        spotifyId: null,
        deezerId: null,
        designers: ['Willy Haugen'],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`, // Jame en folies, du jazz, du psyché, ça part en mini-section où ça en fout partout rythmiquement mais en étant syncho
    },
    {
        id: 'vangelis_albedo_039',
        title: 'Albedo 0.39',
        artist: 'Vangelis',
        year: 1976,
        country: regions.GREECE,
        cover: '.jpg',
        criteria: [criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.ELECTRO],
        selectedTrackTitle: 'Pulstar',
        selectedTrackYtId: 'G1cQnhOxqXw',
        spotifyId: '7M2EhhKnJYcmluPNzmB35N',
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'vangelis_spiral',
        title: 'Spiral',
        artist: 'Vangelis',
        year: 1977,
        country: regions.GREECE,
        cover: '.jpg',
        criteria: [criteria.INSTRUMENTAL, criteria.SYMPHONIC, criteria.ELECTRO],
        selectedTrackTitle: 'Spiral',
        selectedTrackYtId: 'iW_qGMRmJAw',
        spotifyId: '6Tz3gRyPvHv8eDT5RZ2xXX',
        deezerId: '1208489',
        designers: ['Michael Hudson'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'vangelis_beaubourg',
        title: 'Beaubourg',
        artist: 'Vangelis',
        year: 1978,
        country: regions.GREECE,
        cover: '.jpg',
        criteria: [criteria.EXPERIMENTAL, criteria.INSTRUMENTAL, criteria.LENGTHY_TRACKS, criteria.SYMPHONIC, criteria.ELECTRO],
        selectedTrackTitle: 'Beaubourg (Part I)',
        selectedTrackYtId: 'iW_qGMRmJAw',
        spotifyId: '4wC0IlgUIbgVdUm0jH5mPU',
        deezerId: null,
        designers: ['Louis East', 'Vangelis'],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: 'vauxdvihl_to_dimension_logic',
        title: 'To Dimension Logic',
        artist: 'Vauxdvihl',
        year: 1994,
        country: regions.GREECE,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.HEAVY, criteria.NEO_EIGHTIES, criteria.TRANSITION],
        selectedTrackTitle: 'To Dimension Logic',
        selectedTrackYtId: 'iW_qGMRmJAw',
        spotifyId: '1WIvCCikAQJifBsqWmnnTQ',
        deezerId: null,
        designers: [],
        similarAlbums: ['dream_theater_when_dream_and_day_unite', 'queensryche_operation_mindcrime'],
        isAGem: false,
    },
    {
        id: 'visitor_2035_visitor_2035',
        title: 'Visitor 2035',
        artist: 'Visitor 2035',
        year: 1978,
        country: regions.ENGLAND,
        cover: '.jpg',
        criteria: [criteria.ODD_RHYTHM, criteria.INSTRUMENTAL, criteria.JAM, criteria.C_ELECTRO, criteria.JAZZY_GROOVY],
        selectedTrackTitle: 'Center Of The Winds',
        selectedTrackYtId: '7DMy4F3GDiM',
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
]

export default albums