import { regions } from "../regions"
import { criteria } from "../criteria"

const albums = [
    {
        id: "gan_eden_gan_eden",
        title: "להקת גן עדן",
        artist: "להקת גן עדן",
        year: 1979,
        country: regions.ISRAEL,
        criteria: [criteria.HEBREW, criteria.ODD_RHYTHM, criteria.C_ELECTRO, criteria.SOFT_SEVENTIES],
        selectedTrackTitle: "פרמיקס",
        selectedTrackYtId: "He_RXiYpecc",
        spotifyId: "3rMv8mGgdowrKr5qwrxH9k",
        deezerId: "10310852",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "ktzat_acheret_nonames",
        title: "קצת אחרת",
        artist: "קצת אחרת",
        year: 1974,
        country: regions.ISRAEL,
        criteria: [criteria.HEBREW, criteria.SOPHISTICATED, criteria.ODD_RHYTHM, criteria.C_FOLK, criteria.UNCOMMON_INSTRUMENTS],
        selectedTrackTitle: "204",
        selectedTrackYtId: "OsfVoxjltfE",
        spotifyId: "6xjSKLHpGoFeXPmQbKiF8e",
        deezerId: null,
        designers: ["Yossi Orbach"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
    {
        id: "shem_tov_levi_in_the_mood",
        title: "שם-טוב לוי",
        artist: "שם טוב לוי",
        year: 1976,
        country: regions.ISRAEL,
        criteria: [criteria.HEBREW, criteria.C_FOLK, criteria.C_JAZZ, criteria.UNCOMMON_INSTRUMENTS, criteria.BAROQUE, criteria.ODD_RHYTHM],
        selectedTrackTitle: "יום הולדת",
        selectedTrackYtId: null,
        spotifyId: "0R9k164E4gaCTf0ZLI06Ih",
        deezerId: "99002502",
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sheshet_sheshet",
        title: "ששת",
        artist: "ששת",
        year: 1977,
        country: regions.ISRAEL,
        criteria: [criteria.HEBREW, criteria.SOPHISTICATED, criteria.ODD_RHYTHM, criteria.C_JAZZ, criteria.FEMALE, criteria.SOFT, criteria.JAM, criteria.JAZZY_GROOVY],
        selectedTrackTitle: "דבקה",
        selectedTrackYtId: "mOGQc2Wqm-c",
        spotifyId: "2lZrr5RAXLg0rf7JiaupJA",
        deezerId: "85144542",
        designers: ["David Tartakover"],
        similarAlbums: [],
        isAGem: true,
        description: `TODO Description`,
    },
]

export default albums
