import { regions } from "../regions"
import { criteria } from "../criteria"

/**
 * @type {Array.<import(".").Album>}
 */
const albums = [
    {
        id: "hideki_ishima_one_day",
        title: "One Day",
        artist: "石間秀機",
        year: 1973,
        country: regions.JAPAN,
        criteria: [criteria.C_PSYCHE, criteria.ROCK, criteria.SOFT, criteria.JAM, criteria.JAPANESE],
        selectedTrackTitle: `We're Just Tryin' My Way`,
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: ["wishbone_ash_pilgrimage"],
        isAGem: false,
    },
    {
        id: "osamu_kitajima_justin_heathcliff",
        title: "Justin Heathcliff",
        artist: "喜多嶋修",
        year: 1971,
        country: regions.JAPAN,
        criteria: [criteria.C_PSYCHE, criteria.ROCK, criteria.SOUND_COLLAGES],
        selectedTrackTitle: `To Live In Peace`,
        selectedTrackYtId: "Ps6Vpc6S86A",
        spotifyId: null,
        deezerId: null,
        designers: [],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sadistic_mika_band_sadistic_mika_band",
        title: "サディスティック・ミカ・バンド",
        artist: "サディスティック・ミカ・バンド",
        year: 1973,
        country: regions.JAPAN,
        criteria: [criteria.JAPANESE, criteria.ROCK, criteria.GREASY_SEVENTIES, criteria.C_PSYCHE, criteria.FEMALE],
        selectedTrackTitle: "怪傑シルバー・チャイルド",
        selectedTrackYtId: "2ayvwydJxOk",
        spotifyId: null,
        deezerId: null,
        designers: ["Workshop Mu!!"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sadistic_mika_band_black_ship",
        title: "黒船",
        artist: "サディスティック・ミカ・バンド",
        year: 1974,
        country: regions.JAPAN,
        criteria: [criteria.JAPANESE, criteria.ROCK, criteria.C_ELECTRO, criteria.ODD_RHYTHM],
        selectedTrackTitle: "四季頌歌",
        selectedTrackYtId: "_s8C9x1Ek2c",
        spotifyId: null,
        deezerId: null,
        designers: ["Kaoru Kato", "Takeshi Matsuyama"],
        similarAlbums: [],
        isAGem: false,
    },
    {
        id: "sadistic_mika_band_hot_menu",
        title: "Hot! Menu",
        artist: "サディスティック・ミカ・バンド",
        year: 1975,
        country: regions.JAPAN,
        criteria: [criteria.JAPANESE, criteria.JAZZY_GROOVY, criteria.ODD_RHYTHM, criteria.FEMALE],
        selectedTrackTitle: "Wah-Kah! Chico",
        selectedTrackYtId: null,
        spotifyId: null,
        deezerId: null,
        designers: ["Masayoshi Sukita"],
        similarAlbums: [],
        isAGem: false,
    },
]

export default albums
