const regions = {
    ARGENTINA: "Argentina",
    AUSTRALIA: "Australia",
    AUSTRIA: "Austria",
    BELARUS: "Belarus",
    BELGIUM: "Belgium",
    BOLIVIA: "Bolivia",
    BOSNIA_AND_HERZEGOVINA: "Bosnia and Herzegovina",
    BULGARIA: "Bulgaria",
    CANADA: "Canada",
    DENMARK: "Denmark",
    ENGLAND: "England",
    FRANCE: "France",
    GERMANY: "Germany",
    GREECE: "Greece",
    HUNGARY: "Hungary",
    INDIA: "India",
    INDONESIA: "Indonesia",
    ICELAND: "Iceland",
    IRELAND: "Ireland",
    ISRAEL: "Israel",
    ITALY: "Italy",
    JAPAN: "Japan",
    NETHERLANDS: "Netherlands",
    NEW_ZEALAND: "New Zealand",
    NORTHERN_IRELAND: "Northern Ireland",
    NORWAY: "Norway",
    PORTUGAL: "Portugal",
    QUEBEC: "Québec",
    RUSSIA: "Russia",
    SCOTLAND: "Scotland",
    SLOVAKIA: "Slovakia",
    SOUTH_AFRICA: "South Africa",
    SPAIN: "Spain",
    SWEDEN: "Sweden",
    SWITZERLAND: "Switzerland",
    USA: "USA", // TODO split by region
    VENEZUELA: "Venezuela",
    WALES: "Wales",
}

export default regions
