name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
      - uses: actions/checkout@v2.3.1
        with:
          node-version: '12'
          check-latest: true
      - run: npm ci
        run: |
          git config user.name "Benjent" && git config user.email "benjent@hotmail.fr"
          npm run gh-pages-deploy